const { buildMonetizationReleaseAudit } = require('../../scripts/write-monetization-release-audit');

describe('monetization release audit generator', () => {
  it('preserves the current release evidence and external-proof boundaries', () => {
    const content = buildMonetizationReleaseAudit({ auditDate: '2026-06-07' });

    expect(content).toContain('Date: 2026-06-07');
    expect(content).toContain('not a paid-launch approval');
    expect(content).toContain('src/__tests__/challengeShare.test.js');
    expect(content).toContain('src/__tests__/purchaseEntitlements.test.js');
    expect(content).toContain('src/__tests__/purchaseValidationReadiness.test.js');
    expect(content).toContain('purchase entitlement path');
    expect(content).toContain('audit-record contracts');
    expect(content).toContain('validation readiness');
    expect(content).toContain('src/__tests__/badgeCatalog.test.js');
    expect(content).toContain('src/__tests__/badgeService.test.js');
    expect(content).toContain('src/__tests__/badgeProgress.test.js');
    expect(content).toContain('catalog/category contracts');
    expect(content).toContain('Pro gating and award contracts');
    expect(content).toContain('badge progress and rank');
    expect(content).toContain('src/coreCampaignChallengeTemplates.js');
    expect(content).toContain('src/coreLongFormChallengeTemplates.js');
    expect(content).toContain('src/__tests__/challengeTemplates.test.js');
    expect(content).toContain('core campaign and long-form challenge templates');
    expect(content).toContain('campaign-ready core templates');
    expect(content).toContain('75-day long-form templates');
    expect(content).toContain('src/challengeMembershipJoinHelpers.js');
    expect(content).toContain('same `joinChallenge` and `createChallenge` export contracts');
    expect(content).toContain('src/challengeMembershipLeaveHelpers.js');
    expect(content).toContain('same `leaveChallenge` export contract');
    expect(content).toContain('src/challenges/challengeLaunchCardStats.js');
    expect(content).toContain('same `makeChallengeLaunchCardBlob` export contract');
    expect(content).toContain('src/challenges/useChallengeDiscoverySearch.js');
    expect(content).toContain('same Challenges tab state return contract');
    expect(content).toContain('src/challenges/useUserChallengeList.js');
    expect(content).toContain('src/challenges/usePendingChallengeInvite.js');
    expect(content).toContain('src/challenges/useCreatedChallengeShareActions.js');
    expect(content).toContain('same create challenge flow return contract');
    expect(content).toContain('native text-share fallback');
    expect(content).toContain('src/__tests__/profileShareCards.test.js');
    expect(content).toContain('monthly recap share text');
    expect(content).toContain('src/__tests__/profileShareCardSharing.test.js');
    expect(content).toContain('clipboard/download fallback');
    expect(content).toContain('src/profile/profileShareActionConfigs.js');
    expect(content).toContain('same profile share handler return contract');
    expect(content).toContain('src/profile/profileShareConfigHelpers.js');
    expect(content).toContain('same profile share config builder contracts');
    expect(content).toContain('src/profile/winCardCanvas.js');
    expect(content).toContain('same `makeWinCardBlob` export contract');
    expect(content).toContain('src/weeklyReportBuilder.js');
    expect(content).toContain('src/monthlyReportBuilder.js');
    expect(content).toContain('src/weeklyReportMetrics.js');
    expect(content).toContain('stable `src/weeklyReport.js` export barrel');
    expect(content).toContain('same `buildWeeklyReport` and `buildMonthlyReport` export contracts');
    expect(content).toContain('src/__tests__/weeklyCampaignDerivedData.test.js');
    expect(content).toContain('src/profile/profileWeeklyCampaignDerivedResult.js');
    expect(content).toContain('same `buildProfileWeeklyCampaignDerivedData` return contract');
    expect(content).toContain('no-automation/no-tracking boundary contracts');
    expect(content).toContain('src/__tests__/weeklyCampaignMarketingProps.test.js');
    expect(content).toContain('Weekly Campaign marketing prop contract');
    expect(content).toContain('src/__tests__/monetizationModel.test.js');
    expect(content).toContain('safe-denial negative evidence');
    expect(content).toContain('src/profile/monetizationSummaryCopy.js');
    expect(content).toContain('same `monetizationModel` export contract');
    expect(content).toContain('src/__tests__/partnerPerksProps.test.js');
    expect(content).toContain('member/admin/application prop grouping');
    expect(content).toContain('src/profile/partnerPerksMemberProps.js');
    expect(content).toContain('src/profile/partnerPerksAdminProps.js');
    expect(content).toContain('src/profile/partnerPerksApplicationProps.js');
    expect(content).toContain('same `buildPartnerPerksProps` return contract');
    expect(content).toContain('src/profile/partnerPerkInterestActionHandlers.js');
    expect(content).toContain('src/profile/partnerPerkClaimActionHandlers.js');
    expect(content).toContain('same `usePartnerPerkActions` return contract');
    expect(content).toContain('src/profile/partnerCampaignApplicationActionHandlers.js');
    expect(content).toContain('src/profile/partnerCampaignReviewActionHandlers.js');
    expect(content).toContain('same `usePartnerCampaignActions` return contract');
    expect(content).toContain('src/__tests__/engagementCopy.test.js');
    expect(content).toContain('Streak Rescue');
    expect(content).toContain('src/__tests__/monetizationPreLaunchCopy.test.js');
    expect(content).toContain('Customer Value Checklist');
    expect(content).toContain('src/__tests__/referralCopy.test.js');
    expect(content).toContain('Referral Story Sprint Kit');
    expect(content).toContain('src/__tests__/referralRewardSocialProofCopy.test.js');
    expect(content).toContain('Referral Reward Social Proof Kit');
    expect(content).toContain('src/__tests__/referralRewardDecisionCopy.test.js');
    expect(content).toContain('Referral Reward Decision Reply Kit');
    expect(content).toContain('src/profile/communitySupportReviewScreenInputs.js');
    expect(content).toContain('src/profile/communityFeatureReferralScreenInputs.js');
    expect(content).toContain('src/profile/communitySocialReminderScreenInputs.js');
    expect(content).toContain('same `buildCommunitySupportInputs` return contract');
    expect(content).toContain('src/profile/featureMediaActionHandlers.js');
    expect(content).toContain('src/profile/featureSubmissionActionHandlers.js');
    expect(content).toContain('src/profile/featureReviewActionHandlers.js');
    expect(content).toContain('same `useFeatureSubmissionActions` return contract');
    expect(content).toContain('src/__tests__/supportBillingCopy.test.js');
    expect(content).toContain('Support Decision');
    expect(content).toContain('src/profile/accountDeletionActionHandlers.js');
    expect(content).toContain('src/profile/supportRequestActionHandlers.js');
    expect(content).toContain('same `useAccountSupportActions` return contract');
    expect(content).toContain('src/__tests__/storeBillingSupportCopy.test.js');
    expect(content).toContain('Subscription Management Guidance');
    expect(content).toContain('crossPlatformParity.entitlementRecoveryReview.test.js');
    expect(content).toContain('request/review queue checks separate from support and billing copy-only checks');
    expect(content).toContain('src/userServices/entitlementRecoveryService.js');
    expect(content).toContain('same `src/userServices/monetizationSupportService.js` export contract');
    expect(content).toContain('src/profile/profileStoreReadinessDerivedData.js');
    expect(content).toContain('marketplace support copy and paid-launch gate data');
    expect(content).toContain('src/profile/profileStoreDerivedResult.js');
    expect(content).toContain('same `buildProfileStoreDerivedData` return contract');
    expect(content).toContain('src/profile/profileStoreReviewSupportInputs.js');
    expect(content).toContain('store catalog, monetization, and readiness bundle handoff');
    expect(content).toContain('src/profile/profileStoreReviewSupportDataInputs.js');
    expect(content).toContain('same store review/support data return contract');
    expect(content).toContain('src/profile/storeValidationReadinessActionHandlers.js');
    expect(content).toContain('src/profile/storeEvidenceRecordActionHandlers.js');
    expect(content).toContain('src/profile/storeEvidenceReviewActionHandlers.js');
    expect(content).toContain('same `buildStoreEvidenceActionHandlers` return contract');
    expect(content).toContain('src/profile/profileStoreBillingSupportData.js');
    expect(content).toContain('src/profile/profileStoreLifecycleSupportData.js');
    expect(content).toContain('same `buildProfileStoreSupportCardData` return contract');
    expect(content).toContain('src/profile/tribeProStorePropGroups.js');
    expect(content).toContain('same child component props');
    expect(content).toContain('src/profile/tribeProValueDemandProps.js');
    expect(content).toContain('src/profile/tribeProCommerceActionProps.js');
    expect(content).toContain('src/profile/tribeProStatusFooterProps.js');
    expect(content).toContain('same `src/profile/tribeProStorePropGroups.js` export contract');
    expect(content).toContain('src/__tests__/storeLifecycleCopy.test.js');
    expect(content).toContain('support-card ordering contracts');
    expect(content).toContain('src/__tests__/creatorPartnerCopy.test.js');
    expect(content).toContain('Creator Hosting Offer');
    expect(content).toContain('src/profile/creatorHostingCopyKits.js');
    expect(content).toContain('launch-link composition');
    expect(content).toContain('src/profile/creatorHostingReadinessCopyKits.js');
    expect(content).toContain('src/profile/creatorHostingReplyCopyKits.js');
    expect(content).toContain('same combined creator hosting copy export');
    expect(content).toContain('src/profile/CreatorCoachAdminSection.jsx');
    expect(content).toContain('src/profile/CreatorCoachMemberSection.jsx');
    expect(content).toContain('creator coach section contract');
    expect(content).toContain('src/profile/useCreatorRevenueState.js');
    expect(content).toContain('src/profile/usePartnerRevenueState.js');
    expect(content).toContain('src/profile/useMonetizationDemandState.js');
    expect(content).toContain('same `useProfileRevenueState` return contract');
    expect(content).toContain('src/profile/creatorProfileActionHandlers.js');
    expect(content).toContain('src/profile/creatorHostingApplicationActionHandlers.js');
    expect(content).toContain('same `useCreatorRevenueActions` return contract');
    expect(content).toContain('src/profile/profileCustomGoalActionHandlers.js');
    expect(content).toContain('src/profile/profileFrameActionHandlers.js');
    expect(content).toContain('src/profile/profileStreakRecoveryActionHandlers.js');
    expect(content).toContain('same `buildProfileProPreferenceActionHandlers` return contract');
    expect(content).toContain('src/profile/partnerRevenueInputGroups.js');
    expect(content).toContain('same `buildPartnerRevenueInputs` return contract');
    expect(content).toContain('src/profile/partnerRevenueCreatorScreenInputs.js');
    expect(content).toContain('src/profile/partnerRevenuePartnerScreenInputs.js');
    expect(content).toContain('src/profile/partnerRevenueDemandScreenInputs.js');
    expect(content).toContain('same `buildPartnerRevenueScreenInputs` return contract');
    expect(content).toContain('src/profile/profileEngagementCreatorCopyResult.js');
    expect(content).toContain('same engagement/creator copy return contract');
    expect(content).toContain('src/profile/profileShareActionInputs.js');
    expect(content).toContain('src/profile/profileComputedDataInputs.js');
    expect(content).toContain('same computed profile data return contract');
    expect(content).toContain('src/profile/profileEngagementState.js');
    expect(content).toContain('same `buildProfileEngagementState` export');
    expect(content).toContain('src/profile/profileScreenActivityStats.js');
    expect(content).toContain('src/profile/profileScreenBadgeData.js');
    expect(content).toContain('badge XP, rank, ranked percentage, and earned badge list');
    expect(content).toContain('same `buildProfileScreenStats` return contract');
    expect(content).toContain('src/profile/profileScreenStatsPresentation.js');
    expect(content).toContain('src/profile/profileScreenStatsResult.js');
    expect(content).toContain('src/profile/profileScreenDerivedResult.js');
    expect(content).toContain('src/profile/profileScreenDerivedDataBundles.js');
    expect(content).toContain('src/profile/profileScreenBundleInputs.js');
    expect(content).toContain('src/profile/profileScreenMonetizationCampaignInputs.js');
    expect(content).toContain('same `buildProfileScreenDerivedData` return contract');
    expect(content).toContain('src/profile/profileMonetizationCampaignDerivedData.js');
    expect(content).toContain('partner demand, revenue, Weekly Campaign, and creator engagement copy composition');
    expect(content).toContain('src/profile/profileEngagementCreatorCopyBundle.js');
    expect(content).toContain('same monetization campaign derived-data return contract');
    expect(content).toContain('src/__tests__/partnerMonetizationCopy.test.js');
    expect(content).toContain('Partner Campaign Decision');
    expect(content).toContain('crossPlatformParity.communityValueKits.test.js');
    expect(content).toContain('ambassador and customer value checks separate from monetization pathway and paid-offer readiness checks');
    expect(content).toContain('docs/feature-catalog/challenge-surfaces.md');
    expect(content).toContain('include-aware release checks preserving weekly campaign challenges, launch cards, referral attribution, premium-pack metadata, sponsor metadata, and Coach Host branding');
    expect(content).toContain('docs/feature-catalog/identity-progress-surfaces.md');
    expect(content).toContain('include-aware release checks preserving Badges, Leaderboard, Profile Appearance, Pro-only badge, avatar, photo, and Instagram handle contracts');
    expect(content).toContain('docs/feature-catalog/paid-store-surfaces.md');
    expect(content).toContain('include-aware release checks preserving the same catalog contract');
    expect(content).toContain('docs/feature-catalog/tribe-pro-entitlement-foundation.md');
    expect(content).toContain('include-aware release checks preserving Pro entitlements, analytics, custom goals, creator/coach mode, partner perks, campaign-planning, store-readiness guardrails, and paid-access release checks');
    expect(content).toContain('docs/feature-catalog/tribe-pro-release-guardrails.md');
    expect(content).toContain('include-aware release checks preserving Pro analytics gates, creator/coach safety rules, partner-perk safety rules, streak recovery constraints, challenge-pack creation gates, and future Pro-gated feature checks');
    expect(content).toContain('docs/feature-catalog/account-support-surfaces.md');
    expect(content).toContain('include-aware release checks preserving account deletion requests, support requests, admin review queues, copy-only decision replies, marketplace boundaries, and no-entitlement support contracts');
    expect(content).toContain('docs/feature-catalog/tracking-surfaces.md');
    expect(content).toContain('include-aware release checks preserving Home Dashboard, Activity Logging, points, streak, calendar, activity history, badge-check, and wearable-import contracts');
    expect(content).toContain('docs/feature-catalog/platform-release-surfaces.md');
    expect(content).toContain('include-aware release checks preserving Notifications, Deep Links, Release Safety, reminder, native notification, app-link, Universal Link, hosting, build-gate, and release-check contracts');
    expect(content).toContain('docs/feature-catalog/community-growth-surfaces.md');
    expect(content).toContain('include-aware release checks preserving Feature Submissions, Referral Invite Hooks, Community highlights, referral launch, and referral decision copy contracts');
    expect(content).toContain('docs/feature-catalog/sharing-reward-surfaces.md');
    expect(content).toContain('include-aware release checks preserving Progress Sharing, User Win Cards, Weekly Recap Sharing, Referral Reward Badges, and no-entitlement reward claim contracts');
    expect(content).toContain('docs/feature-catalog/store-product-catalog.md');
    expect(content).toContain('include-aware release checks preserving product IDs, receipt validation, restore/sync, entitlement-recovery, store-test evidence, and paid-launch guardrails');
    expect(content).toContain('docs/feature-catalog/weekly-campaign-copy-surfaces.md');
    expect(content).toContain('include-aware release checks preserving scheduler, launch-card, preflight, Story, Live, FAQ, caption, collab, retention, re-invite, no-automation, no-tracking, no-paid-live, consent, and app-first guardrails');
    expect(content).toContain('docs/instagram-content-bank/weekly-campaign-captions.md');
    expect(content).toContain('include-aware campaign checks preserving the same launch, education, highlight, comeback, progress-proof, admin-note, and recap copy');
    expect(content).toContain('docs/instagram-content-bank/weekly-campaign-weekend-captions.md');
    expect(content).toContain('include-aware campaign checks preserving Saturday founder/admin note and Sunday recap/next-week teaser copy');
    expect(content).toContain('docs/instagram-content-bank/story-sequences.md');
    expect(content).toContain('include-aware campaign checks preserving launch-day, comeback, weekend-push, and completion-recap Story frames');
    expect(content).toContain('docs/instagram-content-bank/dm-keyword-replies.md');
    expect(content).toContain('include-aware campaign checks preserving TRIBE, COMEBACK, FEATURE, PRO, PARTNER, and CREATOR manual replies');
    expect(content).toContain('docs/instagram-content-bank/comment-replies.md');
    expect(content).toContain('include-aware campaign checks preserving join, beginner, comeback, free-loop, posting, Feature Me, and wearable replies');
    expect(content).toContain('docs/instagram-content-bank/referral-copy.md');
    expect(content).toContain('include-aware campaign checks preserving invite, Story prompt, and referral-progress celebration copy');
    expect(content).toContain('docs/instagram-content-bank/feature-me-prompts.md');
    expect(content).toContain('include-aware campaign checks preserving submission, community-highlight CTA, review, and consent language');
    expect(content).toContain('docs/instagram-content-bank/paid-feature-safe-copy.md');
    expect(content).toContain('include-aware campaign checks preserving Pro and paid-pack before/after-validation copy plus store-validation and entitlement-QA guardrails');
    expect(content).toContain('docs/instagram-content-bank/creator-partner-outreach.md');
    expect(content).toContain('include-aware campaign checks preserving creator invite, follow-up, partner reply, paid-hosting, random-ad, and member-data guardrails');
    expect(content).toContain('docs/instagram-content-bank/seven-day-launch-pack.md');
    expect(content).toContain('include-aware campaign checks preserving day-by-day join, log, share, referral, and recap prompts');
    expect(content).toContain('docs/instagram-content-bank/hashtag-sets.md');
    expect(content).toContain('include-aware campaign checks preserving general, comeback, referral, and creator campaign tags');
    expect(content).toContain('docs/marketing-content-strategy/audience-lanes.md');
    expect(content).toContain('include-aware release checks preserving new-member, returning-member, contributor, creator, coach, and partner message/surface maps');
    expect(content).toContain('docs/marketing-content-strategy/instagram-growth-loops.md');
    expect(content).toContain('include-aware release checks preserving Weekly Campaign, share-card, community-highlight, referral, and creator/admin operating cues');
    expect(content).toContain('docs/marketing-content-strategy/engagement-retention.md');
    expect(content).toContain('include-aware release checks preserving first-week, comeback, challenge momentum, renewal recovery, cancellation feedback, and entitlement recovery guardrails');
    expect(content).toContain('docs/marketing-content-strategy/monetization-pathways.md');
    expect(content).toContain('include-aware release checks preserving subscription, premium challenge, creator/coaching, sponsor, paid community, merch/event, and trust guardrails');
    expect(content).toContain('docs/marketing-content-strategy/launch-phases.md');
    expect(content).toContain('include-aware release checks preserving release foundation, free challenge, paid validation, paid launch, and creator/partner expansion sequencing');
    expect(content).toContain('docs/monetization-roadmap/current-release-posture.md');
    expect(content).toContain('include-aware roadmap checks preserving Weekly Campaign, store-readiness, parity, copy-kit, and external-proof evidence');
    expect(content).toContain('docs/monetization-roadmap/revenue-ladder.md');
    expect(content).toContain('include-aware roadmap checks preserving Free Core, Tribe Pro, paid-pack, Feature Me, referral, creator/coach, and partnership monetization rules');
    expect(content).toContain('docs/monetization-roadmap/creator-partner-revenue-ladder.md');
    expect(content).toContain('include-aware roadmap checks preserving creator/coach, paid hosting, revenue-share, brand-partnership, sponsor-backed challenge, member-perk, random-ad, and trust-aligned monetization rules');
    expect(content).toContain('docs/monetization-roadmap/rollout-plan.md');
    expect(content).toContain('include-aware roadmap checks preserving phased Weekly Campaign, referral, Pro, paid-pack, creator/coach, and partnership status evidence');
    expect(content).toContain('docs/monetization-roadmap/social-growth-foundation.md');
    expect(content).toContain('include-aware roadmap checks preserving the Phase 1 Weekly Campaign, referral, Pro, paid-pack, creator/coach, partner, and store-readiness sequencing evidence');
    expect(content).toContain('docs/monetization-roadmap/weekly-campaign-social-growth.md');
    expect(content).toContain('include-aware roadmap checks preserving scheduler, launch-card, preflight, Story, Live, FAQ, caption, collab, retention, re-invite, no-automation, no-tracking, consent, app-first, referral, and content-calendar sequencing evidence');
    expect(content).toContain('docs/monetization-roadmap/pro-subscription-foundation.md');
    expect(content).toContain('include-aware roadmap checks preserving entitlement, store-readiness, recovery, evidence, analytics, creator/coach, referral-reward, and paid-access guardrail sequencing evidence');
    expect(content).toContain('crossPlatformParity.creatorHostingApplicationReview.test.js');
    expect(content).toContain('admin review-update checks separate from monetization launch demand and board checks');
    expect(content).toContain('crossPlatformParity.creatorHostingReplies.test.js');
    expect(content).toContain('objection and decision reply checks separate from creator readiness kit checks');
    expect(content).toContain('crossPlatformParity.communityContent.test.js');
    expect(content).toContain('crossPlatformParity.partnerCampaignDecisions.test.js');
    expect(content).toContain('crossPlatformParity.partnerPerkClaimReview.test.js');
    expect(content).toContain('admin review-update checks separate from member claim request and status-history checks');
    expect(content).toContain('crossPlatformParity.partnerPerkDecisionCopy.test.js');
    expect(content).toContain('crossPlatformParity.storeReviewPlanning.test.js');
    expect(content).toContain('crossPlatformParity.weeklyCampaignArchitecture.test.js');
    expect(content).toContain('crossPlatformParity.weeklyCampaignReviewPlanning.test.js');
    expect(content).toContain('review, storyboard, and experiment checks separate from scheduler, launch-card, and preflight checks');
    expect(content).toContain('Weekly Campaign Review Records are implemented across Web, iOS, and Android');
    expect(content).toContain('manual `weeklyCampaignReviews` admin evidence queues');
    expect(content).toContain('no attribution, tracking pixel, auto-posting, scraped-DM, purchase, entitlement, or paid-access side effects');
    expect(content).toContain('crossPlatformParity.weeklyCampaignStoryFollowUp.test.js');
    expect(content).toContain('crossPlatformParity.weeklyCampaignLiveContent.test.js');
    expect(content).toContain('crossPlatformParity.weeklyCampaignContentBank.test.js');
    expect(content).toContain('FAQ carousel and caption bank checks separate from Live Q&A and recap checks');
    expect(content).toContain('src/profile/weeklyCampaignStoryCopyCardDefinitions.js');
    expect(content).toContain('src/profile/weeklyCampaignLiveCopyCardDefinitions.js');
    expect(content).toContain('same combined card export');
    expect(content).toContain('src/profile/profileParityContractLabels.js');
    expect(content).toContain('same `PROFILE_PARITY_CONTRACT_LABELS` export');
    expect(content).toContain('crossPlatformParity.weeklyCampaignCollabLifecycle.test.js');
    expect(content).toContain('47 suites, 112 tests');
    expect(content).toContain('scripts/verify-react-build-timeout.js');
    expect(content).toContain('src/__tests__/buildRuntimeGuard.test.js');
    expect(content).toContain('BUILD_IDLE_TIMEOUT_MS');
    expect(content).toContain('scripts/verify-instagram-campaign-contracts.js');
    expect(content).toContain('scripts/instagram-campaign-document-tokens.js');
    expect(content).toContain('scripts/instagram-campaign-profile-contract-tokens.js');
    expect(content).toContain('document/content-bank checks separate from Web/iOS/Android profile copy checks');
    expect(content).toContain('Web/iOS/Android weekly campaign');
    expect(content).toContain('scripts/verify-release-utils.js');
    expect(content).toContain('without weakening release verification');
    expect(content).toContain('scripts/verify-release-documentation-contracts.js');
    expect(content).toContain('feature catalog, store-readiness, runtime, and parity-ledger');
    expect(content).toContain('src/app/useAppShellState.js');
    expect(content).toContain('src/app/useChallengeRefreshHandlers.js');
    expect(content).toContain('same `useAppAuthenticatedState` consumer contract');
    expect(content).toContain('src/app/AppAuthenticatedFrame.jsx');
    expect(content).toContain('same authenticated app rendering contract');
    expect(content).toContain('src/app/appAuthenticatedStateResult.js');
    expect(content).toContain('src/app/appAuthenticatedProps.js');
    expect(content).toContain('overlay, tab-content, and bottom-nav prop routing');
    expect(content).toContain('src/app/appTabContentProps.js');
    expect(content).toContain('same authenticated tab rendering contract');
    expect(content).toContain('src/onboardingLabels.js');
    expect(content).toContain('same onboarding question and label export contracts');
    expect(content).toContain('scripts/verify-platform-link-contracts.js');
    expect(content).toContain('Firebase hosting, AASA, assetlinks, and native deep-link');
    expect(content).toContain('scripts/verify-store-readiness-contracts.js');
    expect(content).toContain('no-paid-live evidence boundary');
    expect(content).toContain('scripts/store-readiness-release-contracts.js');
    expect(content).toContain('scripts/store-readiness-document-contracts.js');
    expect(content).toContain('docs/store-readiness/android-google-play.md');
    expect(content).toContain('include-aware readiness checks preserving package, Firebase, Google Sign-In, App Links, and Play Billing validation contracts');
    expect(content).toContain('docs/store-readiness/ios-app-store.md');
    expect(content).toContain('include-aware readiness checks preserving bundle ID, Apple Developer capabilities, Universal Links, App Store Connect credentials, receipt validation, and entitlement-write contracts');
    expect(content).toContain('scripts/store-readiness-document-token-groups.js');
    expect(content).toContain('scripts/store-readiness-core-document-tokens.js');
    expect(content).toContain('scripts/store-readiness-release-audit-document-tokens.js');
    expect(content).toContain('scripts/store-readiness-roadmap-document-tokens.js');
    expect(content).toContain('scripts/release-audit-script-document-tokens.js');
    expect(content).toContain('scripts/release-audit-output-document-tokens.js');
    expect(content).toContain('scripts/store-test-purchase-runbook-document-tokens.js');
    expect(content).toContain('scripts/monetization-release-audit-local-recheck-items.js');
    expect(content).toContain('writer focused on assembling sections');
    expect(content).toContain('env-template, readiness-doc, runbook, audit, roadmap, and catalog');
    expect(content).toContain('scripts/verify-monetization-engagement-contracts.js');
    expect(content).toContain('without changing release coverage');
    expect(content).toContain('scripts/verify-web-surface-contracts.js');
    expect(content).toContain('web-only module scans');
    expect(content).toContain('scripts/web-surface-contract-tokens.js');
    expect(content).toContain('derived-data, profile-module, app-shell, and challenge-surface');
    expect(content).toContain('scripts/monetization-engagement-copy-contracts.js');
    expect(content).toContain('static profile-copy parity list');
    expect(content).toContain('scripts/monetization-profile-copy-token-groups.js');
    expect(content).toContain('support/store, creator/partner, and referral/community');
    expect(content).toContain('scripts/support-store-profile-copy-tokens.js');
    expect(content).toContain('scripts/creator-partner-profile-copy-tokens.js');
    expect(content).toContain('scripts/referral-community-profile-copy-tokens.js');
    expect(content).toContain('scripts/parity-test-contracts.js');
    expect(content).toContain('without changing `npm run test:parity`');
    expect(content).toContain('App Store Connect purchase-validation credentials');
    expect(content).toContain('Google Play Developer API credentials');
    expect(content).toContain('Paid access must remain in review mode');
  });
});
