export function buildAppAuthenticatedProps({
  appState,
  user,
}) {
  return {
    bottomNavProps: {
      setTab: appState.setTab,
      tab: appState.tab,
    },
    overlayProps: {
      badgeQueue: appState.badgeQueue,
      challengeStats: appState.challengeStats,
      earnedBadges: appState.earnedBadges,
      handleLog: appState.handleLog,
      myHistory: appState.myHistory,
      selectedDay: appState.selectedDay,
      setBadgeQueue: appState.setBadgeQueue,
      setMyHistory: appState.setMyHistory,
      setSelectedDay: appState.setSelectedDay,
      setShowLog: appState.setShowLog,
      setShowProfile: appState.setShowProfile,
      setUserProfile: appState.setUserProfile,
      showLog: appState.showLog,
      showProfile: appState.showProfile,
      triggerBadgeCheck: appState.triggerBadgeCheck,
      user,
    },
    tabContentProps: {
      actCounts: appState.actCounts,
      allActivities: appState.allActivities,
      badgeCat: appState.badgeCat,
      challengeStats: appState.challengeStats,
      daysActive: appState.daysActive,
      earnedBadges: appState.earnedBadges,
      handleChallengeJoinHandled: appState.handleChallengeJoinHandled,
      handleChallengeStatsChanged: appState.handleChallengeStatsChanged,
      handleProgressShare: appState.handleProgressShare,
      handleShareTemplateSelect: appState.handleShareTemplateSelect,
      hasActivePro: appState.hasActivePro,
      myChallenges: appState.myChallenges,
      myHistory: appState.myHistory,
      pendingJoinCode: appState.pendingJoinCode,
      pendingReferralUid: appState.pendingReferralUid,
      savingShareTemplate: appState.savingShareTemplate,
      setBadgeCat: appState.setBadgeCat,
      setMyHistory: appState.setMyHistory,
      setSelectedDay: appState.setSelectedDay,
      setShowLog: appState.setShowLog,
      setShowProfile: appState.setShowProfile,
      setUserProfile: appState.setUserProfile,
      setTab: appState.setTab,
      shareTemplateId: appState.shareTemplateId,
      streak: appState.streak,
      tab: appState.tab,
      totalPts: appState.totalPts,
      triggerBadgeCheck: appState.triggerBadgeCheck,
      user,
      userProfile: appState.userProfile,
    },
  };
}
