export function buildAppAuthenticatedStateResult({
  activitySummary,
  badgeState,
  challengeRefreshHandlers,
  logState,
  pendingChallengeEntry,
  progressShareActions,
  publicShellState,
  levelUpState,
  rankRules,
  userChallengeData,
}) {
  return {
    actCounts: activitySummary.actCounts,
    allActivities: activitySummary.allActivities,
    ...publicShellState,
    badgeQueue: badgeState.badgeQueue,
    challengeStats: userChallengeData.challengeStats,
    daysActive: activitySummary.daysActive,
    earnedBadges: badgeState.earnedBadges,
    handleChallengeJoinHandled: challengeRefreshHandlers.handleChallengeJoinHandled,
    handleChallengeStatsChanged: challengeRefreshHandlers.handleChallengeStatsChanged,
    handleDeleteActivity: logState.handleDeleteActivity,
    handleLog: logState.handleLog,
    handleProgressShare: progressShareActions.handleProgressShare,
    handleShareTemplateSelect: progressShareActions.handleShareTemplateSelect,
    hasActivePro: activitySummary.hasActivePro,
    dismissLevelUp: levelUpState.dismissLevelUp,
    levelUp: levelUpState.levelUp,
    myChallenges: userChallengeData.myChallenges,
    myHistory: logState.myHistory,
    pendingJoinCode: pendingChallengeEntry.pendingJoinCode,
    pendingReferralUid: pendingChallengeEntry.pendingReferralUid,
    rankRules,
    savingShareTemplate: progressShareActions.savingShareTemplate,
    setBadgeQueue: badgeState.setBadgeQueue,
    setMyHistory: logState.setMyHistory,
    setUserProfile: userChallengeData.setUserProfile,
    shareTemplateId: activitySummary.shareTemplateId,
    streak: activitySummary.streak,
    totalPts: activitySummary.totalPts,
    triggerBadgeCheck: badgeState.triggerBadgeCheck,
    userProfile: userChallengeData.userProfile,
  };
}
