export const WORKOUT_TEMPLATES = [
  {
    id: "pull_day",
    name: "Pull Day",
    emoji: "🧲",
    focus: "Back, biceps, rear delts",
    minutes: 60,
    summary: "Back width, mid-back thickness, rear delts, and biceps in one editable pull session.",
    guidance: [
      "Perform this routine 1-2 times a week, resting 60-120 seconds between sets based on exercise intensity.",
      "Warm up with dynamic shoulder prep like Y-T-W holds or arm circles.",
      "When you hit the top of the rep range with clean form, add 1.25-2.5 kg next time.",
      "Control the lowering phase on pulldowns and rows, and squeeze shoulder blades together on rows.",
    ],
    exercises: [
      { name: "Pull-Ups or Lat Pulldowns", sets: 3, setRange: "3-4", reps: 10, repRange: "8-10", weightKg: 35, focus: "Back width (lats)", tip: "Choose assisted pull-ups or pulldowns if needed. Pull elbows down toward your ribs." },
      { name: "Barbell or Dumbbell Row", sets: 3, setRange: "3-4", reps: 12, repRange: "8-12", weightKg: 30, focus: "Mid-back thickness", tip: "Keep the torso controlled and squeeze shoulder blades together at the top." },
      { name: "Chest-Supported Row", sets: 3, setRange: "3", reps: 12, repRange: "10-12", weightKg: 30, focus: "Upper/mid-back isolation", tip: "Let the bench remove momentum so the upper back does the work." },
      { name: "Cable Face Pulls", sets: 3, setRange: "3", reps: 15, repRange: "12-15", weightKg: 15, focus: "Rear delts and posture", tip: "Aim toward your eyebrows and finish with hands beside your ears." },
      { name: "Incline or Cable Bicep Curls", sets: 3, setRange: "3", reps: 15, repRange: "10-15", weightKg: 10, focus: "Bicep peak and stretch", tip: "Use a full stretch and avoid swinging the elbows forward." },
      { name: "Hammer Curls", sets: 2, setRange: "2-3", reps: 15, repRange: "12-15", weightKg: 10, focus: "Forearms and outer bicep", tip: "Keep a neutral grip and control the lowering phase." },
    ],
  },
  {
    id: "push_day",
    name: "Push Day",
    emoji: "🚀",
    focus: "Chest, shoulders, triceps",
    minutes: 55,
    summary: "Pressing strength plus shoulder and triceps finishers.",
    guidance: [
      "Do presses first while fresh, then finish with isolation work.",
      "Keep reps clean and stop a set before form breaks.",
    ],
    exercises: [
      { name: "Bench Press", sets: 3, reps: 8, weightKg: 50, tip: "Keep feet planted and shoulder blades tucked." },
      { name: "Incline Dumbbell Press", sets: 3, reps: 10, weightKg: 18, tip: "Use a controlled angle and avoid bouncing." },
      { name: "Shoulder Press", sets: 3, reps: 8, weightKg: 25, tip: "Brace ribs down before pressing overhead." },
      { name: "Lateral Raise", sets: 3, reps: 12, weightKg: 7.5, tip: "Lead with elbows and keep traps relaxed." },
      { name: "Triceps Pushdown", sets: 3, reps: 12, weightKg: 20, tip: "Pin elbows by your sides." },
    ],
  },
  {
    id: "legs",
    name: "Legs",
    emoji: "🦵",
    focus: "Quads, glutes, hamstrings, calves",
    minutes: 60,
    summary: "Squat or press, hinge, extensions, curls, calves.",
    guidance: [
      "Leg press foot placement: lower/narrow biases quads, higher/wider biases glutes and hamstrings, middle is balanced.",
      "Use controlled depth, keep knees tracking with toes, and do not lock knees hard at the top.",
    ],
    exercises: [
      { name: "Leg Press", sets: 4, reps: 10, weightKg: 80, tip: "Low/narrow = quads. High/wide = glutes and hamstrings." },
      { name: "Romanian Deadlift", sets: 3, reps: 8, weightKg: 50, tip: "Hinge back with a flat back and soft knees." },
      { name: "Leg Extension", sets: 3, reps: 12, weightKg: 35, tip: "Pause at the top without swinging." },
      { name: "Hamstring Curl", sets: 3, reps: 12, weightKg: 30, tip: "Control both directions." },
      { name: "Calf Raise", sets: 3, reps: 15, weightKg: 40, tip: "Use a full stretch and full squeeze." },
    ],
  },
  {
    id: "chest",
    name: "Chest",
    emoji: "🛡️",
    focus: "Chest and pressing volume",
    minutes: 45,
    summary: "Flat press, incline press, fly, and push-up finisher.",
    guidance: [
      "Use one primary press, one angled press, then one stretch-focused movement.",
      "Keep shoulders packed and avoid turning every set into a max attempt.",
    ],
    exercises: [
      { name: "Bench Press", sets: 4, reps: 8, weightKg: 50, tip: "Keep bar path steady and feet planted." },
      { name: "Incline Dumbbell Press", sets: 3, reps: 10, weightKg: 18, tip: "Press slightly back toward your face." },
      { name: "Cable Fly", sets: 3, reps: 12, weightKg: 12.5, tip: "Hug around the chest, keep elbows soft." },
      { name: "Push-up", sets: 3, reps: 12, weightKg: 0, tip: "Stop before your hips sag." },
    ],
  },
  {
    id: "back",
    name: "Back",
    emoji: "🌊",
    focus: "Lats, mid-back, rear delts",
    minutes: 50,
    summary: "Vertical pull, horizontal row, single-arm row, rear delts.",
    guidance: [
      "Mix vertical and horizontal pulling for a more complete back session.",
      "Think elbows first and keep the neck relaxed.",
    ],
    exercises: [
      { name: "Lat Pulldown", sets: 3, reps: 10, weightKg: 35, tip: "Drive elbows down and keep ribs stacked." },
      { name: "Chest-supported Row", sets: 3, reps: 10, weightKg: 30, tip: "Let the bench remove momentum." },
      { name: "One-arm Dumbbell Row", sets: 3, reps: 10, weightKg: 18, tip: "Pull toward the hip pocket." },
      { name: "Face Pull", sets: 3, reps: 12, weightKg: 15, tip: "Finish with hands beside ears." },
    ],
  },
  {
    id: "arms",
    name: "Arms",
    emoji: "💥",
    focus: "Biceps and triceps",
    minutes: 40,
    summary: "Simple arm volume with curls and extensions.",
    guidance: [
      "Pair biceps and triceps to keep the session moving.",
      "Use strict reps; arm days are easy to cheat when tired.",
    ],
    exercises: [
      { name: "Dumbbell Curl", sets: 3, reps: 10, weightKg: 10, tip: "Keep elbows still." },
      { name: "Hammer Curl", sets: 3, reps: 10, weightKg: 10, tip: "Thumbs up grip for brachialis and forearms." },
      { name: "Cable Curl", sets: 3, reps: 12, weightKg: 15, tip: "Keep constant cable tension." },
      { name: "Triceps Pushdown", sets: 3, reps: 12, weightKg: 20, tip: "Lock out without leaning over the stack." },
      { name: "Overhead Triceps Extension", sets: 3, reps: 12, weightKg: 15, tip: "Feel the long head stretch behind you." },
    ],
  },
  {
    id: "full_body",
    name: "Full Body",
    emoji: "⚡",
    focus: "Squat, pull, press, hinge, core",
    minutes: 55,
    summary: "Balanced session when you want one efficient workout.",
    guidance: [
      "Keep the main lifts moderate so the whole body gets quality work.",
      "This is a strong default when you missed a split day.",
    ],
    exercises: [
      { name: "Goblet Squat", sets: 3, reps: 10, weightKg: 24, tip: "Stay tall and sit between the hips." },
      { name: "Seated Cable Row", sets: 3, reps: 10, weightKg: 35, tip: "Control the squeeze." },
      { name: "Dumbbell Bench Press", sets: 3, reps: 10, weightKg: 18, tip: "Press evenly with both sides." },
      { name: "Romanian Deadlift", sets: 3, reps: 8, weightKg: 45, tip: "Hips back, spine neutral." },
      { name: "Plank", sets: 3, reps: 30, weightKg: 0, tip: "Record seconds in reps for now." },
    ],
  },
];

export function buildExerciseDraftsFromTemplate(template) {
  return template.exercises.map(exercise => ({
    name: exercise.name,
    focus: exercise.focus || "",
    setRange: exercise.setRange || `${exercise.sets}`,
    repRange: exercise.repRange || `${exercise.reps}`,
    tip: exercise.tip || "",
    sets: Array.from({ length: exercise.sets }, () => ({
      reps: String(exercise.reps),
      weightKg: exercise.weightKg > 0 ? String(exercise.weightKg) : "",
    })),
  }));
}
