export function buildPreferenceInputs({
  computedData,
  myHistory,
  onHistoryUpdated,
  onProfileUpdated,
  screenState,
  user,
}) {
  const {
    avatarColor,
    avatarEmoji,
    proActive,
    yesterdayKey,
    yesterdayRecovered,
  } = computedData;

  const {
    goalActiveDays,
    goalPoints,
    goalStreak,
    displayNameDraft,
    profile,
    selectedFrameId,
    setAppearanceError,
    setCosmeticsMessage,
    setDisplayNameDraft,
    setDisplayNameMessage,
    setGoalsMessage,
    setIsSavingAppearance,
    setIsSavingCosmetics,
    setIsSavingDisplayName,
    setIsSavingGoals,
    setIsSavingRecovery,
    setProfile,
    setRecoveryMessage,
  } = screenState;

  return {
    avatarColor,
    avatarEmoji,
    goalActiveDays,
    goalPoints,
    goalStreak,
    displayNameDraft,
    myHistory,
    profile,
    proActive,
    selectedFrameId,
    setAppearanceError,
    setCosmeticsMessage,
    setDisplayNameDraft,
    setDisplayNameMessage,
    setGoalsMessage,
    setIsSavingAppearance,
    setIsSavingCosmetics,
    setIsSavingDisplayName,
    setIsSavingGoals,
    setIsSavingRecovery,
    setProfile,
    setRecoveryMessage,
    user,
    yesterdayKey,
    yesterdayRecovered,
    onHistoryUpdated,
    onProfileUpdated,
  };
}
