export function buildPrelaunchProps(model) {
  const {
    campaignPerformanceSummary,
    communityAmbassadorCopy,
    communityEventInterestCopy,
    communityEventInterestMessage,
    communityEventInterestSummary,
    creatorEnabled,
    creatorRevenueShareTotal,
    customerValueChecklistCopy,
    daysActive,
    founderMemberOfferCopy,
    handleCommunityEventInterestToggle,
    isAdmin,
    isSavingCommunityEventInterest,
    monetizationLaunchCopy,
    monetizationSignalTotal,
    partnerDemandTotal,
    pricingTestKitCopy,
    proTrialDemandTotal,
    recommendedRevenuePath,
    referralJoins,
    revenuePathwayPlannerCopy,
    revenuePathways,
    selectedCommunityEventInterestIds,
    storePackCount,
    storeSubscriptionCount,
  } = model;

  return {
    isAdmin,
    creatorEnabled,
    monetizationSignalTotal,
    proTrialDemandTotal,
    creatorRevenueShareTotal,
    partnerDemandTotal,
    monetizationLaunchCopy,
    revenuePathways,
    recommendedRevenuePath,
    revenuePathwayPlannerCopy,
    storeSubscriptionCount,
    storePackCount,
    pricingTestKitCopy,
    campaignPerformanceSummary,
    referralJoins,
    founderMemberOfferCopy,
    communityAmbassadorCopy,
    communityEventInterestCopy,
    selectedCommunityEventInterestIds,
    communityEventInterestSummary,
    isSavingCommunityEventInterest,
    onCommunityEventInterestToggle: handleCommunityEventInterestToggle,
    communityEventInterestMessage,
    daysActive,
    customerValueChecklistCopy,
  };
}
