export function buildStoreCommerceInputs({ computedData, screenState, user }) {
  const {
    activeChallengePackCount,
    challengePackProducts,
    isAdmin,
    proActive,
  } = computedData;

  const {
    entitlementRecoveryReviewNotes,
    approvedSupportRefundReadinessReviews,
    isRequestingEntitlementRecovery,
    isSubmittingSupportRefundReadinessReview,
    profile,
    recordingStoreTestEvidenceId,
    reviewingEntitlementRecoveryRequestId,
    reviewingSupportRefundReadinessReviewId,
    reviewingStoreTestEvidenceId,
    setApprovedSupportRefundReadinessReviews,
    setCheckoutMessage,
    setCheckoutProductId,
    setEntitlementRecoveryMessage,
    setEntitlementRecoveryReviewQueue,
    setIsCheckingValidationReadiness,
    setIsRequestingEntitlementRecovery,
    setIsSubmittingSupportRefundReadinessReview,
    setRecordingStoreTestEvidenceId,
    setReviewingEntitlementRecoveryRequestId,
    setReviewingSupportRefundReadinessReviewId,
    setReviewingStoreTestEvidenceId,
    setStoreTestEvidenceLog,
    setStoreTestEvidenceMessage,
    setSupportRefundReadinessReviewMessage,
    setSupportRefundReadinessReviewQueue,
    setValidationReadinessMessage,
    storeTestEvidenceReviewNotes,
    supportRefundReadinessReviewNotes,
  } = screenState;

  return {
    activeChallengePackCount,
    approvedSupportRefundReadinessReviews,
    challengePackProducts,
    entitlementRecoveryReviewNotes,
    isAdmin,
    isRequestingEntitlementRecovery,
    isSubmittingSupportRefundReadinessReview,
    profile,
    proActive,
    recordingStoreTestEvidenceId,
    reviewingEntitlementRecoveryRequestId,
    reviewingSupportRefundReadinessReviewId,
    reviewingStoreTestEvidenceId,
    setApprovedSupportRefundReadinessReviews,
    setCheckoutMessage,
    setCheckoutProductId,
    setEntitlementRecoveryMessage,
    setEntitlementRecoveryReviewQueue,
    setIsCheckingValidationReadiness,
    setIsRequestingEntitlementRecovery,
    setIsSubmittingSupportRefundReadinessReview,
    setRecordingStoreTestEvidenceId,
    setReviewingEntitlementRecoveryRequestId,
    setReviewingSupportRefundReadinessReviewId,
    setReviewingStoreTestEvidenceId,
    setStoreTestEvidenceLog,
    setStoreTestEvidenceMessage,
    setSupportRefundReadinessReviewMessage,
    setSupportRefundReadinessReviewQueue,
    setValidationReadinessMessage,
    storeTestEvidenceReviewNotes,
    supportRefundReadinessReviewNotes,
    user,
  };
}
