export function buildCommunityFeatureReferralScreenInputs(screenState) {
  const {
    featureCategory,
    featureConsent,
    featureMediaData,
    featureReviewNotes,
    featureStory,
    isClaimingReferralReward,
    referralRewardReviewNotes,
    reviewingReferralRewardClaimId,
    setFeatureConsent,
    setFeatureMediaData,
    setFeatureMessage,
    setFeatureReviewQueue,
    setFeatureStory,
    setFeatureSubmissions,
    setIsClaimingReferralReward,
    setIsSubmittingFeature,
    setReferralRewardClaimMessage,
    setReferralRewardReviewQueue,
    setReviewingReferralRewardClaimId,
  } = screenState;

  return {
    featureCategory,
    featureConsent,
    featureMediaData,
    featureReviewNotes,
    featureStory,
    isClaimingReferralReward,
    referralRewardReviewNotes,
    reviewingReferralRewardClaimId,
    setFeatureConsent,
    setFeatureMediaData,
    setFeatureMessage,
    setFeatureReviewQueue,
    setFeatureStory,
    setFeatureSubmissions,
    setIsClaimingReferralReward,
    setIsSubmittingFeature,
    setReferralRewardClaimMessage,
    setReferralRewardReviewQueue,
    setReviewingReferralRewardClaimId,
  };
}
