export function buildCommunitySupportReviewScreenInputs(screenState) {
  const {
    accountDeletionReviewNotes,
    isRequestingDeletion,
    isSubmittingSupport,
    profile,
    reviewingAccountDeletionRequestId,
    reviewingSupportRequestId,
    setAccountDeletionReviewQueue,
    setDeletionRequestMessage,
    setIsRequestingDeletion,
    setIsSubmittingSupport,
    setProfile,
    setReviewMessage,
    setReviewingAccountDeletionRequestId,
    setReviewingSupportRequestId,
    setSupportMessage,
    setSupportReviewQueue,
    setSupportStatusMessage,
    supportCategory,
    supportMessage,
    supportReviewNotes,
  } = screenState;

  return {
    accountDeletionReviewNotes,
    isRequestingDeletion,
    isSubmittingSupport,
    profile,
    reviewingAccountDeletionRequestId,
    reviewingSupportRequestId,
    setAccountDeletionReviewQueue,
    setDeletionRequestMessage,
    setIsRequestingDeletion,
    setIsSubmittingSupport,
    setProfile,
    setReviewMessage,
    setReviewingAccountDeletionRequestId,
    setReviewingSupportRequestId,
    setSupportMessage,
    setSupportReviewQueue,
    setSupportStatusMessage,
    supportCategory,
    supportMessage,
    supportReviewNotes,
  };
}
