export function buildCreatorHostingReadinessCopyKits({
  candidateChallengeLine,
  creatorBetaInterestLine,
  creatorFocusLine,
  hostedChallengesLine,
  memberReachLine,
  revenueReadyLine,
}) {
  const creatorChallengeTemplateDraftCopy = [
    'Rise With The Tribe Creator Challenge Template Draft Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    candidateChallengeLine,
    '',
    'Creator template draft checklist:',
    '- Define the challenge promise, audience, duration, rules, daily prompts, and proof habit before building a new template',
    '- Keep the template reusable for free hosted challenges first, then review paid-hosting readiness separately',
    '- Use first-party app joins, logs, referrals, and Feature Me submissions to learn whether the format works',
    '- Include beginner-safe instructions, no medical claims, no guaranteed outcomes, and no pressure language',
    '- Route deeper paid-hosting interest through creator hosting review before discussing creator terms or payouts',
    '',
    'This is a creator challenge template draft kit only. Do not create template records, create contracts, collect payments, create purchases, write entitlements, start revenue-share, create payouts, create partner links, add tracking pixels, export private member activity, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorBrandedPagePreviewCopy = [
    'Rise With The Tribe Creator Branded Page Preview Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    candidateChallengeLine,
    '',
    'Branded challenge page checklist:',
    '- Confirm the Coach Host block shows the creator specialty, bio, and CTA link accurately',
    '- Keep the challenge name, tagline, rules, and daily prompts truthful and beginner-safe',
    '- Use the app invite link for joins so member reach, referrals, and logs stay first-party',
    '- Ask members to submit Feature Me wins only through the app so consent and review status are preserved',
    '- Review the page before promotion for no medical claims, no guaranteed outcomes, and no paid-hosting promises',
    '',
    'This is a creator branded page preview kit only. Do not create branded page records, create contracts, collect payments, create purchases, write entitlements, start revenue-share, add tracking pixels, export private member activity, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPrivateInviteCopy = [
    'Rise With The Tribe Private Creator Invite Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    candidateChallengeLine,
    '',
    'Invite-only launch checklist:',
    '- Create a private Pro Coach Mode challenge and use the app invite link only',
    '- Send the link to a small accountability group before opening broader public promotion',
    '- Ask invitees to join, log their first session, and tag @risewiththetribe only if they choose to share',
    '- Review success from first-party challenge joins, saved logs, referrals, and consent-cleared Feature Me submissions',
    '- Keep any paid-hosting or revenue-share conversation behind creator hosting review',
    '',
    'This is a private creator invite kit only. Do not auto-message, scrape DMs, store inbound replies, count link opens, export private member activity, create contracts, create payouts, start revenue-share, collect payments, create purchases, write entitlements, grant paid access, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure invitees.',
  ].join('\n');
  const creatorHostingOfferCopy = [
    'Rise With The Tribe Creator Hosting Offer Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Draft offer angle: run a structured hosted challenge with clear daily accountability, community proof, and a manual launch plan.',
    'Before taking payments: confirm paid-hosting policy, creator terms, payout operations, store product validation, and Firestore entitlement QA.',
    'This is a planning brief only; it does not create a contract, payout, purchase, entitlement, or paid-access claim.',
  ].join('\n');
  const creatorTermsReadinessCopy = [
    'Rise With The Tribe Creator Terms Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    '',
    'Terms checklist:',
    '- Creator responsibilities: truthful challenge descriptions, safe community conduct, no medical claims, and no guaranteed fitness outcomes',
    '- Content moderation: hosted challenges and feature submissions remain subject to manual review and removal',
    '- Payout readiness: payout provider, tax collection, identity verification, refund handling, and support escalation must be approved before any creator revenue-share',
    '- Marketplace alignment: paid access must use configured App Store / Play products, receipt validation, restore flow, and entitlement QA',
    '- Support handoff: users need clear support, privacy, terms, and data deletion resources before hosted paid access is promoted',
    '',
    'This is a creator terms readiness brief only. Do not create contracts, collect payout details, collect tax details, start revenue-share, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise outcomes, imply medical results, or claim paid creator hosting is live.',
  ].join('\n');
  const creatorPayoutReadinessCopy = [
    'Rise With The Tribe Creator Payout Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Payout readiness checklist:',
    '- Select and approve a payout provider before collecting payout details',
    '- Define creator eligibility, revenue-share terms, refund responsibility, tax collection, and identity verification',
    '- Confirm App Store / Play paid-access flow, receipt validation, restore, and entitlement QA before any creator payout promise',
    '- Keep hosted challenge support, moderation, refunds, account deletion, and safety escalation owned by the app team',
    '- Review creator content for truthful claims, no medical outcomes, and no guaranteed fitness results',
    '',
    'This is a creator payout readiness brief only. Do not create payouts, collect payout details, collect tax details, create contracts, start revenue-share, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise outcomes, imply medical results, or claim paid creator hosting is live.',
  ].join('\n');

  return {
    creatorBrandedPagePreviewCopy,
    creatorChallengeTemplateDraftCopy,
    creatorHostingOfferCopy,
    creatorPrivateInviteCopy,
    creatorPayoutReadinessCopy,
    creatorTermsReadinessCopy,
  };
}
