export function buildCreatorHostingReadinessCopyKits({
  candidateChallengeLine,
  creatorBetaInterestLine,
  creatorBioLine = 'Creator bio: add a short proof-first bio before sharing',
  creatorCtaLine = 'Creator CTA: add an app-first CTA link before sharing',
  creatorFocusLine,
  hostedChallengesLine,
  memberReachLine,
  revenueReadyLine,
}) {
  const creatorProfileCompletionCopy = [
    'Rise With The Tribe Creator Profile Completion Kit:',
    '',
    creatorFocusLine,
    creatorBioLine,
    creatorCtaLine,
    hostedChallengesLine,
    memberReachLine,
    candidateChallengeLine,
    '',
    'Profile completion checklist:',
    '- Keep the specialty specific, truthful, and beginner-safe',
    '- Keep the bio focused on accountability, challenge format, and community proof',
    '- Use an app-first CTA link or hosted challenge invite path instead of off-platform payment language',
    '- Confirm the Coach Host block, launch copy, and branded page preview match the saved profile',
    '- Route paid-hosting interest through creator hosting review before discussing terms, payouts, or revenue-share',
    '',
    'This is a creator profile completion kit only. Do not create contracts, collect payments, create purchases, write entitlements, start revenue-share, create payouts, collect payout details, collect tax details, create partner links, add tracking pixels, export private member activity, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorChallengeTemplateDraftCopy = [
    'Rise With The Tribe Creator Challenge Template Draft Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    candidateChallengeLine,
    '',
    'Creator template draft checklist:',
    '- Define the challenge promise, audience, duration, rules, daily prompts, and proof habit before building a new template',
    '- Keep the template reusable for free hosted challenges first, then review paid-hosting readiness separately',
    '- Use first-party app joins, logs, referrals, and Feature Me submissions to learn whether the format works',
    '- Include beginner-safe instructions, no medical claims, no guaranteed outcomes, and no pressure language',
    '- Route deeper paid-hosting interest through creator hosting review before discussing creator terms or payouts',
    '',
    'This is a creator challenge template draft kit only. Do not create template records, create contracts, collect payments, create purchases, write entitlements, start revenue-share, create payouts, create partner links, add tracking pixels, export private member activity, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorLeaderboardPreviewCopy = [
    'Rise With The Tribe Creator Leaderboard Preview Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    candidateChallengeLine,
    '',
    'Leaderboard preview checklist:',
    '- Rank only first-party hosted challenge movement: active members, logged sessions, challenge points, referrals, and consent-cleared Feature Me submissions',
    '- Keep the preview aggregate-first until creator moderation, privacy, support handoff, and claim rules are reviewed',
    '- Use the leaderboard to spot community momentum, not to promise earnings, outcomes, or paid hosting access',
    '- Route member disputes, privacy concerns, and safety flags through support review before any public creator leaderboard launch',
    '- Keep paid-hosting and revenue-share decisions behind creator hosting review, marketplace validation, payout operations, and entitlement QA',
    '',
    'This is a creator leaderboard preview kit only. Do not create leaderboard records, expose private member activity, export per-user logs, create contracts, collect payments, create purchases, write entitlements, start revenue-share, create payouts, create partner links, add tracking pixels, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorBrandedPagePreviewCopy = [
    'Rise With The Tribe Creator Branded Page Preview Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    candidateChallengeLine,
    '',
    'Branded challenge page checklist:',
    '- Confirm the Coach Host block shows the creator specialty, bio, and CTA link accurately',
    '- Keep the challenge name, tagline, rules, and daily prompts truthful and beginner-safe',
    '- Use the app invite link for joins so member reach, referrals, and logs stay first-party',
    '- Ask members to submit Feature Me wins only through the app so consent and review status are preserved',
    '- Review the page before promotion for no medical claims, no guaranteed outcomes, and no paid-hosting promises',
    '',
    'This is a creator branded page preview kit only. Do not create branded page records, create contracts, collect payments, create purchases, write entitlements, start revenue-share, add tracking pixels, export private member activity, scrape DMs, store inbound replies, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPrivateInviteCopy = [
    'Rise With The Tribe Private Creator Invite Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    candidateChallengeLine,
    '',
    'Invite-only launch checklist:',
    '- Create a private Pro Coach Mode challenge and use the app invite link only',
    '- Send the link to a small accountability group before opening broader public promotion',
    '- Ask invitees to join, log their first session, and tag @risewiththetribe only if they choose to share',
    '- Review success from first-party challenge joins, saved logs, referrals, and consent-cleared Feature Me submissions',
    '- Keep any paid-hosting or revenue-share conversation behind creator hosting review',
    '',
    'This is a private creator invite kit only. Do not auto-message, scrape DMs, store inbound replies, count link opens, export private member activity, create contracts, create payouts, start revenue-share, collect payments, create purchases, write entitlements, grant paid access, promise earnings, imply paid hosting is live, promise outcomes, imply medical results, or pressure invitees.',
  ].join('\n');
  const creatorHostingOfferCopy = [
    'Rise With The Tribe Creator Hosting Offer Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Draft offer angle: run a structured hosted challenge with clear daily accountability, community proof, and a manual launch plan.',
    'Before taking payments: confirm paid-hosting policy, creator terms, payout operations, store product validation, and Firestore entitlement QA.',
    'This is a planning brief only; it does not create a contract, payout, purchase, entitlement, or paid-access claim.',
  ].join('\n');
  const creatorTermsReadinessCopy = [
    'Rise With The Tribe Creator Terms Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    '',
    'Terms checklist:',
    '- Creator responsibilities: truthful challenge descriptions, safe community conduct, no medical claims, and no guaranteed fitness outcomes',
    '- Content moderation: hosted challenges and feature submissions remain subject to manual review and removal',
    '- Payout readiness: payout provider, tax collection, identity verification, refund handling, and support escalation must be approved before any creator revenue-share',
    '- Marketplace alignment: paid access must use configured App Store / Play products, receipt validation, restore flow, and entitlement QA',
    '- Support handoff: users need clear support, privacy, terms, and data deletion resources before hosted paid access is promoted',
    '',
    'This is a creator terms readiness brief only. Do not create contracts, collect payout details, collect tax details, start revenue-share, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise outcomes, imply medical results, or claim paid creator hosting is live.',
  ].join('\n');
  const creatorAgreementPrepCopy = [
    'Rise With The Tribe Creator Agreement Prep Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Agreement prep checklist:',
    '- Confirm the creator identity, support owner, moderation owner, content boundaries, and takedown process before drafting terms',
    '- Map marketplace alignment for App Store / Play paid access, receipt validation, restore flow, refunds, and entitlement QA',
    '- Keep payout provider, tax collection, identity verification, and revenue-share language in reviewed legal and finance workflows',
    '- Record creator claim rules: no medical claims, no guaranteed outcomes, no earnings promises, and no pressure language',
    '- Keep the draft app-first and support-safe until paid-hosting policy, creator terms, payout operations, and store validation are approved',
    '',
    'This is a creator agreement prep kit only. Do not create contracts, collect signatures, collect payout details, collect tax details, start revenue-share, create payouts, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, add tracking pixels, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorSupportHandoffCopy = [
    'Rise With The Tribe Creator Support Handoff Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Support handoff checklist:',
    '- Name the app support owner, creator support owner, moderation owner, and escalation path before any paid hosting review',
    '- Route purchase, refund, cancellation, restore, and entitlement questions to marketplace/backend support instead of creator DMs',
    '- Keep community safety, takedowns, account deletion, privacy, and data requests owned by the app support path',
    '- Give creators approved reply boundaries for medical claims, outcome claims, harassment, refunds, privacy, and paid-access questions',
    '- Keep support notes aggregate and first-party; do not export private member logs or scrape off-platform messages',
    '',
    'This is a creator support handoff kit only. Do not process refunds, cancel subscriptions, create purchases, write entitlements, collect payments, collect payout details, collect tax details, create contracts, start revenue-share, create payouts, bypass marketplace policy, expose private member data, scrape DMs, store inbound DMs, promise earnings, imply paid creator hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPaidHostingPolicyCopy = [
    'Rise With The Tribe Creator Paid Hosting Policy Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Paid-hosting policy checklist:',
    '- Define which hosted challenge formats are eligible before any paid hosting review',
    '- Confirm creator conduct, moderation, safety, support owner, takedown, refund, restore, and account deletion boundaries',
    '- Require marketplace alignment: configured App Store / Play products, receipt validation, restore flow, entitlement QA, and support escalation',
    '- Require creator agreement, payout provider, tax workflow, identity verification, and claim review before revenue-share language appears',
    '- Keep member-facing copy app-first, beginner-safe, no medical claims, no guaranteed outcomes, no earnings promises, and no pressure',
    '',
    'This is a creator paid-hosting policy kit only. Do not approve paid hosting, create contracts, collect signatures, collect payout details, collect tax details, create payouts, start revenue-share, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, add tracking pixels, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPayoutReadinessCopy = [
    'Rise With The Tribe Creator Payout Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Payout readiness checklist:',
    '- Select and approve a payout provider before collecting payout details',
    '- Define creator eligibility, revenue-share terms, refund responsibility, tax collection, and identity verification',
    '- Confirm App Store / Play paid-access flow, receipt validation, restore, and entitlement QA before any creator payout promise',
    '- Keep hosted challenge support, moderation, refunds, account deletion, and safety escalation owned by the app team',
    '- Review creator content for truthful claims, no medical outcomes, and no guaranteed fitness results',
    '',
    'This is a creator payout readiness brief only. Do not create payouts, collect payout details, collect tax details, create contracts, start revenue-share, process payments, create purchases, write entitlements, process refunds, bypass marketplace policy, promise outcomes, imply medical results, or claim paid creator hosting is live.',
  ].join('\n');
  const creatorPayoutProviderSetupCopy = [
    'Rise With The Tribe Creator Payout Provider Setup Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Provider setup checklist:',
    '- Compare payout providers for creator eligibility, country coverage, fees, tax form support, identity verification, payout timing, dispute handling, and export controls before choosing one',
    '- Define what the app team will configure outside profile UI: provider account, legal entity, payout terms, tax workflow, support owner, refund handoff, and finance reconciliation',
    '- Confirm marketplace boundaries: App Store / Play purchases, receipt validation, restore flow, entitlement QA, and refund escalation stay separate from creator payouts',
    '- Prepare creator-facing setup copy that explains payout onboarding is not live until legal, finance, support, marketplace, and policy review approve it',
    '- Keep all payout, bank, tax, government ID, and provider credential collection out of client code, screenshots, public docs, and Firestore profile records',
    '',
    'This is a creator payout provider setup kit only. Do not create payout accounts, collect bank details, collect payout details, collect tax details, collect government IDs, store provider credentials, store tax forms, create contracts, collect signatures, start revenue-share, create payouts, process payments, process refunds, create purchases, write entitlements, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, add tracking pixels, promise outcomes, imply medical results, or pressure creators.',
  ].join('\n');
  const creatorPayoutOperationsDryRunCopy = [
    'Rise With The Tribe Creator Payout Operations Dry-Run Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Operations dry-run checklist:',
    '- Walk through a zero-money payout rehearsal with mock creator eligibility, mock payout event, mock refund adjustment, and mock finance reconciliation notes',
    '- Confirm legal, finance, support, moderation, marketplace, and entitlement owners know where handoffs happen before real payout onboarding',
    '- Compare the dry-run outcome against provider setup, creator terms, payout readiness, refund paths, support scripts, and store-test evidence',
    '- Keep mock payout amounts, provider names, tax form notes, bank details, government IDs, and credentials out of client code, screenshots, public docs, and Firestore profile records',
    '- Stop the dry run if any step requires live provider access, real creator tax data, real payment movement, payout creation, purchase creation, entitlement writes, or marketplace bypass',
    '',
    'This is a creator payout operations dry-run kit only. Do not create payout accounts, access payout providers, collect bank details, collect payout details, collect tax details, collect government IDs, store provider credentials, store tax forms, create contracts, collect signatures, start revenue-share, create payouts, move money, process payments, process refunds, create purchases, write entitlements, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, add tracking pixels, promise outcomes, imply medical results, or pressure creators.',
  ].join('\n');
  const creatorPayoutReconciliationCopy = [
    'Rise With The Tribe Creator Payout Reconciliation Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Payout reconciliation checklist:',
    '- Match mock payout events against store-test evidence, refund adjustments, entitlement QA notes, creator eligibility, and finance reconciliation notes before any real payout run',
    '- Confirm finance, support, marketplace, legal, moderation, and entitlement owners can explain every adjustment without using private member logs or off-platform messages',
    '- Separate marketplace revenue evidence from creator payout planning: purchases, restores, refunds, entitlement writes, provider records, tax data, and payout movement must each stay in their approved systems',
    '- Prepare a creator-facing reconciliation summary that says payout reconciliation is not live until legal, finance, marketplace, support, and provider operations approve it',
    '- Escalate mismatched evidence, refund disputes, entitlement gaps, tax workflow gaps, or provider setup gaps back to hold-plan review instead of promising earnings',
    '',
    'This is a creator payout reconciliation kit only. Do not create payout accounts, access payout providers, collect bank details, collect payout details, collect tax details, collect government IDs, store provider credentials, store tax forms, create contracts, collect signatures, start revenue-share, create payouts, move money, process payments, process refunds, create purchases, write entitlements, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, expose private member logs, scrape or store messages, add tracking pixels, promise outcomes, imply medical results, or pressure creators.',
  ].join('\n');
  const creatorTaxWorkflowReadinessCopy = [
    'Rise With The Tribe Creator Tax Workflow Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Tax workflow readiness checklist:',
    '- Map the future tax workflow owner, payout-provider tax form path, creator eligibility rules, country coverage, withholding review, and finance export process before any creator onboarding',
    '- Confirm tax form collection, government ID checks, legal entity review, and withholding decisions happen only inside approved provider, legal, finance, or tax-advisor workflows',
    '- Prepare creator-facing setup copy that explains tax onboarding is not live and no tax form, bank, payout, or government ID details should be sent through profile, DMs, screenshots, support tickets, or Firestore profile records',
    '- Cross-check tax workflow readiness against creator terms, payout provider setup, payout dry run, reconciliation, refund responsibility, support escalation, marketplace policy, and entitlement QA',
    '- Route tax questions to reviewed legal/finance support language instead of giving tax advice, promising payout eligibility, or implying revenue-share is approved',
    '',
    'This is a creator tax workflow readiness kit only. Do not collect tax details, collect tax forms, collect government IDs, collect bank details, collect payout details, verify identities, create payout accounts, access payout providers, store provider credentials, store tax forms, create contracts, collect signatures, start revenue-share, create payouts, move money, process payments, process refunds, create purchases, write entitlements, give tax advice, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, expose private member logs, scrape or store messages, add tracking pixels, promise outcomes, imply medical results, or pressure creators.',
  ].join('\n');
  const creatorPayoutExceptionResponseCopy = [
    'Rise With The Tribe Creator Payout Exception Response Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Payout exception response checklist:',
    '- Classify the exception before replying: mismatched store-test evidence, refund dispute, entitlement gap, tax workflow gap, provider setup gap, support escalation, or creator eligibility question',
    '- Assign an owner for finance, marketplace, support, legal, tax, provider setup, and entitlement QA before promising any next step',
    '- Compare only first-party app records, approved store-test notes, aggregate finance notes, and reviewed support language; keep private member logs and off-platform messages out of the response',
    '- Send creators a manual status update that payout exception review is not live payout processing and no earnings, eligibility, tax, refund, or revenue-share decision is approved yet',
    '- Route unresolved exceptions back to hold-plan review, tax workflow readiness, provider setup, reconciliation, or marketplace support instead of improvising payout or tax answers',
    '',
    'This is a creator payout exception response kit only. Do not resolve payout disputes, process refunds, collect tax details, collect tax forms, collect government IDs, collect bank details, collect payout details, verify identities, create payout accounts, access payout providers, store provider credentials, store tax forms, create contracts, collect signatures, start revenue-share, create payouts, move money, process payments, create purchases, write entitlements, give tax advice, bypass marketplace policy, promise earnings, imply paid creator hosting is live, export private member activity, expose private member logs, scrape or store messages, add tracking pixels, promise outcomes, imply medical results, or pressure creators.',
  ].join('\n');
  const creatorIdentityVerificationPrepCopy = [
    'Rise With The Tribe Creator Identity Verification Prep Kit:',
    '',
    creatorFocusLine,
    creatorBioLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Identity verification prep checklist:',
    '- Confirm the saved creator name, specialty, bio, and CTA describe the same person or organization before any paid-hosting review',
    '- Prepare a manual review path for identity, content ownership, brand permission, support owner, and moderation owner',
    '- Keep payout, tax, legal, and identity-provider workflows outside profile UI until approved operations exist',
    '- Review creator claims for no medical outcomes, no guaranteed fitness results, no earnings promises, and no pressure language',
    '- Route identity concerns, impersonation concerns, and brand-permission questions through support review before creator terms or revenue-share',
    '',
    'This is a creator identity verification prep kit only. Do not verify identities from client code, collect government IDs, collect payout details, collect tax details, create contracts, collect signatures, start revenue-share, create payouts, process payments, create purchases, write entitlements, bypass marketplace policy, expose private member activity, add tracking pixels, promise earnings, imply paid creator hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorModerationReadinessCopy = [
    'Rise With The Tribe Creator Moderation Readiness Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Moderation readiness checklist:',
    '- Define creator conduct rules, member safety rules, comment boundaries, removal criteria, and escalation owners before paid-hosting review',
    '- Confirm takedown, harassment, privacy, account deletion, refund/restore, and support handoff paths before revenue-share is discussed',
    '- Review hosted challenge copy, prompts, replies, and Feature Me requests for no medical claims, no guaranteed outcomes, no earnings promises, and no pressure language',
    '- Keep creator moderation notes aggregate and first-party; route private member concerns through support review instead of creator DMs',
    '- Pause paid-hosting review when identity, brand permission, support owner, or claim-safety issues need manual review',
    '',
    'This is a creator moderation readiness kit only. Do not auto-moderate, auto-message, scrape DMs, store inbound DMs, export private member activity, expose private member data, create contracts, collect signatures, collect payout details, collect tax details, start revenue-share, create payouts, process payments, create purchases, write entitlements, bypass marketplace policy, promise earnings, imply paid creator hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPaidHostingLaunchGateCopy = [
    'Rise With The Tribe Creator Paid Hosting Launch Gate Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Launch gate checks:',
    '- Creator profile, branded page preview, and challenge template draft are reviewed for truthful, beginner-safe copy',
    '- Creator agreement prep, identity/brand review, moderation readiness, and support handoff have named owners',
    '- Payout provider, tax workflow, refund responsibility, and revenue-share terms are approved outside profile UI',
    '- App Store / Play products, receipt validation, restore flow, entitlement QA, and store-test evidence are reviewed before paid access is promoted',
    '- Member-facing launch copy has no medical claims, guaranteed outcomes, earnings promises, pressure language, or off-store payment language',
    '',
    'Gate result: keep paid creator hosting in review until every check above has reviewed evidence.',
    '',
    'This is a creator paid hosting launch gate kit only. Do not approve paid hosting, create contracts, collect signatures, collect payout details, collect tax details, start revenue-share, create payouts, process payments, create purchases, write entitlements, grant paid access, bypass marketplace policy, submit store review, promise earnings, imply paid creator hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');
  const creatorPaidHostingHoldPlanCopy = [
    'Rise With The Tribe Creator Paid Hosting Hold Plan Kit:',
    '',
    creatorFocusLine,
    hostedChallengesLine,
    memberReachLine,
    revenueReadyLine,
    creatorBetaInterestLine,
    candidateChallengeLine,
    '',
    'Hold plan triggers:',
    '- Launch gate evidence is incomplete, stale, disputed, or missing owner sign-off',
    '- Store products, receipt validation, restore flow, entitlement QA, or store-test evidence fail review',
    '- Creator agreement, identity/brand review, payout/tax workflow, moderation, support, or marketplace checks need rework',
    '- Member-facing copy risks medical claims, guaranteed outcomes, earnings promises, off-store payment language, or pressure',
    '',
    'Hold response:',
    '- Keep the creator in free hosted challenge mode while review items are repaired',
    '- Send creators a clear manual update that paid hosting is still in review and no payout, revenue-share, or paid access is live',
    '- Route member questions to the free challenge loop, support, restore, or marketplace policy paths until evidence is approved',
    '- Re-run the launch gate only after owners attach updated evidence for every failed check',
    '',
    'This is a creator paid hosting hold plan kit only. Do not approve paid hosting, create contracts, collect signatures, collect payout details, collect tax details, start revenue-share, create payouts, process payments, create purchases, write entitlements, grant paid access, bypass marketplace policy, submit store review, promise earnings, imply paid creator hosting is live, promise outcomes, imply medical results, or pressure creators or members.',
  ].join('\n');

  return {
    creatorBrandedPagePreviewCopy,
    creatorChallengeTemplateDraftCopy,
    creatorLeaderboardPreviewCopy,
    creatorProfileCompletionCopy,
    creatorHostingOfferCopy,
    creatorPrivateInviteCopy,
    creatorAgreementPrepCopy,
    creatorSupportHandoffCopy,
    creatorPaidHostingPolicyCopy,
    creatorIdentityVerificationPrepCopy,
    creatorModerationReadinessCopy,
    creatorPaidHostingLaunchGateCopy,
    creatorPaidHostingHoldPlanCopy,
    creatorPayoutOperationsDryRunCopy,
    creatorPayoutReconciliationCopy,
    creatorTaxWorkflowReadinessCopy,
    creatorPayoutExceptionResponseCopy,
    creatorPayoutProviderSetupCopy,
    creatorPayoutReadinessCopy,
    creatorTermsReadinessCopy,
  };
}
