export function buildCreatorCoachAdminSectionProps({
  creatorAnalytics,
  creatorHostingApplicationReviewNotes,
  creatorHostingApplicationReviewQueue,
  creatorHostingDecisionReplyCopy,
  creatorTemplateDraftReviewNotes,
  creatorTemplateDraftReviewQueue,
  creatorRevenueSharePitchCopy,
  creatorRevenueShareSummary,
  creatorRevenueShareTotal,
  handleCreatorHostingApplicationReview,
  handleCreatorTemplateDraftReview,
  publishedCreatorChallengeTemplates,
  reviewingCreatorHostingApplicationId,
  reviewingCreatorTemplateDraftId,
  setCreatorHostingApplicationReviewNotes,
  setCreatorTemplateDraftReviewNotes,
}) {
  return {
    creatorAnalytics,
    creatorHostingApplicationReviewNotes,
    creatorHostingApplicationReviewQueue,
    creatorHostingDecisionReplyCopy,
    creatorTemplateDraftReviewNotes,
    creatorTemplateDraftReviewQueue,
    creatorRevenueSharePitchCopy,
    creatorRevenueShareSummary,
    creatorRevenueShareTotal,
    handleCreatorHostingApplicationReview,
    handleCreatorTemplateDraftReview,
    publishedCreatorChallengeTemplates,
    reviewingCreatorHostingApplicationId,
    reviewingCreatorTemplateDraftId,
    setCreatorHostingApplicationReviewNotes,
    setCreatorTemplateDraftReviewNotes,
  };
}
