export function buildCreatorPlanningCopyKitConfigs({
  creatorAnalytics,
  creatorBrandedPagePreviewCopy,
  creatorChallengeTemplateDraftCopy,
  creatorProfileCompletionCopy,
  creatorEnabled,
  creatorHostingObjectionReplyCopy,
  creatorHostingOfferCopy,
  creatorIdentityVerificationPrepCopy,
  creatorLeaderboardPreviewCopy,
  creatorModerationReadinessCopy,
  creatorPaidHostingLaunchGateCopy,
  creatorPaidHostingHoldPlanCopy,
  creatorLaunchChallenge,
  creatorLaunchCopy,
  creatorLaunchLink,
  creatorPrivateInviteCopy,
  creatorAgreementPrepCopy,
  creatorSupportHandoffCopy,
  creatorPaidHostingPolicyCopy,
  creatorPayoutOperationsDryRunCopy,
  creatorPayoutReconciliationCopy,
  creatorTaxWorkflowReadinessCopy,
  creatorPayoutProviderSetupCopy,
  creatorPayoutReadinessCopy,
  creatorRevenueShareInterest,
  creatorTermsReadinessCopy,
  proActive,
}) {
  return [
    {
      body: creatorLaunchCopy,
      buttonLabel: 'COPY CREATOR LAUNCH COPY',
      color: '#60A5FA',
      copyText: creatorLaunchCopy,
      preLine: true,
      proActive,
      status: creatorLaunchLink ? 'INVITE READY' : 'COPY READY',
      statusActive: creatorLaunchChallenge,
      subtitle: creatorLaunchChallenge?.name || 'No hosted challenge yet',
      title: 'CREATOR LAUNCH KIT',
    },
    {
      body: 'Copy a profile completion checklist for specialty, bio, CTA, Coach Host block, and app-first launch readiness.',
      buttonLabel: 'COPY PROFILE KIT',
      color: '#14B8A6',
      copyText: creatorProfileCompletionCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorEnabled ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'PROFILE CHECK',
      statusActive: creatorEnabled,
      subtitle: 'Creator profile polish before promotion',
      title: 'CREATOR PROFILE COMPLETION KIT',
    },
    {
      body: 'Copy a reusable hosted challenge template draft checklist before creating new creator templates or paid-hosting offers.',
      buttonLabel: 'COPY TEMPLATE DRAFT KIT',
      color: '#38BDF8',
      copyText: creatorChallengeTemplateDraftCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'DRAFT ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Reusable hosted challenge template planning',
      title: 'CREATOR CHALLENGE TEMPLATE DRAFT KIT',
    },
    {
      body: 'Copy a creator leaderboard preview checklist for first-party hosted challenge movement, privacy review, and support-safe ranking boundaries.',
      buttonLabel: 'COPY LEADERBOARD PREVIEW KIT',
      color: '#10B981',
      copyText: creatorLeaderboardPreviewCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['ACTIVE', creatorAnalytics.active],
      ],
      proActive,
      status: 'PREVIEW',
      statusActive: creatorEnabled,
      subtitle: 'First-party creator ranking readiness',
      title: 'CREATOR LEADERBOARD PREVIEW KIT',
    },
    {
      body: 'Copy a branded challenge page review checklist for Coach Host blocks, creator CTA links, and consent-safe promotion.',
      buttonLabel: 'COPY BRANDED PAGE KIT',
      color: '#22D3EE',
      copyText: creatorBrandedPagePreviewCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['ACTIVE', creatorAnalytics.active],
      ],
      proActive,
      status: 'PAGE REVIEW',
      statusActive: creatorEnabled,
      subtitle: 'Coach Host page preview before promotion',
      title: 'CREATOR BRANDED PAGE PREVIEW KIT',
    },
    {
      body: 'Copy invite-only launch guidance for private Pro Coach Mode challenges using app links and first-party join/log review.',
      buttonLabel: 'COPY PRIVATE INVITE KIT',
      color: '#A855F7',
      copyText: creatorPrivateInviteCopy,
      metrics: [
        ['PRIVATE', creatorAnalytics.private],
        ['REACH', creatorAnalytics.members],
        ['HOSTED', creatorAnalytics.hosted],
      ],
      proActive,
      status: 'INVITE ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Private challenge links before paid hosting',
      title: 'PRIVATE CREATOR INVITE KIT',
    },
    {
      body: 'Draft creator offer copy before paid hosting, revenue-share terms, payout operations, and entitlement QA are live.',
      buttonLabel: 'COPY HOSTING OFFER KIT',
      color: '#F472B6',
      copyText: creatorHostingOfferCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'COPY ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Future paid-hosting planning brief',
      title: 'CREATOR HOSTING OFFER KIT',
    },
    {
      body: 'Copy creator responsibilities, moderation, payout readiness, support handoff, and marketplace guardrails before hosted paid access is reviewed.',
      buttonLabel: 'COPY CREATOR TERMS KIT',
      color: '#2DD4BF',
      copyText: creatorTermsReadinessCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'TERMS DRAFT',
      statusActive: creatorEnabled,
      subtitle: 'Responsibilities before paid hosting',
      title: 'CREATOR TERMS READINESS KIT',
    },
    {
      body: 'Copy agreement prep checks for creator identity, support owner, moderation owner, marketplace alignment, and claim rules before legal terms exist.',
      buttonLabel: 'COPY AGREEMENT PREP KIT',
      color: '#34D399',
      copyText: creatorAgreementPrepCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'LEGAL PREP',
      statusActive: creatorEnabled,
      subtitle: 'Agreement checklist before terms are live',
      title: 'CREATOR AGREEMENT PREP KIT',
    },
    {
      body: 'Copy support handoff checks for app support, creator support, moderation, refunds, privacy, and escalation before paid hosting is reviewed.',
      buttonLabel: 'COPY SUPPORT HANDOFF KIT',
      color: '#F59E0B',
      copyText: creatorSupportHandoffCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'SUPPORT PREP',
      statusActive: creatorEnabled,
      subtitle: 'Support boundaries before paid hosting',
      title: 'CREATOR SUPPORT HANDOFF KIT',
    },
    {
      body: 'Copy paid-hosting policy checks for eligible formats, marketplace alignment, creator conduct, support boundaries, and claim rules before paid hosting is approved.',
      buttonLabel: 'COPY PAID HOSTING POLICY KIT',
      color: '#FB7185',
      copyText: creatorPaidHostingPolicyCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'POLICY PREP',
      statusActive: creatorEnabled,
      subtitle: 'Paid-hosting rules before launch',
      title: 'CREATOR PAID HOSTING POLICY KIT',
    },
    {
      body: 'Copy identity, content ownership, brand permission, support owner, moderation owner, and claim-safety checks before creator terms or revenue-share.',
      buttonLabel: 'COPY IDENTITY PREP KIT',
      color: '#0EA5E9',
      copyText: creatorIdentityVerificationPrepCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'VERIFY PREP',
      statusActive: creatorEnabled,
      subtitle: 'Identity and brand checks before paid hosting',
      title: 'CREATOR IDENTITY VERIFICATION PREP KIT',
    },
    {
      body: 'Copy creator conduct, member safety, takedown, support escalation, privacy, and claim-review checks before paid-hosting review.',
      buttonLabel: 'COPY MODERATION KIT',
      color: '#F97316',
      copyText: creatorModerationReadinessCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'MOD PREP',
      statusActive: creatorEnabled,
      subtitle: 'Safety and takedown checks before paid hosting',
      title: 'CREATOR MODERATION READINESS KIT',
    },
    {
      body: 'Copy a final go/no-go gate for creator profile, agreement, identity, moderation, support, payout, marketplace, and entitlement QA before paid hosting is promoted.',
      buttonLabel: 'COPY CREATOR LAUNCH GATE',
      color: '#FACC15',
      copyText: creatorPaidHostingLaunchGateCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'GATE',
      statusActive: creatorEnabled,
      subtitle: 'Go/no-go checks before paid hosting',
      title: 'CREATOR PAID HOSTING LAUNCH GATE KIT',
    },
    {
      body: 'Copy a hold response when creator paid-hosting evidence, store QA, payout/tax, moderation, support, or marketplace checks are not ready.',
      buttonLabel: 'COPY CREATOR HOLD PLAN',
      color: '#FBBF24',
      copyText: creatorPaidHostingHoldPlanCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'HOLD',
      statusActive: creatorEnabled,
      subtitle: 'Pause criteria when the launch gate fails',
      title: 'CREATOR PAID HOSTING HOLD PLAN KIT',
    },
    {
      body: 'Copy payout provider, tax, identity, refund, marketplace, support, and creator-claim checks before any revenue-share promise.',
      buttonLabel: 'COPY CREATOR PAYOUT KIT',
      color: '#818CF8',
      copyText: creatorPayoutReadinessCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'OPS CHECK',
      statusActive: creatorEnabled,
      subtitle: 'Payout operations before revenue-share',
      title: 'CREATOR PAYOUT READINESS KIT',
    },
    {
      body: 'Copy payout provider selection, legal entity, tax workflow, support owner, refund handoff, and finance reconciliation setup checks before any payout onboarding goes live.',
      buttonLabel: 'COPY PAYOUT SETUP KIT',
      color: '#A78BFA',
      copyText: creatorPayoutProviderSetupCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'PROVIDER PREP',
      statusActive: creatorEnabled,
      subtitle: 'Provider setup before payout onboarding',
      title: 'CREATOR PAYOUT PROVIDER SETUP KIT',
    },
    {
      body: 'Copy a zero-money payout rehearsal checklist for mock eligibility, mock payout events, refund adjustments, finance reconciliation, and owner handoffs before real payout onboarding.',
      buttonLabel: 'COPY PAYOUT DRY-RUN KIT',
      color: '#C084FC',
      copyText: creatorPayoutOperationsDryRunCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'DRY RUN',
      statusActive: creatorEnabled,
      subtitle: 'Zero-money payout rehearsal before launch',
      title: 'CREATOR PAYOUT OPERATIONS DRY-RUN KIT',
    },
    {
      body: 'Copy payout reconciliation checks for mock payout events, store-test evidence, refund adjustments, entitlement QA, finance notes, and owner sign-off before any real payout run.',
      buttonLabel: 'COPY PAYOUT RECONCILIATION KIT',
      color: '#D8B4FE',
      copyText: creatorPayoutReconciliationCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'RECONCILE',
      statusActive: creatorEnabled,
      subtitle: 'Mock payout evidence matching before launch',
      title: 'CREATOR PAYOUT RECONCILIATION KIT',
    },
    {
      body: 'Copy tax workflow readiness checks for provider tax forms, country coverage, withholding review, finance export, and owner handoff before creator onboarding.',
      buttonLabel: 'COPY TAX WORKFLOW KIT',
      color: '#F0ABFC',
      copyText: creatorTaxWorkflowReadinessCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'TAX PREP',
      statusActive: creatorEnabled,
      subtitle: 'Tax workflow review before payout onboarding',
      title: 'CREATOR TAX WORKFLOW READINESS KIT',
    },
    {
      body: 'Answer creator questions without claiming paid hosting, payouts, contracts, purchases, or revenue-share are live.',
      buttonLabel: 'COPY CREATOR REPLIES',
      color: '#818CF8',
      copyText: creatorHostingObjectionReplyCopy,
      proActive,
      status: 'COPY ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Manual replies before revenue-share launch',
      title: 'CREATOR HOSTING OBJECTION REPLY KIT',
    },
  ];
}
