export function buildCreatorPlanningCopyKitConfigs({
  creatorAnalytics,
  creatorBrandedPagePreviewCopy,
  creatorChallengeTemplateDraftCopy,
  creatorProfileCompletionCopy,
  creatorEnabled,
  creatorHostingObjectionReplyCopy,
  creatorHostingOfferCopy,
  creatorLaunchChallenge,
  creatorLaunchCopy,
  creatorLaunchLink,
  creatorPrivateInviteCopy,
  creatorAgreementPrepCopy,
  creatorPayoutReadinessCopy,
  creatorRevenueShareInterest,
  creatorTermsReadinessCopy,
  proActive,
}) {
  return [
    {
      body: creatorLaunchCopy,
      buttonLabel: 'COPY CREATOR LAUNCH COPY',
      color: '#60A5FA',
      copyText: creatorLaunchCopy,
      preLine: true,
      proActive,
      status: creatorLaunchLink ? 'INVITE READY' : 'COPY READY',
      statusActive: creatorLaunchChallenge,
      subtitle: creatorLaunchChallenge?.name || 'No hosted challenge yet',
      title: 'CREATOR LAUNCH KIT',
    },
    {
      body: 'Copy a profile completion checklist for specialty, bio, CTA, Coach Host block, and app-first launch readiness.',
      buttonLabel: 'COPY PROFILE KIT',
      color: '#14B8A6',
      copyText: creatorProfileCompletionCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorEnabled ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'PROFILE CHECK',
      statusActive: creatorEnabled,
      subtitle: 'Creator profile polish before promotion',
      title: 'CREATOR PROFILE COMPLETION KIT',
    },
    {
      body: 'Copy a reusable hosted challenge template draft checklist before creating new creator templates or paid-hosting offers.',
      buttonLabel: 'COPY TEMPLATE DRAFT KIT',
      color: '#38BDF8',
      copyText: creatorChallengeTemplateDraftCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'DRAFT ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Reusable hosted challenge template planning',
      title: 'CREATOR CHALLENGE TEMPLATE DRAFT KIT',
    },
    {
      body: 'Copy a branded challenge page review checklist for Coach Host blocks, creator CTA links, and consent-safe promotion.',
      buttonLabel: 'COPY BRANDED PAGE KIT',
      color: '#22D3EE',
      copyText: creatorBrandedPagePreviewCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['ACTIVE', creatorAnalytics.active],
      ],
      proActive,
      status: 'PAGE REVIEW',
      statusActive: creatorEnabled,
      subtitle: 'Coach Host page preview before promotion',
      title: 'CREATOR BRANDED PAGE PREVIEW KIT',
    },
    {
      body: 'Copy invite-only launch guidance for private Pro Coach Mode challenges using app links and first-party join/log review.',
      buttonLabel: 'COPY PRIVATE INVITE KIT',
      color: '#A855F7',
      copyText: creatorPrivateInviteCopy,
      metrics: [
        ['PRIVATE', creatorAnalytics.private],
        ['REACH', creatorAnalytics.members],
        ['HOSTED', creatorAnalytics.hosted],
      ],
      proActive,
      status: 'INVITE ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Private challenge links before paid hosting',
      title: 'PRIVATE CREATOR INVITE KIT',
    },
    {
      body: 'Draft creator offer copy before paid hosting, revenue-share terms, payout operations, and entitlement QA are live.',
      buttonLabel: 'COPY HOSTING OFFER KIT',
      color: '#F472B6',
      copyText: creatorHostingOfferCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
      ],
      proActive,
      status: 'COPY ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Future paid-hosting planning brief',
      title: 'CREATOR HOSTING OFFER KIT',
    },
    {
      body: 'Copy creator responsibilities, moderation, payout readiness, support handoff, and marketplace guardrails before hosted paid access is reviewed.',
      buttonLabel: 'COPY CREATOR TERMS KIT',
      color: '#2DD4BF',
      copyText: creatorTermsReadinessCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'TERMS DRAFT',
      statusActive: creatorEnabled,
      subtitle: 'Responsibilities before paid hosting',
      title: 'CREATOR TERMS READINESS KIT',
    },
    {
      body: 'Copy agreement prep checks for creator identity, support owner, moderation owner, marketplace alignment, and claim rules before legal terms exist.',
      buttonLabel: 'COPY AGREEMENT PREP KIT',
      color: '#34D399',
      copyText: creatorAgreementPrepCopy,
      metrics: [
        ['HOSTED', creatorAnalytics.hosted],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'LEGAL PREP',
      statusActive: creatorEnabled,
      subtitle: 'Agreement checklist before terms are live',
      title: 'CREATOR AGREEMENT PREP KIT',
    },
    {
      body: 'Copy payout provider, tax, identity, refund, marketplace, support, and creator-claim checks before any revenue-share promise.',
      buttonLabel: 'COPY CREATOR PAYOUT KIT',
      color: '#818CF8',
      copyText: creatorPayoutReadinessCopy,
      metrics: [
        ['REACH', creatorAnalytics.members],
        ['READY', creatorAnalytics.revenueReady],
        ['BETA', creatorRevenueShareInterest ? 'YES' : 'NO'],
      ],
      proActive,
      status: 'OPS CHECK',
      statusActive: creatorEnabled,
      subtitle: 'Payout operations before revenue-share',
      title: 'CREATOR PAYOUT READINESS KIT',
    },
    {
      body: 'Answer creator questions without claiming paid hosting, payouts, contracts, purchases, or revenue-share are live.',
      buttonLabel: 'COPY CREATOR REPLIES',
      color: '#818CF8',
      copyText: creatorHostingObjectionReplyCopy,
      proActive,
      status: 'COPY ONLY',
      statusActive: creatorEnabled,
      subtitle: 'Manual replies before revenue-share launch',
      title: 'CREATOR HOSTING OBJECTION REPLY KIT',
    },
  ];
}
