import {
  buildLaunchExperiments,
  buildLaunchQaChecklist,
  pickRecommendedLaunchExperiment,
  scoreLaunchExperiment,
} from './monetizationModel';

export function buildLaunchExperimentCopy({
  proTrialDemandTotal,
  storePackCount,
  referralJoins,
  partnerDemandTotal,
  weeklyCampaignPrompt,
  monetizationSignalTotal,
  campaignPerformanceSummary,
  storeCatalog,
}) {
  const launchExperiments = buildLaunchExperiments({
    proTrialDemandTotal,
    storePackCount,
    referralJoins,
    partnerDemandTotal,
  });
  const recommendedLaunchExperiment = pickRecommendedLaunchExperiment(launchExperiments);
  const {
    scorecard: experimentScorecard,
    score: experimentScore,
    label: experimentScoreLabel,
  } = scoreLaunchExperiment({
    monetizationSignalTotal,
    referralJoins,
    campaignPerformanceSummary,
  });
  const launchQaChecklist = buildLaunchQaChecklist(storeCatalog);

  return {
    launchExperiments,
    experimentScore,
    experimentScoreLabel,
    recommendedLaunchExperiment,
    weeklyCampaignExperimentBriefCopy: `Rise With The Tribe Weekly Campaign Experiment Brief Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\nSignal: ${recommendedLaunchExperiment.signal}\nAction: ${recommendedLaunchExperiment.action}\n\nExperiment brief:\n[ ] Anchor the experiment to this week's campaign CTA: ${weeklyCampaignPrompt.cta}\n[ ] Use the launch card, storyboard, content calendar, and DM keyword kit as manual copy inputs\n[ ] Measure only first-party app movement: challenge joins, referral joins, feature submissions, share-card usage, and saved interest signals\n[ ] Review the result with the Weekly Campaign Review Kit before repeating or retiring the experiment\n\nThis is a manual weekly campaign experiment brief only. Do not create experiment records, schedule posts, auto-post to Instagram, add tracking pixels, scrape or store Instagram DMs, export per-user activity, share user content without consent, imply paid access is live, promise outcomes, or imply medical results.`,
    weeklyCampaignExperimentBriefApprovalCopy: `Rise With The Tribe Weekly Campaign Experiment Brief Approval Kit:\n\nCampaign experiment brief ready for approval: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\nSignal: ${recommendedLaunchExperiment.signal}\nAction: ${recommendedLaunchExperiment.action}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\n\nManual experiment brief approval:\n[ ] Compare the experiment brief, experiment QA note, approved storyboard reference, support-risk route, consent queue, paid-language hold, first-party signal summary, and app-first CTA before approving the experiment lane.\n[ ] Choose one approval lane: approve manual test copy, hold for storyboard edits, route support risk, request consent review, keep the free-loop CTA, or escalate to retrospective readiness only after the manual campaign push is complete.\n[ ] Keep approval inputs first-party and aggregate: challenge joins, referral joins, Feature Me submissions with consent, share-card usage, saved interest, support notes, and entitlement QA status only.\n[ ] Record approval owner, reviewedAt timestamp, approved experiment lane, approved experiment brief reference, unresolved blockers, evidence reference, support-risk route, and retrospective readiness trigger before any retrospective readback starts.\n\nThis is a manual Weekly Campaign Experiment Brief Approval Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveReadinessHandoffCopy: `Rise With The Tribe Launch Retrospective Readiness Handoff Kit:\n\nExperiment ready for retrospective handoff: ${recommendedLaunchExperiment.label}\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual retrospective readiness handoff:\n[ ] Compare the approved experiment lane, experiment brief approval, experiment QA note, post-complete callback, first-party monitor, support-risk route, consent queue, and entitlement QA note before retrospective readback starts.\n[ ] Confirm the handoff names one retrospective owner, one approved experiment brief reference, one approved campaign push reference, one first-party signal summary, one support-risk route, one consent queue, and one paid-language hold note.\n[ ] Keep handoff inputs first-party and aggregate only: challenge joins, referral joins, Feature Me submissions with consent, share-card usage, saved interest, support notes, and entitlement QA status.\n[ ] Record retrospective handoff owner, reviewedAt timestamp, retrospective owner, approved experiment lane, unresolved blockers, evidence reference, support-risk route, consent queue, and repeat/hold decision deadline before the readiness script is used.\n\nThis is a manual Launch Retrospective Readiness Handoff Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveReadinessQaCopy: `Rise With The Tribe Launch Retrospective Readiness QA Kit:\n\nExperiment readiness QA: ${recommendedLaunchExperiment.label}\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual retrospective readiness QA:\n[ ] Compare the retrospective handoff, approved experiment lane, approved campaign push reference, first-party signal summary, support-risk route, consent queue, entitlement QA status, and paid-language hold before the readiness script is used.\n[ ] Confirm the readiness script separates Instagram reactions from product proof, keeps every readback aggregate, and names one repeat, hold, support-review, store-QA, prompt-refresh, or free-loop decision lane.\n[ ] Remove unapproved member stories, private replies, tracking language, attribution claims, paid-live claims, outcome promises, medical claims, reward language, discount language, refund promises, or pressure language before readback starts.\n[ ] Record readiness QA owner, reviewedAt timestamp, approved readiness script reference, unresolved blockers, evidence reference, support-risk route, consent queue, and repeat/hold decision owner before any repeat or pause decision is made.\n\nThis is a manual Launch Retrospective Readiness QA Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveDecisionCopy: `Rise With The Tribe Launch Retrospective Decision Kit:\n\nExperiment decision ready: ${recommendedLaunchExperiment.label}\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual retrospective decision:\n[ ] Compare the readiness script, readiness QA note, retrospective handoff, first-party signal summary, support-risk route, consent queue, entitlement QA status, and paid-language hold before choosing the next action.\n[ ] Choose one decision lane: repeat the experiment, pause it, route support review, open store/entitlement QA, refresh the weekly prompt, keep the member in the free challenge loop, or hold paid-language copy.\n[ ] Keep the decision first-party and aggregate: challenge joins, referral joins, Feature Me submissions with consent, share-card usage, saved interest, support notes, and entitlement QA status only.\n[ ] Record retrospective decision owner, reviewedAt timestamp, decision lane, evidence reference, support-risk route, consent queue, next campaign owner, and no-paid-live note before any next campaign copy is written.\n\nThis is a manual Launch Retrospective Decision Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveDecisionReplyCopy: `Rise With The Tribe Launch Retrospective Decision Reply Kit:\n\nExperiment decision reply: ${recommendedLaunchExperiment.label}\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual retrospective decision replies:\nAPPROVED TO REPEAT: The last campaign created enough first-party movement to repeat this experiment manually next week. Keep the CTA app-first, use aggregate proof only, and carry the same support-risk route, consent queue, entitlement QA status, and paid-language hold.\nPAUSE FOR NOW: The signal is not strong enough to repeat this experiment yet. Keep members in the free weekly challenge loop, gather more first-party app movement, and do not use Instagram reactions as product proof.\nROUTE SUPPORT REVIEW: Pause public follow-up until support-risk replies, account questions, store confusion, or consent questions are reviewed inside the app support route.\nOPEN STORE QA: Keep paid-language copy on hold until App Store / Google Play product, receipt-validation, restore/sync, and entitlement QA evidence is reviewed.\nREFRESH WEEKLY PROMPT: Move the next campaign owner to a safer weekly prompt, new app-first CTA, or free challenge loop before any new campaign copy is written.\n\nThis is a manual Launch Retrospective Decision Reply Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveNextCampaignHandoffCopy: `Rise With The Tribe Launch Retrospective Next Campaign Handoff Kit:\n\nNext campaign handoff from: ${recommendedLaunchExperiment.label}\nCampaign reviewed: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual next campaign handoff:\n[ ] Carry forward the final decision reply, retrospective decision lane, first-party signal summary, support-risk route, consent queue, entitlement QA status, and paid-language hold into the next campaign brief.\n[ ] Assign one next campaign owner, one preflight owner, one support owner, one consent reviewer, and one store/entitlement QA owner before any next campaign copy is drafted.\n[ ] Choose the next starting lane: repeat approved experiment, refresh weekly prompt, free challenge loop, support-first follow-up, store QA hold, or paid-language hold.\n[ ] Record handoff owner, reviewedAt timestamp, next campaign owner, next preflight owner, evidence reference, support-risk route, consent queue, paid-language hold, and no-paid-live note before the next preflight owner handoff begins.\n\nThis is a manual Launch Retrospective Next Campaign Handoff Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveNextCampaignQaCopy: `Rise With The Tribe Launch Retrospective Next Campaign QA Kit:\n\nNext campaign QA from: ${recommendedLaunchExperiment.label}\nCampaign reviewed: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual next campaign QA:\n[ ] Compare the next campaign handoff, final decision reply, retrospective decision lane, first-party signal summary, support-risk route, consent queue, entitlement QA status, and paid-language hold before preflight starts.\n[ ] Confirm the next starting lane is one of: repeat approved experiment, refresh weekly prompt, free challenge loop, support-first follow-up, store QA hold, or paid-language hold.\n[ ] Remove unapproved member stories, private replies, tracking language, attribution claims, paid-live claims, outcome promises, medical claims, reward language, discount language, refund promises, or pressure language before the next campaign brief is written.\n[ ] Record next campaign QA owner, reviewedAt timestamp, approved handoff reference, next campaign owner, next preflight owner, unresolved blockers, evidence reference, support-risk route, consent queue, and no-paid-live note before preflight owner handoff starts.\n\nThis is a manual Launch Retrospective Next Campaign QA Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchRetrospectiveNextCampaignBriefCopy: `Rise With The Tribe Launch Retrospective Next Campaign Brief Kit:\n\nNext campaign brief from: ${recommendedLaunchExperiment.label}\nCampaign reviewed: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nManual next campaign brief:\n[ ] Start from the approved next campaign QA note, final decision reply, retrospective decision lane, support-risk route, consent queue, entitlement QA status, and paid-language hold.\n[ ] Draft one app-first campaign angle, one free weekly challenge CTA, one support-safe reply route, one consent-safe proof lane, and one no-paid-live note before preflight owner handoff.\n[ ] Choose the brief lane: repeat approved experiment, refreshed weekly prompt, free-loop nurture, support-first follow-up, store QA hold, or paid-language hold.\n[ ] Record next campaign brief owner, reviewedAt timestamp, approved QA reference, campaign angle, app-first CTA, evidence reference, support-risk route, consent queue, paid-language hold, and preflight owner before new launch copy is written.\n\nThis is a manual Launch Retrospective Next Campaign Brief Kit only. Do not create experiment records, create attribution records, add tracking pixels, auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    launchExperimentCopy: `Rise With The Tribe Launch Experiment Kit:\n\nRecommended test: ${recommendedLaunchExperiment.label}\nSignal: ${recommendedLaunchExperiment.signal}\nAction: ${recommendedLaunchExperiment.action}\n\nThis is a manual Instagram/app experiment. Use first-party app signals only, do not add tracking pixels, and do not promote paid access as live until store validation and entitlement QA are complete.\n\nThis week's campaign hook: ${weeklyCampaignPrompt.name} - ${weeklyCampaignPrompt.cta} ${weeklyCampaignPrompt.hashtag}`,
    launchExperimentScorecardCopy: `Rise With The Tribe Launch Experiment Scorecard:\n\nRecommended test: ${recommendedLaunchExperiment.label}\nScore: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nCommunity loop: ${experimentScorecard.communityLoop}\nRisk: ${experimentScorecard.risk}\n\nUse this as a manual planning score only. It uses first-party app signals, does not add tracking pixels, and does not grant or imply paid access.`,
    launchQaChecklistCopy: `Rise With The Tribe Release QA Checklist:\n\n${launchQaChecklist.map(([label, status, ready]) => `${ready ? '[x]' : '[ ]'} ${label}: ${status}`).join('\n')}\n\nBefore a monetization or social launch: confirm store products, receipt-validation credentials, entitlement writes, feature parity docs, and native/web share flows across Web, iOS, and Android.`,
    launchRetrospectiveCopy: `Rise With The Tribe Launch Retrospective Kit:\n\nExperiment reviewed: ${recommendedLaunchExperiment.label}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\n\nReview manually after the push: challenge joins, referral movement, feature submissions, share-card usage, and entitlement validation. This is a first-party review prompt only; it does not add tracking pixels, automated attribution, or paid-access changes.`,
    launchRetrospectiveReadinessScriptCopy: `Rise With The Tribe Launch Retrospective Readiness Script Kit:\n\nExperiment reviewed: ${recommendedLaunchExperiment.label}\nPlanning score: ${experimentScore}/100 (${experimentScoreLabel})\nDemand signal: ${experimentScorecard.demandSignal}\nCampaign reach: ${experimentScorecard.campaignReach}\nReferral joins: ${referralJoins}\nCommunity loop: ${experimentScorecard.communityLoop}\nThis week's campaign: ${weeklyCampaignPrompt.name} ${weeklyCampaignPrompt.hashtag}\n\nManual retrospective readiness script:\n1. Confirm the campaign push is complete before reviewing outcomes: launch card posted manually, weekly CTA used, DM/comment copy handled manually, and support-risk replies routed before follow-up.\n2. Capture only first-party app movement: challenge joins, referral joins, Feature Me submissions, share-card usage, saved Pro interest, saved creator interest, saved partner interest, support notes, and entitlement QA status.\n3. Separate directional Instagram reactions from product or monetization proof; use them for content ideas only, not attribution, targeting, private records, purchases, rewards, or entitlement decisions.\n4. Choose the next action in-app: repeat the experiment, pause it, move to support review, open store/entitlement QA, refresh the weekly prompt, or keep the member in the free challenge loop.\n\nThis launch retrospective readiness script is copy-only. Do not create experiment records, attribution records, tracking pixels, auto-posts, scraped/stored DMs, off-platform identity records, purchases, refunds, rewards, payouts, partner links, coupons, discounts, entitlement writes, paid-access grants, store-review submissions, paid-live claims, private member exports, automated messages, outcome promises, medical claims, or pressure members.`,
  };
}
