import { buildMonetizationPreLaunchCopyKits } from './monetizationPreLaunchCopyKits';

export function buildMonetizationPreLaunchSectionData({
  campaignPerformanceSummary,
  communityAmbassadorCopy,
  communityEventInterestMessage,
  communityEventInterestCopy,
  communityEventInterestSummary,
  creatorEnabled,
  creatorRevenueShareTotal,
  customerValueChecklistCopy,
  daysActive,
  founderMemberOfferCopy,
  approvedLaunchExperimentReviews,
  experimentScore,
  experimentScoreLabel,
  featureReviewQueue,
  handleLaunchExperimentReviewDecision,
  handleLaunchExperimentReviewSubmit,
  isAdmin,
  isSubmittingLaunchExperimentReview,
  isSavingCommunityEventInterest,
  launchExperimentReviewMessage,
  launchExperimentReviewNotes,
  launchExperimentReviewQueue,
  monetizationLaunchCopy,
  monetizationSignalTotal,
  onCommunityEventInterestToggle,
  partnerDemandTotal,
  pricingTestKitCopy,
  proTrialDemandTotal,
  recommendedLaunchExperiment,
  recommendedRevenuePath,
  reviewingLaunchExperimentReviewId,
  setLaunchExperimentReviewNotes,
  referralJoins,
  revenuePathwayPlannerCopy,
  revenuePathways,
  selectedCommunityEventInterestIds,
  storePackCount,
  storeSubscriptionCount,
  supportReviewQueue,
}) {
  const copyKits = buildMonetizationPreLaunchCopyKits({
    campaignPerformanceSummary,
    communityAmbassadorCopy,
    communityEventInterestCopy,
    customerValueChecklistCopy,
    daysActive,
    founderMemberOfferCopy,
    monetizationSignalTotal,
    pricingTestKitCopy,
    recommendedRevenuePath,
    referralJoins,
    storePackCount,
    storeSubscriptionCount,
  });

  return {
    canShowPlanningKits: isAdmin || creatorEnabled,
    communityEventInterestSectionProps: {
      communityEventInterestMessage,
      communityEventInterestSummary,
      isAdmin,
      isSavingCommunityEventInterest,
      onCommunityEventInterestToggle,
      selectedCommunityEventInterestIds,
    },
    launchBoardProps: {
      approvedLaunchExperimentReviews,
      creatorRevenueShareTotal,
      experimentScore,
      experimentScoreLabel,
      featureReviewQueue,
      isAdmin,
      isSubmittingLaunchExperimentReview,
      launchExperimentReviewMessage,
      launchExperimentReviewNotes,
      launchExperimentReviewQueue,
      monetizationLaunchCopy,
      monetizationSignalTotal,
      onLaunchExperimentReviewDecision: handleLaunchExperimentReviewDecision,
      onLaunchExperimentReviewSubmit: handleLaunchExperimentReviewSubmit,
      partnerDemandTotal,
      proTrialDemandTotal,
      recommendedLaunchExperiment,
      referralJoins,
      reviewingLaunchExperimentReviewId,
      setLaunchExperimentReviewNotes,
      supportReviewQueue,
    },
    primaryCopyKit: copyKits[0],
    followUpCopyKits: copyKits.slice(1),
    revenuePathwayPlannerProps: {
      recommendedRevenuePath,
      revenuePathwayPlannerCopy,
      revenuePathways,
    },
  };
}
