import { buildMonetizationPreLaunchCopyKits } from './monetizationPreLaunchCopyKits';

export function buildMonetizationPreLaunchSectionData({
  campaignPerformanceSummary,
  communityAmbassadorCopy,
  approvedCommunityEventReviews,
  communityEventInterestMessage,
  communityEventInterestCopy,
  communityEventInterestSummary,
  communityEventReviewMessage,
  communityEventReviewNotes,
  communityEventReviewQueue,
  communityEventReviewDecisionReplyCopy,
  communityEventSupportEscalationCopy,
  creatorEnabled,
  creatorRevenueShareTotal,
  customerValueChecklistCopy,
  approvedCustomerValueReviews,
  customerValueReviewDecisionReplyCopy,
  customerValueReviewMessage,
  customerValueReviewNotes,
  customerValueReviewQueue,
  daysActive,
  founderMemberOfferCopy,
  approvedLaunchExperimentReviews,
  experimentScore,
  experimentScoreLabel,
  featureReviewQueue,
  handleLaunchExperimentReviewDecision,
  handleCommunityEventReviewDecision,
  handleCommunityEventReviewSubmit,
  handleCustomerValueReviewDecision,
  handleCustomerValueReviewSubmit,
  handleLaunchExperimentReviewSubmit,
  isAdmin,
  isSubmittingLaunchExperimentReview,
  isSubmittingCommunityEventReview,
  isSubmittingCustomerValueReview,
  isSavingCommunityEventInterest,
  launchExperimentReviewMessage,
  launchExperimentReviewNotes,
  launchExperimentReviewQueue,
  monetizationLaunchCopy,
  monetizationSignalTotal,
  onCommunityEventInterestToggle,
  partnerDemandTotal,
  pricingTestKitCopy,
  proTrialDemandTotal,
  recommendedLaunchExperiment,
  recommendedRevenuePath,
  reviewingLaunchExperimentReviewId,
  reviewingCommunityEventReviewId,
  reviewingCustomerValueReviewId,
  setCommunityEventReviewNotes,
  setCustomerValueReviewNotes,
  setLaunchExperimentReviewNotes,
  referralJoins,
  revenuePathwayPlannerCopy,
  revenuePathways,
  selectedCommunityEventInterestIds,
  storePackCount,
  storeSubscriptionCount,
  supportReviewQueue,
}) {
  const copyKits = buildMonetizationPreLaunchCopyKits({
    campaignPerformanceSummary,
    communityAmbassadorCopy,
    communityEventInterestCopy,
    customerValueChecklistCopy,
    daysActive,
    founderMemberOfferCopy,
    monetizationSignalTotal,
    pricingTestKitCopy,
    recommendedRevenuePath,
    referralJoins,
    storePackCount,
    storeSubscriptionCount,
  });

  return {
    canShowPlanningKits: isAdmin || creatorEnabled,
    communityEventInterestSectionProps: {
      communityEventInterestMessage,
      communityEventInterestSummary,
      approvedCommunityEventReviews,
      communityEventReviewMessage,
      communityEventReviewNotes,
      communityEventReviewQueue,
      communityEventReviewDecisionReplyCopy,
      communityEventSupportEscalationCopy,
      isAdmin,
      isSubmittingCommunityEventReview,
      isSavingCommunityEventInterest,
      onCommunityEventReviewDecision: handleCommunityEventReviewDecision,
      onCommunityEventReviewSubmit: handleCommunityEventReviewSubmit,
      onCommunityEventInterestToggle,
      reviewingCommunityEventReviewId,
      selectedCommunityEventInterestIds,
      setCommunityEventReviewNotes,
    },
    customerValueReviewSectionProps: {
      approvedCustomerValueReviews,
      customerValueReviewDecisionReplyCopy,
      customerValueReviewMessage,
      customerValueReviewNotes,
      customerValueReviewQueue,
      isAdmin,
      isSubmittingCustomerValueReview,
      onCustomerValueReviewDecision: handleCustomerValueReviewDecision,
      onCustomerValueReviewSubmit: handleCustomerValueReviewSubmit,
      reviewingCustomerValueReviewId,
      setCustomerValueReviewNotes,
    },
    launchBoardProps: {
      approvedLaunchExperimentReviews,
      creatorRevenueShareTotal,
      experimentScore,
      experimentScoreLabel,
      featureReviewQueue,
      isAdmin,
      isSubmittingLaunchExperimentReview,
      launchExperimentReviewMessage,
      launchExperimentReviewNotes,
      launchExperimentReviewQueue,
      monetizationLaunchCopy,
      monetizationSignalTotal,
      onLaunchExperimentReviewDecision: handleLaunchExperimentReviewDecision,
      onLaunchExperimentReviewSubmit: handleLaunchExperimentReviewSubmit,
      partnerDemandTotal,
      proTrialDemandTotal,
      recommendedLaunchExperiment,
      referralJoins,
      reviewingLaunchExperimentReviewId,
      setLaunchExperimentReviewNotes,
      supportReviewQueue,
    },
    primaryCopyKit: copyKits[0],
    followUpCopyKits: copyKits.slice(1),
    revenuePathwayPlannerProps: {
      recommendedRevenuePath,
      revenuePathwayPlannerCopy,
      revenuePathways,
    },
  };
}
