export function buildPartnerAdminCopyKitProps({
  campaignPerformanceSummary,
  copyText,
  partnerActivationCopy,
  partnerCampaignObjectionReplyCopy,
  partnerCampaignRetrospectiveCopy,
  partnerCampaignRetrospectiveDecisionReplyCopy,
  partnerCampaignSupportEscalationCopy,
  partnerContractReadinessCopy,
  partnerDemandTotal,
  partnerPitchCopy,
  partnerTermsReadinessCopy,
  referralJoins,
  topPartnerPerk,
}) {
  return {
    campaignPerformanceSummary,
    copyText,
    partnerActivationCopy,
    partnerCampaignObjectionReplyCopy,
    partnerCampaignRetrospectiveCopy,
    partnerCampaignRetrospectiveDecisionReplyCopy,
    partnerCampaignSupportEscalationCopy,
    partnerContractReadinessCopy,
    partnerDemandTotal,
    partnerPitchCopy,
    partnerTermsReadinessCopy,
    referralJoins,
    topPartnerPerk,
  };
}
