export function buildPartnerRevenueCreatorScreenInputs(screenState) {
  const {
    creatorBio,
    creatorCtaUrl,
    creatorEnabled,
    creatorHostingApplicationReviewNotes,
    creatorTemplateDraftReviewNotes,
    creatorRevenueShareInterest,
    creatorSpecialty,
    isSubmittingCreatorHostingApplication,
    isSubmittingCreatorTemplateDraft,
    profile,
    setPublishedCreatorChallengeTemplates,
    reviewingCreatorHostingApplicationId,
    reviewingCreatorTemplateDraftId,
    setCreatorHostingApplicationMessage,
    setCreatorHostingApplicationReviewQueue,
    setCreatorMessage,
    setCreatorTemplateDraftMessage,
    setCreatorTemplateDraftReviewQueue,
    setIsSavingCreator,
    setIsSubmittingCreatorHostingApplication,
    setIsSubmittingCreatorTemplateDraft,
    setProfile,
    setPublishedCreatorChallengeTemplates,
    setReviewingCreatorHostingApplicationId,
    setReviewingCreatorTemplateDraftId,
  } = screenState;

  return {
    creatorBio,
    creatorCtaUrl,
    creatorEnabled,
    creatorHostingApplicationReviewNotes,
    creatorTemplateDraftReviewNotes,
    creatorRevenueShareInterest,
    creatorSpecialty,
    isSubmittingCreatorHostingApplication,
    isSubmittingCreatorTemplateDraft,
    profile,
    reviewingCreatorHostingApplicationId,
    reviewingCreatorTemplateDraftId,
    setCreatorHostingApplicationMessage,
    setCreatorHostingApplicationReviewQueue,
    setCreatorMessage,
    setCreatorTemplateDraftMessage,
    setCreatorTemplateDraftReviewQueue,
    setIsSavingCreator,
    setIsSubmittingCreatorHostingApplication,
    setIsSubmittingCreatorTemplateDraft,
    setProfile,
    setReviewingCreatorHostingApplicationId,
    setReviewingCreatorTemplateDraftId,
  };
}
