export function buildPartnerRevenueDemandScreenInputs(screenState) {
  const {
    approvedLaunchExperimentReviews,
    isSubmittingLaunchExperimentReview,
    launchExperimentReviewNotes,
    launchExperimentReviewQueue,
    reviewingLaunchExperimentReviewId,
    selectedCommunityEventInterestIds,
    selectedProTrialReasonIds,
    setApprovedLaunchExperimentReviews,
    setCommunityEventInterestMessage,
    setIsSubmittingLaunchExperimentReview,
    setIsSavingCommunityEventInterest,
    setIsSavingProTrialInterest,
    setLaunchExperimentReviewMessage,
    setLaunchExperimentReviewNotes,
    setLaunchExperimentReviewQueue,
    setProTrialMessage,
    setReviewingLaunchExperimentReviewId,
    setSelectedCommunityEventInterestIds,
    setSelectedProTrialReasonIds,
  } = screenState;

  return {
    approvedLaunchExperimentReviews,
    isSubmittingLaunchExperimentReview,
    launchExperimentReviewNotes,
    launchExperimentReviewQueue,
    reviewingLaunchExperimentReviewId,
    selectedCommunityEventInterestIds,
    selectedProTrialReasonIds,
    setApprovedLaunchExperimentReviews,
    setCommunityEventInterestMessage,
    setIsSubmittingLaunchExperimentReview,
    setIsSavingCommunityEventInterest,
    setIsSavingProTrialInterest,
    setLaunchExperimentReviewMessage,
    setLaunchExperimentReviewNotes,
    setLaunchExperimentReviewQueue,
    setProTrialMessage,
    setReviewingLaunchExperimentReviewId,
    setSelectedCommunityEventInterestIds,
    setSelectedProTrialReasonIds,
  };
}
