export function buildPartnerMonetizationCopy({
  topPartnerPerk,
  partnerDemandTotal,
  campaignPerformanceSummary,
  referralJoins,
  partnerPerkClaimReviewQueue,
  partnerCampaignApplicationReviewQueue,
  partnerPerkHandoffAuditReviewQueue = [],
  approvedPartnerPerkHandoffAuditReviews = [],
}) {
  const topLabel = topPartnerPerk?.label || 'Gathering';
  const topDemand = topPartnerPerk?.demand || 0;
  const campaignReach = campaignPerformanceSummary.memberReach || 0;
  const perkClaimCount = partnerPerkClaimReviewQueue.length;
  const partnerApplicationCount = partnerCampaignApplicationReviewQueue.length;

  const partnerActivationCopy = `Rise With The Tribe Partner Campaign Activation Kit:\n\nPilot theme: ${topPartnerPerk?.title || 'Aligned member perk'}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nPilot plan: attach one aligned sponsor value to a weekly or seasonal challenge, ask members to save perk interest, and review challenge joins plus feature submissions after the push.\n\nThis is a manual planning brief only. Do not add partner links, tracking pixels, ad targeting, purchases, entitlements, or paid-access claims until partner terms, privacy review, and store/entitlement QA are complete.`;
  const partnerTermsReadinessCopy = `Rise With The Tribe Partner Terms Readiness Kit:\n\nPilot theme: ${topPartnerPerk?.title || 'Aligned member perk'}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nTerms checklist:\n- Partner fit: aligned with fitness accountability, recovery, nutrition, gear, studio, or wearable value without medical or guaranteed outcome claims\n- Disclosure copy: sponsored challenge labels, perk status, and coming-soon language are clear before any member-facing promotion\n- Data boundaries: use aggregate first-party demand counts only; no per-user interest export, tracking pixels, ad targeting, or third-party data sharing\n- Destination review: partner links stay empty or inactive until destination safety, privacy, support, and store-policy review are complete\n- Reporting readiness: campaign results should use aggregate challenge joins, member reach, referral joins, and feature submissions only\n- Support handoff: define support ownership, refund boundaries, complaint handling, and data deletion/privacy escalation before launch\n\nThis is a partner terms readiness brief only. Do not add partner links, tracking pixels, ad targeting, affiliate payouts, commissions, revenue-share, purchases, entitlements, discounts, coupons, third-party data sharing, medical claims, guaranteed outcomes, or paid-access claims until partner terms, privacy review, support handoff, and store/entitlement QA are complete.`;
  const partnerContractReadinessCopy = `Rise With The Tribe Partner Contract Readiness Kit:\n\nPilot theme: ${topPartnerPerk?.title || 'Aligned member perk'}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nContract checklist:\n- Partner identity, offer owner, support owner, and escalation contact are known before any member-facing promise\n- Written terms define disclosure wording, fulfillment scope, complaint handling, refund boundaries, and data deletion/privacy escalation\n- Reporting uses aggregate first-party demand, challenge joins, member reach, referral joins, and feature submissions only\n- Destination, coupon, discount, affiliate, and partner-link behavior stays off until legal, privacy, store, and support review pass\n- No third-party data sharing, ad targeting, tracking pixels, commissions, payouts, discounts, coupons, purchases, or entitlement changes are created from this app surface\n\nThis is a partner contract readiness brief only. Do not create partner links, tracking pixels, ad targeting, affiliate payouts, commissions, revenue-share, purchases, entitlements, discounts, coupons, third-party data sharing, medical claims, guaranteed outcomes, paid-access claims, or fulfillment promises.`;
  const partnerCampaignRetrospectiveCopy = `Rise With The Tribe Partner Campaign Retrospective Kit:\n\nPilot theme reviewed: ${topPartnerPerk?.title || 'Aligned member perk'}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\nOpen partner-pilot applications: ${partnerApplicationCount}\nOpen perk claims: ${perkClaimCount}\n\nManual retrospective prompts:\n[ ] Which aggregate app signal moved after the sponsor pilot: challenge joins, member reach, referral joins, perk claims, Feature Me submissions, or support notes?\n[ ] Did the partner value help accountability without medical claims, guaranteed outcomes, random ads, or pressure?\n[ ] Were disclosure wording, support owner, privacy boundaries, and destination safety clear before any member-facing promise?\n[ ] What should change before another sponsor-backed challenge: partner fit, perk category, campaign CTA, claim review, or support handoff?\n[ ] What must stay off until reviewed terms exist: partner links, tracking pixels, ad targeting, payouts, coupons, purchases, entitlements, revenue-share, or third-party exports?\n\nDecision note:\nUse this as a manual, aggregate-only post-pilot readback. Repeat, pause, or revise partner outreach only from first-party app movement and support-safe notes.\n\nThis is a manual Partner Campaign Retrospective Kit only. Do not create partner links, tracking pixels, ad targeting, affiliate payouts, commissions, coupons, discounts, purchases, entitlements, revenue-share, paid-access claims, third-party data exports, payment collection, fulfillment promises, outcome promises, medical claims, auto-message users, scrape/store DMs, or pressure partners or members.`;
  const partnerPerkFulfillmentReadinessCopy = `Rise With The Tribe Partner Perk Fulfillment Readiness Kit:\n\nOpen perk claims: ${perkClaimCount}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual readiness checks:\n[ ] Verify the claim was written from first-party eligibility progress only\n[ ] Confirm partner fit, disclosure wording, support owner, and privacy boundaries\n[ ] Confirm destination safety before any partner link exists\n[ ] Define complaint/refund/escalation ownership before fulfillment\n[ ] Review aggregate demand only; do not export per-user interest lists\n[ ] Keep StoreKit, Play Billing, and entitlement behavior unchanged\n\nThis is a manual partner perk fulfillment readiness kit only. Do not create coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking pixels, ad targeting, third-party data exports, paid-access claims, outcome promises, medical implications, or fulfillment promises before partner terms, privacy review, destination review, and support handoff are complete.`;
  const partnerPerkFulfillmentHandoffCopy = `Rise With The Tribe Partner Perk Fulfillment Handoff Kit:\n\nOpen perk claims: ${perkClaimCount}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual handoff script:\n[ ] Confirm the claim decision is approved for manual follow-up only.\n[ ] Record partner owner, support owner, disclosure wording, destination safety, and complaint/escalation path before any member-facing promise.\n[ ] Send the member a no-promise handoff note: your perk claim is eligible for manual follow-up, and support will confirm partner terms before anything is fulfilled.\n[ ] Keep reporting aggregate only: claim counts, demand category, campaign reach, referral joins, and support outcomes.\n[ ] Recheck privacy, destination, store, and support boundaries before any future coupon, partner link, discount, or fulfillment path exists.\n\nThis is a manual partner perk fulfillment handoff kit only. Do not create coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking pixels, ad targeting, third-party data exports, paid-access claims, payment collection, fulfillment promises, outcome promises, medical implications, auto-message users, scrape/store DMs, or pressure members before partner terms, privacy review, destination review, and support handoff are complete.`;
  const partnerPerkHandoffAuditCopy = `Rise With The Tribe Partner Perk Handoff Audit Kit:\n\nOpen perk claims: ${perkClaimCount}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual audit checklist:\n[ ] Confirm the member-facing note stayed no-promise and manual follow-up only.\n[ ] Confirm partner owner, support owner, disclosure wording, destination safety, and complaint/escalation path are recorded outside member chat.\n[ ] Record only aggregate support outcomes: claim count, demand category, response status, and unresolved support risk.\n[ ] Flag any claim that mentions refunds, payments, coupons, discounts, medical results, guaranteed outcomes, or paid access for support review before replying.\n[ ] Keep StoreKit, Play Billing, purchase validation, and entitlement behavior unchanged.\n\nThis is a manual partner perk handoff audit kit only. Do not create coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking pixels, ad targeting, third-party data exports, paid-access claims, payment collection, refunds, fulfillment promises, outcome promises, medical implications, auto-message users, scrape/store DMs, or pressure members before partner terms, privacy review, destination review, and support handoff are complete.`;
  const partnerPerkHandoffAuditDecisionReplyCopy = `Rise With The Tribe Partner Perk Handoff Audit Decision Reply Kit:\n\nOpen partner perk handoff audit records: ${partnerPerkHandoffAuditReviewQueue.length}\nApproved manual audit records: ${approvedPartnerPerkHandoffAuditReviews.length}\nOpen perk claims: ${perkClaimCount}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual audit decision replies:\nAPPROVED FOR MANUAL HANDOFF: This partner perk handoff audit is approved for manual follow-up. Keep the member-facing note no-promise, support-safe, and aggregate-only while coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking, ad targeting, third-party exports, refunds, and fulfillment promises stay off.\n\nWAITING ON HANDOFF REVIEW: This partner perk handoff audit is waiting on manual review. Confirm claim status, partner fit, disclosure wording, support ownership, destination safety, privacy boundaries, and unresolved support risk before any follow-up continues.\n\nNOT READY FOR HANDOFF: This partner perk handoff audit is not ready yet. Resolve missing eligibility proof, unclear support ownership, unsafe fulfillment expectations, privacy or destination risk, refund/payment confusion, or aggregate evidence gaps before moving forward.\n\nDECLINED FOR HANDOFF: This partner perk handoff audit is declined for now. Keep the decision grounded in first-party claim evidence, partner-readiness notes, support boundaries, and no-pressure member communication.\n\nThis is a manual Partner Perk Handoff Audit Decision Reply Kit only. Do not create coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking pixels, ad targeting, third-party data exports, paid-access claims, collect payment, process refunds, promise fulfillment, promise outcomes, imply medical results, auto-message users, scrape/store DMs, or pressure members.`;
  const partnerPerkSupportEscalationCopy = `Rise With The Tribe Partner Perk Support Escalation Kit:\n\nOpen perk claims: ${perkClaimCount}\nOpen partner perk handoff audit records: ${partnerPerkHandoffAuditReviewQueue.length}\nApproved manual audit records: ${approvedPartnerPerkHandoffAuditReviews.length}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nPartner perk support escalation checklist:\n[ ] Assign the first response owner: member support, partner support, marketplace support, privacy/data safety, entitlement QA, finance/refund policy, partner terms owner, or product owner.\n[ ] Classify severity as information request, eligibility confusion, claim status mismatch, handoff concern, refund/payment confusion, privacy concern, unsafe partner destination, fulfillment expectation, or policy escalation.\n[ ] Use approved response language saying partner perk support escalation is not live fulfillment, not coupon delivery, not refund processing, not payment collection, and not entitlement approval.\n[ ] Keep escalation notes aggregate or first-party only; do not export private member activity, per-user interest lists, payment details, purchase tokens, support transcripts, off-platform messages, or screenshots with sensitive data.\n[ ] Route unresolved cases to claim admin review, fulfillment readiness, fulfillment handoff, handoff audit, partner terms review, marketplace support, privacy/data safety, or entitlement QA before any member-facing promise.\n\nThis is a manual partner perk support escalation kit only. Do not provide live perk fulfillment, create coupons, create partner links, process refunds, collect payment details, create payouts, create discounts, create purchases, write entitlements, create affiliate rewards, add tracking pixels, use ad targeting, export third-party data, expose private member logs, scrape/store DMs, auto-message users, promise fulfillment, imply paid access is live, promise outcomes, imply medical results, or pressure members.`;
  const partnerPerkDecisionReplyCopy = `Rise With The Tribe Partner Perk Admin Decision Reply Kit:\n\nOpen perk claims: ${perkClaimCount}\nTop demand: ${topLabel} (${topDemand})\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual decision replies:\nAPPROVED FOR MANUAL FOLLOW-UP: Your partner perk request is eligible for manual follow-up. We are checking partner fit, disclosure wording, support ownership, privacy boundaries, and destination safety before anything is fulfilled.\n\nWAITING ON PARTNER TERMS: Your request is eligible, but the partner terms and support path are not ready yet. We will keep it in review until terms, privacy, destination safety, and support ownership are clear.\n\nNOT READY YET: Your request is still in review because the claim needs clearer first-party eligibility proof or fulfillment readiness. Keep logging honestly and watch your claim status in profile.\n\nDECLINED FOR NOW: We cannot move this request forward right now. This may be because partner fit, eligibility proof, support ownership, privacy, destination safety, or fulfillment readiness is not strong enough yet.\n\nThis is a manual partner perk decision reply kit only. Do not create coupons, partner links, payouts, discounts, purchases, entitlements, affiliate rewards, tracking pixels, ad targeting, third-party data exports, paid-access claims, outcome promises, medical implications, or fulfillment promises.`;
  const partnerCampaignObjectionReplyCopy = `Rise With The Tribe Partner Campaign Objection Reply Kit:\n\nPilot theme: ${topPartnerPerk?.title || 'Aligned member perk'}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual replies:\nQ: Are partner perks or sponsor campaigns live yet?\nA: Not yet. We are collecting first-party member demand and reviewing partner fit before any sponsor pilot goes live. Partner links, tracking, payouts, purchases, and entitlements stay off until terms, privacy, support, and store QA are complete.\n\nQ: What kind of partner would fit the tribe?\nA: A useful partner should support fitness accountability, recovery, nutrition, gear, studio access, or wearable value without medical claims, guaranteed outcomes, random ads, or third-party data sharing.\n\nQ: What should members do now?\nA: Save the perk interest that would actually help you stay consistent, join the weekly challenge, invite one accountability partner, and submit wins with consent so we can prove value before pitching sponsors.\n\nThis is a manual partner campaign objection reply kit only. Do not claim partner campaigns are live, add partner links, add tracking pixels, use ad targeting, collect payments, create purchases, create affiliate payouts, create commissions, start revenue-share, write entitlements, offer discounts, share third-party data, promise outcomes, imply medical results, scrape DMs, store inbound DMs, or pressure users.`;
  const partnerCampaignSupportEscalationCopy = `Rise With The Tribe Partner Campaign Support Escalation Kit:\n\nOpen partner-pilot applications: ${partnerApplicationCount}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nPartner campaign support escalation checklist:\n[ ] Assign the first response owner: partner terms owner, member support, partner support, marketplace support, privacy/data safety, entitlement QA, finance/refund policy, moderation, or product owner.\n[ ] Classify severity as information request, sponsor-pilot status question, unsafe claim concern, partner destination concern, privacy/data concern, refund/payment confusion, fulfillment expectation, marketplace-policy issue, or support-risk escalation.\n[ ] Use approved response language saying partner campaign support escalation is not a live sponsor campaign, not partner-link activation, not coupon delivery, not payment collection, not payout approval, and not entitlement approval.\n[ ] Keep escalation notes aggregate or first-party only; do not export private member activity, per-user partner interest, payment details, purchase tokens, support transcripts, off-platform messages, or screenshots with sensitive data.\n[ ] Route unresolved cases to partner campaign application review, partner terms readiness, contract readiness, campaign decision replies, campaign retrospective, partner perk support, marketplace support, privacy/data safety, moderation, or entitlement QA before any member-facing promise.\n\nThis is a manual partner campaign support escalation kit only. Do not claim partner campaigns are live, create partner links, add tracking pixels, use ad targeting, collect payments, create purchases, create affiliate payouts, create commissions, start revenue-share, write entitlements, offer discounts, create coupons, share third-party data, export private member logs, scrape/store DMs, auto-message users, promise fulfillment, promise outcomes, imply medical results, or pressure users, partners, or members.`;
  const partnerCampaignDecisionReplyCopy = `Rise With The Tribe Partner Campaign Decision Reply Kit:\n\nOpen partner-pilot applications: ${partnerApplicationCount}\nTop demand: ${topLabel} (${topDemand})\nTotal first-party perk signals: ${partnerDemandTotal}\nCampaign member reach: ${campaignReach}\nReferral joins: ${referralJoins}\n\nManual decision replies:\nAPPROVED FOR MANUAL FOLLOW-UP: Your sponsor-pilot application is approved for manual follow-up. We are reviewing partner fit, disclosure wording, privacy boundaries, destination safety, support ownership, and store-policy alignment before any partner link, perk fulfillment, payout, or member-facing promise goes live.\n\nWAITING ON PARTNER TERMS: Your application has useful first-party demand, but partner terms, support handoff, privacy review, and destination safety need more detail before follow-up.\n\nNOT READY YET: Your application is not ready for sponsor-pilot follow-up yet. Keep collecting first-party demand, clarify the member value, and avoid partner or perk promises until review is stronger.\n\nDECLINED FOR NOW: We cannot move this sponsor-pilot request forward right now. This may be due to partner fit, unclear member value, unsafe claims, privacy risk, destination risk, support gaps, or insufficient first-party demand.\n\nThis is a manual Partner Campaign Decision Reply Kit only. Do not create partner links, tracking pixels, ad targeting, affiliate payouts, commissions, coupons, discounts, purchases, entitlements, revenue-share, paid-access claims, third-party data exports, payment collection, fulfillment promises, outcome promises, medical claims, scraped DMs, stored inbound replies, or pressure partners or members.`;

  return {
    partnerActivationCopy,
    partnerTermsReadinessCopy,
    partnerContractReadinessCopy,
    partnerPerkFulfillmentReadinessCopy,
    partnerPerkFulfillmentHandoffCopy,
    partnerPerkHandoffAuditCopy,
    partnerPerkHandoffAuditDecisionReplyCopy,
    partnerPerkSupportEscalationCopy,
    partnerPerkDecisionReplyCopy,
    partnerCampaignObjectionReplyCopy,
    partnerCampaignSupportEscalationCopy,
    partnerCampaignDecisionReplyCopy,
    partnerCampaignRetrospectiveCopy,
  };
}
