export function buildPartnerRevenuePartnerScreenInputs(screenState) {
  const {
    claimingPartnerPerkId,
    isSubmittingPartnerCampaignApplication,
    partnerCampaignApplicationReviewNotes,
    partnerPerkReviewNotes,
    reviewingPartnerCampaignApplicationId,
    reviewingPartnerPerkClaimId,
    selectedPartnerPerkIds,
    setClaimingPartnerPerkId,
    setIsSavingPartnerPerks,
    setIsSubmittingPartnerCampaignApplication,
    setPartnerCampaignApplicationMessage,
    setPartnerCampaignApplicationReviewQueue,
    setPartnerPerkClaimMessage,
    setPartnerPerkClaimReviewQueue,
    setPartnerPerkClaims,
    setPartnerPerkMessage,
    setReviewingPartnerCampaignApplicationId,
    setReviewingPartnerPerkClaimId,
    setSelectedPartnerPerkIds,
  } = screenState;

  return {
    claimingPartnerPerkId,
    isSubmittingPartnerCampaignApplication,
    partnerCampaignApplicationReviewNotes,
    partnerPerkReviewNotes,
    reviewingPartnerCampaignApplicationId,
    reviewingPartnerPerkClaimId,
    selectedPartnerPerkIds,
    setClaimingPartnerPerkId,
    setIsSavingPartnerPerks,
    setIsSubmittingPartnerCampaignApplication,
    setPartnerCampaignApplicationMessage,
    setPartnerCampaignApplicationReviewQueue,
    setPartnerPerkClaimMessage,
    setPartnerPerkClaimReviewQueue,
    setPartnerPerkClaims,
    setPartnerPerkMessage,
    setReviewingPartnerCampaignApplicationId,
    setReviewingPartnerPerkClaimId,
    setSelectedPartnerPerkIds,
  };
}
