export { buildProfileShareActionInputs } from './profileShareActionInputs';

export function buildProfileScreenDerivedDataInputs({
  stats,
  screenState,
  user,
  myHistory,
}) {
  const {
    accountDeletionReviewQueue,
    campaignPerformanceSummary,
    challengePoints,
    creatorBio,
    creatorCtaUrl,
    creatorEnabled,
    creatorHostingApplicationReviewQueue,
    creatorRevenueShareInterest,
    creatorRevenueShareSummary,
    creatorSpecialty,
    entitlementRecoveryReviewQueue,
    featureReviewQueue,
    featuredSubmissions,
    goalStreak,
    partnerCampaignApplicationReviewQueue,
    partnerPerkClaimReviewQueue,
    partnerPerkSummary,
    profile,
    profileChallenges,
    proTrialSummary,
    referralRewardReviewQueue,
    selectedFrameId,
    selectedPartnerPerkIds,
    storeTestEvidenceLog,
    supportCategory,
    supportReviewQueue,
    validationReadinessMessage,
  } = screenState;

  return {
    accountDeletionReviewQueue,
    campaignPerformanceSummary,
    challengePoints,
    creatorBio,
    creatorCtaUrl,
    creatorEnabled,
    creatorHostingApplicationReviewQueue,
    creatorRevenueShareInterest,
    creatorRevenueShareSummary,
    creatorSpecialty,
    currentStreak: stats.currentStreak,
    daysActive: stats.daysActive,
    entitlementRecoveryReviewQueue,
    featureReviewQueue,
    featuredSubmissions,
    goalStreak,
    monthlyRecap: stats.monthlyRecap,
    myHistory,
    partnerCampaignApplicationReviewQueue,
    partnerPerkClaimReviewQueue,
    partnerPerkSummary,
    profile,
    profileChallenges,
    proTrialSummary,
    rank: stats.rank,
    referralRewardReviewQueue,
    selectedFrameId,
    selectedPartnerPerkIds,
    storeTestEvidenceLog,
    supportCategory,
    supportReviewQueue,
    totalChallengePoints: stats.totalChallengePoints,
    totalWinPoints: stats.totalWinPoints,
    user,
    validationReadinessMessage,
    weeklyReport: stats.weeklyReport,
  };
}
