export function buildStreakComebackSectionProps({
  comebackChallengeInviteCopy,
  copyText,
  currentStreak,
  goalStreak,
  handleStreakRecovery,
  isSavingRecovery,
  proActive,
  recoveryMessage,
  streakRescuePromptCopy,
  weeklyCampaignPrompt,
  yesterdayRecovered,
}) {
  return {
    proActive,
    yesterdayRecovered,
    isSavingRecovery,
    onStreakRecovery: handleStreakRecovery,
    recoveryMessage,
    currentStreak,
    goalStreak,
    streakRescuePromptCopy,
    comebackChallengeInviteCopy,
    weeklyCampaignPrompt,
    copyText,
  };
}

export function buildReferralRewardsSectionProps({
  copyText,
  handleReferralRewardClaim,
  handleReferralRewardClaimReview,
  isAdmin,
  isClaimingReferralReward,
  referralJoins,
  referralLaunchCopy,
  referralRewardClaimMessage,
  referralRewardDecisionReplyCopy,
  referralRewardReviewNotes,
  referralRewardReviewQueue,
  referralRewardSocialProofCopy,
  referralState,
  referralStorySprintCopy,
  reviewingReferralRewardClaimId,
  setReferralRewardReviewNotes,
  unlockedReferralRewardTier,
}) {
  return {
    referralState,
    referralJoins,
    referralLaunchCopy,
    referralStorySprintCopy,
    referralRewardSocialProofCopy,
    unlockedReferralRewardTier,
    onReferralRewardClaim: handleReferralRewardClaim,
    isClaimingReferralReward,
    referralRewardClaimMessage,
    isAdmin,
    referralRewardReviewQueue,
    referralRewardReviewNotes,
    setReferralRewardReviewNotes,
    reviewingReferralRewardClaimId,
    onReferralRewardClaimReview: handleReferralRewardClaimReview,
    referralRewardDecisionReplyCopy,
    copyText,
  };
}
