export function buildProfileEngagementCreatorCopyResult({
  engagementState,
  engagementCampaignCopyData,
  creatorHostingCopyData,
}) {
  const {
    creatorAnalytics,
    proValueNextAction,
    yesterdayKey,
    yesterdayRecovered,
  } = engagementState;
  const {
    valueProofStoryCopy,
    storyPostingChecklistCopy,
    instagramPromptCopy,
    instagramContentCalendarCopy,
    challengePackLaunchCopy,
    challengePackObjectionReplyCopy,
    streakRescuePromptCopy,
    comebackChallengeInviteCopy,
  } = engagementCampaignCopyData;
  const {
    creatorOwnedChallenges,
    creatorLaunchChallenge,
    creatorLaunchLink,
    creatorLaunchCopy,
    creatorBrandedPagePreviewCopy,
    creatorChallengeTemplateDraftCopy,
    creatorProfileCompletionCopy,
    creatorPrivateInviteCopy,
    creatorAgreementPrepCopy,
    creatorSupportHandoffCopy,
    creatorPaidHostingPolicyCopy,
    creatorHostingOfferCopy,
    creatorTermsReadinessCopy,
    creatorPayoutReadinessCopy,
    creatorHostingObjectionReplyCopy,
    creatorHostingDecisionReplyCopy,
    creatorIdentityVerificationPrepCopy,
    creatorLeaderboardPreviewCopy,
    creatorModerationReadinessCopy,
    creatorPaidHostingLaunchGateCopy,
    creatorPaidHostingHoldPlanCopy,
  } = creatorHostingCopyData;

  return {
    challengePackLaunchCopy,
    challengePackObjectionReplyCopy,
    comebackChallengeInviteCopy,
    creatorAnalytics,
    creatorBrandedPagePreviewCopy,
    creatorChallengeTemplateDraftCopy,
    creatorProfileCompletionCopy,
    creatorHostingDecisionReplyCopy,
    creatorIdentityVerificationPrepCopy,
    creatorLeaderboardPreviewCopy,
    creatorModerationReadinessCopy,
    creatorPaidHostingLaunchGateCopy,
    creatorPaidHostingHoldPlanCopy,
    creatorHostingObjectionReplyCopy,
    creatorHostingOfferCopy,
    creatorLaunchChallenge,
    creatorLaunchCopy,
    creatorLaunchLink,
    creatorOwnedChallenges,
    creatorPrivateInviteCopy,
    creatorAgreementPrepCopy,
    creatorSupportHandoffCopy,
    creatorPaidHostingPolicyCopy,
    creatorPayoutReadinessCopy,
    creatorTermsReadinessCopy,
    instagramContentCalendarCopy,
    instagramPromptCopy,
    proValueNextAction,
    storyPostingChecklistCopy,
    streakRescuePromptCopy,
    valueProofStoryCopy,
    yesterdayKey,
    yesterdayRecovered,
  };
}
