export function buildProfileScreenLoadTargets({
  engagementState,
  preferenceState,
  reviewState,
  revenueState,
  setChallengePoints,
  setProfile,
  setProfileChallenges,
  setVisible,
  storeState,
}) {
  return {
    setAccountDeletionReviewQueue: reviewState.setAccountDeletionReviewQueue,
    setCampaignPerformanceSummary: revenueState.setCampaignPerformanceSummary,
    setChallengePoints,
    setCommunityEventInterestSummary: revenueState.setCommunityEventInterestSummary,
    setCreatorBio: revenueState.setCreatorBio,
    setCreatorCtaUrl: revenueState.setCreatorCtaUrl,
    setCreatorEnabled: revenueState.setCreatorEnabled,
    setCreatorBrandedPageReviewQueue: revenueState.setCreatorBrandedPageReviewQueue,
    setCreatorHostingApplicationReviewQueue: revenueState.setCreatorHostingApplicationReviewQueue,
    setCreatorLeaderboardSnapshotReviewQueue: revenueState.setCreatorLeaderboardSnapshotReviewQueue,
    setCreatorPrivateInviteLaunchReviewQueue: revenueState.setCreatorPrivateInviteLaunchReviewQueue,
    setCreatorPaidHostingLaunchGateReviewQueue: revenueState.setCreatorPaidHostingLaunchGateReviewQueue,
    setCreatorRevenueShareInterest: revenueState.setCreatorRevenueShareInterest,
    setCreatorRevenueShareSummary: revenueState.setCreatorRevenueShareSummary,
    setCreatorSpecialty: revenueState.setCreatorSpecialty,
    setCreatorTemplateDraftReviewQueue: revenueState.setCreatorTemplateDraftReviewQueue,
    setPublishedCreatorBrandedPages: revenueState.setPublishedCreatorBrandedPages,
    setApprovedCreatorPrivateInviteLaunches: revenueState.setApprovedCreatorPrivateInviteLaunches,
    setApprovedCreatorPaidHostingLaunchGateReviews: revenueState.setApprovedCreatorPaidHostingLaunchGateReviews,
    setPublishedCreatorChallengeTemplates: revenueState.setPublishedCreatorChallengeTemplates,
    setPublishedCreatorLeaderboardSnapshots: revenueState.setPublishedCreatorLeaderboardSnapshots,
    setEntitlementRecoveryReviewQueue: storeState.setEntitlementRecoveryReviewQueue,
    setFeatureReviewQueue: engagementState.setFeatureReviewQueue,
    setFeatureSubmissions: engagementState.setFeatureSubmissions,
    setFeaturedSubmissions: engagementState.setFeaturedSubmissions,
    setGoalActiveDays: preferenceState.setGoalActiveDays,
    setGoalPoints: preferenceState.setGoalPoints,
    setGoalStreak: preferenceState.setGoalStreak,
    setInstagramHandle: engagementState.setInstagramHandle,
    setApprovedLaunchExperimentReviews: revenueState.setApprovedLaunchExperimentReviews,
    setApprovedWeeklyCampaignReviews: revenueState.setApprovedWeeklyCampaignReviews,
    setLaunchExperimentReviewQueue: revenueState.setLaunchExperimentReviewQueue,
    setPartnerCampaignApplicationReviewQueue: revenueState.setPartnerCampaignApplicationReviewQueue,
    setPartnerPerkClaimReviewQueue: revenueState.setPartnerPerkClaimReviewQueue,
    setPartnerPerkClaims: revenueState.setPartnerPerkClaims,
    setPartnerPerkSummary: revenueState.setPartnerPerkSummary,
    setProfile,
    setProfileChallenges,
    setProTrialSummary: revenueState.setProTrialSummary,
    setReferralRewardReviewQueue: reviewState.setReferralRewardReviewQueue,
    setSelectedCommunityEventInterestIds: revenueState.setSelectedCommunityEventInterestIds,
    setSelectedFrameId: preferenceState.setSelectedFrameId,
    setSelectedPartnerPerkIds: revenueState.setSelectedPartnerPerkIds,
    setSelectedProTrialReasonIds: revenueState.setSelectedProTrialReasonIds,
    setStoreTestEvidenceLog: storeState.setStoreTestEvidenceLog,
    setSupportReviewQueue: reviewState.setSupportReviewQueue,
    setVisible,
    setWeeklyCampaignReviewQueue: revenueState.setWeeklyCampaignReviewQueue,
  };
}
