export function buildStreakComebackSectionProps({
  comebackChallengeInviteCopy,
  copyText,
  currentStreak,
  goalStreak,
  handleStreakRecovery,
  isSavingRecovery,
  proActive,
  recoveryMessage,
  streakRescuePromptCopy,
  weeklyCampaignPrompt,
  yesterdayRecovered,
}) {
  return {
    proActive,
    yesterdayRecovered,
    isSavingRecovery,
    onStreakRecovery: handleStreakRecovery,
    recoveryMessage,
    currentStreak,
    goalStreak,
    streakRescuePromptCopy,
    comebackChallengeInviteCopy,
    weeklyCampaignPrompt,
    copyText,
  };
}

export function buildReferralRewardsSectionProps({
  appReferralSignups,
  approvedReferralRewardHandoffAuditReviews,
  copyText,
  handleReferralRewardClaim,
  handleReferralRewardClaimReview,
  handleReferralRewardHandoffAuditReviewDecision,
  handleReferralRewardHandoffAuditReviewSubmit,
  isAdmin,
  isClaimingReferralReward,
  isSubmittingReferralRewardHandoffAuditReview,
  referralJoins,
  referralLaunchCopy,
  referralRewardClaimMessage,
  referralRewardDecisionReplyCopy,
  referralRewardSupportEscalationCopy,
  referralRewardHandoffAuditDecisionReplyCopy,
  referralRewardHandoffAuditReviewMessage,
  referralRewardHandoffAuditReviewNotes,
  referralRewardHandoffAuditReviewQueue,
  referralRewardReviewNotes,
  referralRewardReviewQueue,
  referralRewardSocialProofCopy,
  referralState,
  referralStorySprintCopy,
  reviewingReferralRewardHandoffAuditReviewId,
  reviewingReferralRewardClaimId,
  setReferralRewardHandoffAuditReviewNotes,
  setReferralRewardReviewNotes,
  unlockedReferralRewardTier,
  user,
}) {
  const appInviteLink = user?.uid
    ? `https://tribechallengetracker.web.app?ref=${encodeURIComponent(user.uid)}`
    : '';

  return {
    appInviteLink,
    appReferralSignups,
    approvedReferralRewardHandoffAuditReviews,
    referralState,
    referralJoins,
    referralLaunchCopy,
    referralStorySprintCopy,
    referralRewardSocialProofCopy,
    unlockedReferralRewardTier,
    onReferralRewardClaim: handleReferralRewardClaim,
    isClaimingReferralReward,
    referralRewardClaimMessage,
    referralRewardHandoffAuditReviewMessage,
    referralRewardHandoffAuditReviewNotes,
    referralRewardHandoffAuditReviewQueue,
    isAdmin,
    isSubmittingReferralRewardHandoffAuditReview,
    referralRewardReviewQueue,
    referralRewardReviewNotes,
    setReferralRewardHandoffAuditReviewNotes,
    setReferralRewardReviewNotes,
    reviewingReferralRewardHandoffAuditReviewId,
    reviewingReferralRewardClaimId,
    onReferralRewardClaimReview: handleReferralRewardClaimReview,
    onReferralRewardHandoffAuditReviewDecision: handleReferralRewardHandoffAuditReviewDecision,
    onReferralRewardHandoffAuditReviewSubmit: handleReferralRewardHandoffAuditReviewSubmit,
    referralRewardDecisionReplyCopy,
    referralRewardSupportEscalationCopy,
    referralRewardHandoffAuditDecisionReplyCopy,
    copyText,
  };
}
