export const PROFILE_PARITY_CONTRACT_LABELS = [
  'Store Launch Readiness',
  'COPY STORE LAUNCH CHECKLIST',
  'CREDENTIALS PENDING',
  'CHALLENGE PACK LAUNCH KIT',
  'COPY PACK LAUNCH COPY',
  'Copy for paid-pack demand before store launch',
  'CHALLENGE PACK OBJECTION REPLY KIT',
  'COPY PACK REPLIES',
  'Campaign Performance Board',
  'COPY CAMPAIGN BOARD COPY',
  'weekly campaign engine summary',
  'Weekly Campaign Scheduler',
  'COPY WEEKLY CAMPAIGN COPY',
  'Creator/admin Instagram cadence prompt',
  'STORE CREDENTIAL SETUP KIT',
  'COPY CREDENTIAL SETUP KIT',
  'CHECK VALIDATION READINESS',
  'SUPPORT REFUND READINESS KIT',
  'COPY SUPPORT KIT',
  'PAID LAUNCH DECISION GATE',
  'COPY LAUNCH DECISION',
  'SANDBOX PURCHASE TEST PLAN',
  'COPY SANDBOX TEST PLAN',
  'LAUNCH RETROSPECTIVE KIT',
  'COPY RETROSPECTIVE KIT',
  'Manual first-party review after a campaign push',
  'STORE LISTING COPY KIT',
  'COPY STORE LISTING',
  'STORE REVIEW SUBMISSION KIT',
  'COPY REVIEW NOTES',
  'Reviewer notes and permission checklist',
  'STORE REVIEW EVIDENCE PACK',
  'COPY REVIEW EVIDENCE PACK',
  'Reviewer proof package from release checks',
  'STORE REVIEW RESPONSE KIT',
  'COPY REVIEW RESPONSE',
  'Reviewer follow-up and rejection reply checklist',
  'DATA SAFETY DISCLOSURE KIT',
  'COPY DATA SAFETY',
  'App Privacy and Play Data Safety draft',
  'LAUNCH EXPERIMENT KIT',
  'LAUNCH EXPERIMENT SCORECARD',
  'COPY EXPERIMENT SCORECARD',
  'First-party signal readout for the next test',
  'RELEASE QA CHECKLIST',
  'COPY RELEASE QA CHECKLIST',
  'Manual cross-platform guardrails before launch',
  'reviewedAt',
  'ENTITLEMENT RECOVERY REVIEW QUEUE',
  'Manual entitlement recovery review note',
  'do not write entitlements',
  'storeTestPurchaseEvidence',
  'STORE TEST PURCHASE EVIDENCE LOG',
  'Sandbox and license-test proof before paid launch',
  'Manual store test evidence review note',
  'NEEDS REVIEW',
  'must not write entitlements',
  'RESTORE FIRST',
  'LEARN ONLY',
];
