import {
  CANCELLATION_FEEDBACK_ITEMS,
  LAPSED_MEMBER_WINBACK_ITEMS,
  POLICY_LINKS,
  RENEWAL_RECOVERY_ITEMS,
  STORE_DEMO_ACCOUNT_ITEMS,
  STORE_EVIDENCE_ARCHIVE_ITEMS,
  STORE_EVIDENCE_EXPORT_TEMPLATE_ITEMS,
  STORE_LAUNCH_DRY_RUN_ITEMS,
  STORE_REVIEW_PACK_ITEMS,
  STORE_REVIEW_EVIDENCE_GAP_DECISION_ITEMS,
  STORE_REVIEW_EVIDENCE_GAP_TRIAGE_ITEMS,
  STORE_REVIEW_POLICY_LINK_QA_ITEMS,
  STORE_REVIEW_REJECTION_ROOT_CAUSE_ITEMS,
  STORE_REVIEW_RESUBMISSION_ITEMS,
  STORE_REVIEWER_REPLY_PACKET_ITEMS,
  STORE_REVIEW_METADATA_DIFF_ITEMS,
  STORE_REVIEW_DATA_SAFETY_ALIGNMENT_ITEMS,
  STORE_REVIEW_PERMISSION_COPY_CHECK_ITEMS,
  STORE_REVIEW_DEMO_ACCESS_QA_ITEMS,
  STORE_REVIEW_SUPPORT_HANDOFF_QA_ITEMS,
  STORE_REVIEW_EVIDENCE_PACKET_INDEX_ITEMS,
  STORE_REVIEW_FINAL_SIGNOFF_ITEMS,
  STORE_REVIEW_CONSOLE_DRAFT_QA_ITEMS,
  STORE_REVIEW_SUBMISSION_HOLD_REASONS_ITEMS,
  STORE_SCREENSHOT_QA_ITEMS,
  STORE_TEST_PURCHASE_SESSION_PREP_ITEMS,
} from './profileConstants';
import { buildStoreLifecycleCopy } from './storeLifecycleCopy';

export function buildProfileStoreLifecycleSupportData({
  activeChallengePackCount,
  challengePackCount,
  currentStreak,
  entitlementRecoveryReviewCount,
  monetizationSignalTotal,
  paidLaunchDecisionItemCount,
  paidLaunchDecisionStatus,
  paidLaunchReadyCount,
  proActive,
  proTrialDemandTotal,
  recommendedRevenuePath,
  referralJoins,
  storeCatalog,
  storeTestEvidenceSummary,
  supportReviewCount,
  validationReadinessConfirmed,
  weeklyCampaignPrompt,
}) {
  return buildStoreLifecycleCopy({
    renewalRecoveryItems: RENEWAL_RECOVERY_ITEMS,
    cancellationFeedbackItems: CANCELLATION_FEEDBACK_ITEMS,
    lapsedMemberWinbackItems: LAPSED_MEMBER_WINBACK_ITEMS,
    storeLaunchDryRunItems: STORE_LAUNCH_DRY_RUN_ITEMS,
    storeTestPurchaseSessionPrepItems: STORE_TEST_PURCHASE_SESSION_PREP_ITEMS,
    storeEvidenceArchiveItems: STORE_EVIDENCE_ARCHIVE_ITEMS,
    storeEvidenceExportTemplateItems: STORE_EVIDENCE_EXPORT_TEMPLATE_ITEMS,
    storeDemoAccountItems: STORE_DEMO_ACCOUNT_ITEMS,
    storeScreenshotQaItems: STORE_SCREENSHOT_QA_ITEMS,
    storeReviewPackItems: STORE_REVIEW_PACK_ITEMS,
    storeReviewEvidenceGapDecisionItems: STORE_REVIEW_EVIDENCE_GAP_DECISION_ITEMS,
    storeReviewEvidenceGapTriageItems: STORE_REVIEW_EVIDENCE_GAP_TRIAGE_ITEMS,
    storeReviewPolicyLinkQaItems: STORE_REVIEW_POLICY_LINK_QA_ITEMS,
    storeReviewRejectionRootCauseItems: STORE_REVIEW_REJECTION_ROOT_CAUSE_ITEMS,
    storeReviewerReplyPacketItems: STORE_REVIEWER_REPLY_PACKET_ITEMS,
    storeReviewMetadataDiffItems: STORE_REVIEW_METADATA_DIFF_ITEMS,
    storeReviewDataSafetyAlignmentItems: STORE_REVIEW_DATA_SAFETY_ALIGNMENT_ITEMS,
    storeReviewPermissionCopyCheckItems: STORE_REVIEW_PERMISSION_COPY_CHECK_ITEMS,
    storeReviewDemoAccessQaItems: STORE_REVIEW_DEMO_ACCESS_QA_ITEMS,
    storeReviewSupportHandoffQaItems: STORE_REVIEW_SUPPORT_HANDOFF_QA_ITEMS,
    storeReviewEvidencePacketIndexItems: STORE_REVIEW_EVIDENCE_PACKET_INDEX_ITEMS,
    storeReviewFinalSignoffItems: STORE_REVIEW_FINAL_SIGNOFF_ITEMS,
    storeReviewConsoleDraftQaItems: STORE_REVIEW_CONSOLE_DRAFT_QA_ITEMS,
    storeReviewSubmissionHoldReasonsItems: STORE_REVIEW_SUBMISSION_HOLD_REASONS_ITEMS,
    storeReviewResubmissionItems: STORE_REVIEW_RESUBMISSION_ITEMS,
    storeCatalog,
    policyLinks: POLICY_LINKS,
    weeklyCampaignPrompt,
    currentStreak,
    referralJoins,
    monetizationSignalTotal,
    proTrialDemandTotal,
    recommendedRevenuePath,
    validationReadinessConfirmed,
    proActive,
    activeChallengePackCount,
    challengePackCount,
    entitlementRecoveryReviewCount,
    supportReviewCount,
    storeTestEvidenceSummary,
    paidLaunchDecisionStatus,
    paidLaunchReadyCount,
    paidLaunchDecisionItemCount,
  });
}
