export function buildProfileUtilitySectionProps({
  disableReminder,
  displayNameDraft,
  displayNameMessage,
  handleReminder,
  handleDisplayNameSave,
  isSavingDisplayName,
  onSignOut,
  profile,
  reminderError,
  reminderLabel,
  setDisplayNameDraft,
  user,
}) {
  return {
    displayNameDraft,
    displayNameMessage,
    isSavingDisplayName,
    reminderLabel,
    reminderError,
    onDisplayNameSave: handleDisplayNameSave,
    onReminder: handleReminder,
    onReminderOff: disableReminder,
    profile,
    setDisplayNameDraft,
    user,
    onSignOut,
  };
}

export function buildSupportAccountSectionProps({
  accountDeletionDecisionReplyCopy,
  accountDeletionRequested,
  accountDeletionReviewNotes,
  accountDeletionReviewQueue,
  contentReportQueue,
  contentReportReviewNotes,
  copyText,
  deletionRequestMessage,
  handleAccountDeletionRequest,
  handleAccountDeletionReview,
  handleContentReportReview,
  handleSupportRequest,
  handleSupportRequestReview,
  isAdmin,
  isRequestingDeletion,
  isSubmittingSupport,
  profile,
  reviewingAccountDeletionRequestId,
  reviewingContentReportId,
  reviewingSupportRequestId,
  setAccountDeletionReviewNotes,
  setContentReportReviewNotes,
  setSupportCategory,
  setSupportMessage,
  setSupportReviewNotes,
  supportCategory,
  supportDecisionReplyCopy,
  supportMessage,
  supportReviewNotes,
  supportReviewQueue,
  supportStatusMessage,
}) {
  return {
    supportCategory,
    setSupportCategory,
    supportMessage,
    setSupportMessage,
    isSubmittingSupport,
    onSupportRequest: handleSupportRequest,
    supportStatusMessage,
    isAdmin,
    supportReviewQueue,
    supportReviewNotes,
    setSupportReviewNotes,
    onSupportRequestReview: handleSupportRequestReview,
    reviewingSupportRequestId,
    supportDecisionReplyCopy,
    copyText,
    contentReportQueue,
    contentReportReviewNotes,
    setContentReportReviewNotes,
    onContentReportReview: handleContentReportReview,
    reviewingContentReportId,
    accountDeletionRequested,
    onAccountDeletionRequest: handleAccountDeletionRequest,
    isRequestingDeletion,
    deletionRequestMessage,
    accountDeletionReviewQueue,
    accountDeletionReviewNotes,
    setAccountDeletionReviewNotes,
    onAccountDeletionReview: handleAccountDeletionReview,
    reviewingAccountDeletionRequestId,
    profile,
    accountDeletionDecisionReplyCopy,
  };
}

export function buildProfileScreenSupportSectionsProps(model, { onSignOut }) {
  return {
    supportAccountSectionProps: buildSupportAccountSectionProps(model),
    utilitySectionProps: buildProfileUtilitySectionProps({
      ...model,
      onSignOut,
    }),
  };
}
