export function buildProfileWeeklyCampaignDerivedResult({
  coreData,
  experimentData,
  engagementData,
}) {
  const {
    campaignPerformanceCopy,
    campaignSchedulerCopy,
    weeklyCampaignLaunchCardCopy,
    weeklyCampaignLaunchCopyQaCopy,
    weeklyCampaignPreflightCopy,
    weeklyCampaignReviewCopy,
    weeklyCampaignStoryboardCopy,
    dmKeywordCopy,
  } = coreData;
  const {
    launchExperiments,
    recommendedLaunchExperiment,
    weeklyCampaignExperimentBriefCopy,
    launchExperimentCopy,
    launchExperimentScorecardCopy,
    experimentScore,
    experimentScoreLabel,
    launchQaChecklistCopy,
    launchRetrospectiveCopy,
    launchRetrospectiveReadinessScriptCopy,
  } = experimentData;
  const {
    weeklyCampaignCommentReplyCopy,
    weeklyCampaignCountdownStoryCopy,
    weeklyCampaignStartDayStoryCopy,
    weeklyCampaignMidweekCheckInStoryCopy,
    weeklyCampaignWeekendPushStoryCopy,
    weeklyCampaignCompletionRecapStoryCopy,
    weeklyCampaignNextWeekTeaserStoryCopy,
    weeklyCampaignPartnerPerkTeaserStoryCopy,
    weeklyCampaignStoryPollCopy,
    weeklyCampaignPollReviewCopy,
    weeklyCampaignLiveQaCopy,
    weeklyCampaignLiveRecapCopy,
    weeklyCampaignFaqCarouselCopy,
    weeklyCampaignCaptionBankCopy,
    weeklyCampaignCollabCopyCards,
  } = engagementData;

  return {
    campaignPerformanceCopy,
    campaignSchedulerCopy,
    dmKeywordCopy,
    experimentScore,
    experimentScoreLabel,
    launchExperimentCopy,
    launchExperimentScorecardCopy,
    launchExperiments,
    launchQaChecklistCopy,
    launchRetrospectiveCopy,
    launchRetrospectiveReadinessScriptCopy,
    recommendedLaunchExperiment,
    weeklyCampaignCaptionBankCopy,
    weeklyCampaignCollabCopyCards,
    weeklyCampaignCommentReplyCopy,
    weeklyCampaignCompletionRecapStoryCopy,
    weeklyCampaignCountdownStoryCopy,
    weeklyCampaignExperimentBriefCopy,
    weeklyCampaignFaqCarouselCopy,
    weeklyCampaignLaunchCardCopy,
    weeklyCampaignLaunchCopyQaCopy,
    weeklyCampaignLiveQaCopy,
    weeklyCampaignLiveRecapCopy,
    weeklyCampaignMidweekCheckInStoryCopy,
    weeklyCampaignNextWeekTeaserStoryCopy,
    weeklyCampaignPartnerPerkTeaserStoryCopy,
    weeklyCampaignPollReviewCopy,
    weeklyCampaignPreflightCopy,
    weeklyCampaignReviewCopy,
    weeklyCampaignStartDayStoryCopy,
    weeklyCampaignStoryboardCopy,
    weeklyCampaignStoryPollCopy,
    weeklyCampaignWeekendPushStoryCopy,
  };
}
