import { buildProfileStoreBillingSupportData } from './profileStoreBillingSupportData';
import { buildProfileStoreLifecycleSupportData } from './profileStoreLifecycleSupportData';
import { buildStoreSupportCopyCards } from './storeSupportCopyCards';

export function buildProfileStoreSupportCardData({
  activeChallengePackCount,
  challengePackCount,
  currentStreak,
  entitlementRecoveryReviewCount,
  monetizationSignalTotal,
  paidLaunchDecisionItemCount,
  paidLaunchDecisionStatus,
  paidLaunchReadyCount,
  proActive,
  proTrialDemandTotal,
  recommendedRevenuePath,
  referralJoins,
  storeCatalog,
  storePackCount,
  storeSubscriptionCount,
  storeTestEvidenceSummary,
  subscriptionManagementGuidanceCopy,
  supportReviewCount,
  validationReadinessConfirmed,
  weeklyCampaignPrompt,
}) {
  const {
    billingSupportEscalationCopy,
    entitlementRecoveryDecisionReplyCopy,
  } = buildProfileStoreBillingSupportData({
    activeChallengePackCount,
    challengePackCount,
    entitlementRecoveryReviewCount,
    proActive,
    storeCatalog,
    storePackCount,
    storeSubscriptionCount,
    storeTestEvidenceSummary,
    validationReadinessConfirmed,
  });
  const {
    renewalRecoveryCopy,
    cancellationFeedbackCopy,
    lapsedMemberWinbackCopy,
    storeLaunchDryRunCopy,
    storeTestPurchaseSessionPrepCopy,
    storeEvidenceArchiveCopy,
    storeEvidenceExportTemplateCopy,
    storeDemoAccountCopy,
    storeScreenshotQaCopy,
    storeReviewPackCopy,
    storeReviewResponseCopy,
    storeReviewEvidenceGapDecisionCopy,
    storeReviewEvidenceGapTriageCopy,
    storeReviewPolicyLinkQaCopy,
    storeReviewRejectionRootCauseCopy,
    storeReviewerReplyPacketCopy,
    storeReviewMetadataDiffCopy,
    storeReviewDataSafetyAlignmentCopy,
    storeReviewPermissionCopyCheckCopy,
    storeReviewResubmissionCopy,
  } = buildProfileStoreLifecycleSupportData({
    activeChallengePackCount,
    challengePackCount,
    currentStreak,
    entitlementRecoveryReviewCount,
    monetizationSignalTotal,
    paidLaunchDecisionItemCount,
    paidLaunchDecisionStatus,
    paidLaunchReadyCount,
    proActive,
    proTrialDemandTotal,
    recommendedRevenuePath,
    referralJoins,
    storeCatalog,
    supportReviewCount,
    storeTestEvidenceSummary,
    validationReadinessConfirmed,
    weeklyCampaignPrompt,
  });
  const storeSupportCopyCards = buildStoreSupportCopyCards({
    subscriptionManagementGuidanceCopy,
    billingSupportEscalationCopy,
    renewalRecoveryCopy,
    cancellationFeedbackCopy,
    lapsedMemberWinbackCopy,
    storeLaunchDryRunCopy,
    storeTestPurchaseSessionPrepCopy,
    storeEvidenceArchiveCopy,
    storeEvidenceExportTemplateCopy,
    storeDemoAccountCopy,
    storeScreenshotQaCopy,
    storeReviewPackCopy,
    storeReviewResponseCopy,
    storeReviewEvidenceGapDecisionCopy,
    storeReviewEvidenceGapTriageCopy,
    storeReviewPolicyLinkQaCopy,
    storeReviewRejectionRootCauseCopy,
    storeReviewerReplyPacketCopy,
    storeReviewMetadataDiffCopy,
    storeReviewDataSafetyAlignmentCopy,
    storeReviewPermissionCopyCheckCopy,
    storeReviewResubmissionCopy,
  });

  return {
    billingSupportEscalationCopy,
    entitlementRecoveryDecisionReplyCopy,
    lapsedMemberWinbackCopy,
    renewalRecoveryCopy,
    storeSupportCopyCards,
    storeTestPurchaseSessionPrepCopy,
    storeScreenshotQaCopy,
  };
}
