export function buildReferralRewardCopy({
  referralState,
  referralJoins,
  totalWinPoints,
  currentStreak,
  daysActive,
  unlockedReferralRewardTier,
  referralRewardReviewQueue,
}) {
  const referralLaunchCopy = referralState.next
    ? `Rise With The Tribe Referral Launch Kit:\n\nTarget tier: ${referralState.next.label}\nReferral progress: ${referralJoins}/${referralState.next.target} attributed challenge joins\nRemaining: ${referralState.remainingToNext}\nCurrent tribe momentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nLaunch checklist:\n[ ] Pick one active challenge or this week's campaign as the invite destination.\n[ ] Share one honest proof point: logged session, streak, badge, challenge card, or comeback note.\n[ ] Invite one accountability partner to join the challenge and log their first session.\n[ ] Use the invite link from the app so attributed challenge joins can count toward the ladder.\n[ ] Review progress from first-party challenge joins only before talking about rewards.\n\nCaption draft:\nI am ${referralState.remainingToNext} challenge join${referralState.remainingToNext === 1 ? '' : 's'} away from ${referralState.next.label}. Join a challenge with me, log your first session, and tag @risewiththetribe when you start.\n\nManual comment reply:\nStart with one challenge, log one honest session, and bring one accountability partner with you. The tribe grows through completed joins, not link clicks.\n\nThis is a manual Referral Launch Kit only. Do not count link opens, grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, imply medical results, scrape DMs, store inbound replies, add tracking pixels, pressure invites, or claim reward fulfillment before admin review.`
    : `Rise With The Tribe Referral Launch Kit:\n\nAll current referral tiers are unlocked.\nReferral progress: ${referralJoins} attributed challenge joins\nCurrent tribe momentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nLaunch checklist:\n[ ] Pick one active challenge or this week's campaign as the invite destination.\n[ ] Share one honest proof point: logged session, streak, badge, challenge card, or comeback note.\n[ ] Invite one accountability partner to join the challenge and log their first session.\n[ ] Use the invite link from the app so attributed challenge joins can count toward the ladder.\n[ ] Review progress from first-party challenge joins only before talking about rewards.\n\nCaption draft:\nAll current referral tiers are unlocked, but the tribe still grows one invite at a time. Join a challenge with me, bring one accountability partner, and tag @risewiththetribe when you start.\n\nManual comment reply:\nStart with one challenge, log one honest session, and bring one accountability partner with you. The tribe grows through completed joins, not link clicks.\n\nThis is a manual Referral Launch Kit only. Do not count link opens, grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, imply medical results, scrape DMs, store inbound replies, add tracking pixels, pressure invites, or claim reward fulfillment before admin review.`;

  const referralStorySprintCopy = referralState.next
    ? `Rise With The Tribe Referral Story Sprint Kit:\n\nNext tier: ${referralState.next.label}\nReferral progress: ${referralJoins}/${referralState.next.target} challenge joins\nRemaining: ${referralState.remainingToNext}\nMomentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nStory sprint:\n[ ] Frame 1: "I am ${referralState.remainingToNext} challenge join${referralState.remainingToNext === 1 ? '' : 's'} away from ${referralState.next.label}."\n[ ] Frame 2: show today's logged session, challenge card, or streak proof\n[ ] Frame 3: invite one accountability partner to join a challenge and log their first session\n[ ] Frame 4: tag @risewiththetribe and ask them to start today\n\nReel hook: "Bring one person with you. The tribe gets stronger when we log together."\n\nThis is a manual referral story sprint only. Do not count link opens, grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, or imply medical results.`
    : `Rise With The Tribe Referral Story Sprint Kit:\n\nAll current referral tiers are unlocked.\nReferral progress: ${referralJoins} challenge joins\nMomentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nStory sprint:\n[ ] Frame 1: celebrate the current referral ladder being complete\n[ ] Frame 2: show today's logged session, challenge card, or streak proof\n[ ] Frame 3: invite one accountability partner to join a challenge and log their first session\n[ ] Frame 4: tag @risewiththetribe and ask them to start today\n\nReel hook: "Bring one person with you. The tribe gets stronger when we log together."\n\nThis is a manual referral story sprint only. Do not count link opens, grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, or imply medical results.`;

  const referralRewardSocialProofCopy = unlockedReferralRewardTier
    ? `Rise With The Tribe Referral Reward Social Proof Kit:\n\nUnlocked tier: ${unlockedReferralRewardTier.label}\nReferral progress: ${referralJoins} attributed challenge joins\nRecognition angle: ${unlockedReferralRewardTier.reward}\nMomentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nStory caption:\nI unlocked ${unlockedReferralRewardTier.label} by bringing people into the challenge loop with me. If you need accountability, join a challenge, log your first session, and tag @risewiththetribe when you start.\n\nCarousel beats:\n[ ] Slide 1: referral tier unlocked\n[ ] Slide 2: show challenge/streak proof from the app\n[ ] Slide 3: thank the accountability partners who joined\n[ ] Slide 4: invite one new person into the next challenge\n\nThis is manual social proof copy only. Do not grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, imply medical results, or claim fulfillment before admin review.`
    : `Rise With The Tribe Referral Reward Social Proof Kit:\n\nNo referral reward tier is unlocked yet.\nReferral progress: ${referralJoins} attributed challenge joins\nNext tier: ${referralState.next?.label || 'Referral tier'} at ${referralState.next?.target || 1} join${(referralState.next?.target || 1) === 1 ? '' : 's'}\nMomentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active\n\nStory caption:\nI am building consistency with Rise With The Tribe and inviting one accountability partner into the challenge loop. Join a challenge, log your first session, and tag @risewiththetribe when you start.\n\nCarousel beats:\n[ ] Slide 1: next referral tier target\n[ ] Slide 2: show challenge/streak proof from the app\n[ ] Slide 3: invite one accountability partner\n[ ] Slide 4: point them back to the next challenge\n\nThis is manual social proof copy only. Do not grant rewards, write referral state, create payouts, create affiliate rewards, unlock entitlements, imply paid access is live, promise outcomes, imply medical results, or claim fulfillment before admin review.`;

  const referralRewardDecisionReplyCopy = `Rise With The Tribe Referral Reward Decision Reply Kit:

Open referral reward claims: ${referralRewardReviewQueue.length}
Referral progress: ${referralJoins} attributed challenge joins
Highest unlocked tier: ${unlockedReferralRewardTier?.label || 'None yet'}
Next tier: ${referralState.next?.label || 'Ladder clear'}
Current tribe momentum: ${totalWinPoints} pts \u00b7 ${currentStreak}d streak \u00b7 ${daysActive} days active

Manual decision replies:
APPROVED FOR MANUAL RECOGNITION: Your referral reward claim is approved for manual recognition. We are checking meaningful challenge joins, duplicate activity, recognition copy, consent-safe public wording, and support notes before any thank-you or future perk fulfillment is handled outside the app.

WAITING ON REVIEW: Your referral reward claim is still waiting on manual review. We need to confirm attributed challenge joins, duplicate checks, and recognition wording before the claim can move forward.

NOT READY YET: Your referral reward claim is not ready yet. Keep inviting accountability partners into real challenge joins and log honestly; link opens, screenshots, or unverified invites do not count as completed referral progress.

DECLINED FOR NOW: We cannot move this referral reward claim forward right now. This may be due to incomplete challenge joins, duplicate or unclear referral activity, missing review context, unsafe fulfillment expectations, or claim timing.

This is a manual Referral Reward Decision Reply Kit only. Do not grant Pro, write entitlements, unlock challenge packs, create discounts, create payouts, create purchases, create affiliate rewards, write referral state, count link opens, claim fulfillment, promise outcomes, imply medical results, scrape DMs, store inbound replies, add tracking pixels, auto-message users, or pressure members.`;

  return {
    referralLaunchCopy,
    referralStorySprintCopy,
    referralRewardSocialProofCopy,
    referralRewardDecisionReplyCopy,
  };
}
