export function buildRevenueReadinessCopy({
  approvedCommunityEventReviews = [],
  approvedCustomerValueReviews = [],
  communityEventReviewQueue = [],
  customerValueReviewQueue = [],
  storeCatalog,
  recommendedRevenuePath,
  monetizationSignalTotal,
  campaignPerformanceSummary,
  referralJoins,
  daysActive,
}) {
  const pricingTestProducts = storeCatalog.map(product => ({
    ...product,
    label: product.kind === 'subscription'
      ? `Tribe Pro ${product.cadence || 'subscription'}`
      : (product.packId || product.id).replace(/_/g, ' '),
  }));

  return {
    pricingTestKitCopy: `Rise With The Tribe Pricing Test Kit:\n\nRecommended path: ${recommendedRevenuePath.label}\nTest message: Would ${recommendedRevenuePath.label} help you stay more consistent if it added clearer accountability, deeper progress proof, and community momentum beyond the free app?\n\nProducts to configure before paid launch:\n${pricingTestProducts.map(product => `- ${product.label}: ${product.id}`).join('\n')}\n\nUse this to validate pricing language manually with your audience. Do not quote unconfigured prices, collect payments outside approved store flows, grant purchases, write entitlements, offer discounts, or claim paid access is live until App Store, Play Billing, receipt validation, and release QA are complete.`,
    founderMemberOfferCopy: `Rise With The Tribe Founder Member Offer Kit:\n\nOffer angle: early tribe accountability access\nRecommended path: ${recommendedRevenuePath.label}\nFirst-party monetization signals: ${monetizationSignalTotal}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\n\nInvite committed early members into the free challenge loop, ask them to save Pro Trial Interest, partner perk interest, or creator beta interest, and use their feedback to validate paid value before charging.\n\nThis is not a sale, coupon, lifetime deal, purchase, entitlement, discount, or paid-access promise. Do not collect payment or promise founder pricing until App Store, Play Billing, receipt validation, legal copy, and release QA are complete.`,
    communityAmbassadorCopy: `Rise With The Tribe Community Ambassador Kit:\n\nAmbassador focus: invite one accountability partner, submit visible wins, and keep weekly challenge momentum alive.\nReferral joins: ${referralJoins}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nFounder offer path: ${recommendedRevenuePath.label}\nFirst-party monetization signals: ${monetizationSignalTotal}\n\nRecruit ambassadors from members who already refer friends, complete challenges, submit feature stories, or consistently share progress. Give them copy prompts, recognition, and challenge leadership moments inside the free community loop first.\n\nThis is a community-recognition brief only. Do not create commissions, payouts, paid roles, affiliate links, partner tracking, purchases, entitlements, discounts, or revenue-share promises until creator terms, payout operations, partner review, and release QA are complete.`,
    communityEventInterestCopy: `Rise With The Tribe Community Event Interest Kit:\n\nEvent angle: local challenge meetup, milestone finisher moment, or seasonal tribe check-in.\nRecommended path: ${recommendedRevenuePath.label}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nActive days proof: ${daysActive}\nFirst-party monetization signals: ${monetizationSignalTotal}\n\nUse this to validate whether members want in-person accountability, milestone merch, studio pop-ups, or local finisher moments after the app challenge loop is already working. Keep the signal first-party: profile interest, challenge joins, referrals, support notes, and consent-cleared submissions.\n\nThis is a community event interest brief only. Do not sell tickets, collect payments, create orders, promise merch, book venues, create partner links, create payouts, write entitlements, export private member data, add tracking pixels, scrape DMs, imply paid access is live, promise outcomes, imply medical results, or pressure members before event ops, safety, refund/support, partner terms, and privacy review are complete.`,
    communityEventReviewDecisionReplyCopy: `Rise With The Tribe Community Event Review Decision Reply Kit:\n\nOpen community event reviews: ${communityEventReviewQueue.length}\nApproved community event reviews: ${approvedCommunityEventReviews.length}\nRecommended path: ${recommendedRevenuePath.label}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nFirst-party monetization signals: ${monetizationSignalTotal}\n\nManual decision replies:\nAPPROVED FOR EVENT LEARNING: This community event review is approved for manual planning. Use first-party demand to shape the next free community validation step without selling tickets, booking venues, promising merch, creating partner links, payouts, payments, orders, or entitlements.\n\nWAITING ON EVENT READINESS: Thanks for the signal. We are waiting on event ops, safety, refund/support, partner terms, and privacy review before turning interest into any public event promise.\n\nNOT READY FOR EVENT HANDOFF: This signal is not ready for event handoff yet. Keep collecting first-party app interest, challenge joins, referrals, support notes, and consent-cleared submissions before proposing tickets, merch, venues, or partner conversations.\n\nDECLINED FOR EVENT HANDOFF: We are not moving this event idea forward right now because the first-party evidence or safety/support readiness is not strong enough. Keep members in the free challenge loop and do not pressure them into an event commitment.\n\nThis is a manual Community Event Review Decision Reply Kit only. Do not sell tickets, collect payments, create orders, promise merch, book venues, create partner links, create payouts, write entitlements, export private member data, add tracking pixels, scrape/store DMs, imply paid access is live, promise outcomes, imply medical results, auto-message users, or pressure members.`,
    communityEventSupportEscalationCopy: `Rise With The Tribe Community Event Support Escalation Kit:\n\nOpen community event reviews: ${communityEventReviewQueue.length}\nApproved community event reviews: ${approvedCommunityEventReviews.length}\nRecommended path: ${recommendedRevenuePath.label}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nActive days proof: ${daysActive}\nFirst-party monetization signals: ${monetizationSignalTotal}\n\nSupport escalation checklist:\n[ ] Assign the first response owner: member support, event ops, safety review, privacy/data safety, partner terms owner, marketplace support, finance/refund policy, or product owner.\n[ ] Classify severity as information request, event-readiness question, safety concern, venue/merch expectation, partner fit issue, refund/payment confusion, privacy concern, accessibility need, or pressure/safety escalation.\n[ ] Use approved response language saying community event support escalation is not ticket sales, not a venue booking, not merch fulfillment, not payment collection, not partner-link activation, not payout approval, and not entitlement approval.\n[ ] Keep escalation notes first-party and support-safe; do not export private member activity, per-user event interest lists, support transcripts, off-platform messages, screenshots with sensitive data, or location commitments.\n[ ] Route unresolved cases to community event review, support review, safety review, privacy/data safety, partner terms review, marketplace support, or launch hold before any public event promise continues.\n\nThis is a manual Community Event Support Escalation Kit only. Do not sell tickets, collect payments, create orders, promise merch, book venues, create partner links, create payouts, write entitlements, export private member data, export per-user event interest lists, store support transcripts, add tracking pixels, scrape/store DMs, auto-message users, imply paid access is live, promise event fulfillment, promise outcomes, imply medical results, or pressure members.`,
    customerValueChecklistCopy: `Rise With The Tribe Customer Value Delivery Checklist:\n\nRecommended path: ${recommendedRevenuePath.label}\nFree loop proof: ${daysActive} active days, ${referralJoins} referral joins, ${campaignPerformanceSummary.memberReach || 0} campaign member reach\nPaid value signal: ${monetizationSignalTotal} first-party monetization signals\nCommunity proof: weekly campaigns, public challenge wins, ambassador recognition, and shareable progress stories\nSupport proof: store readiness, credential setup, release QA, refund/support copy, and entitlement checks before launch\n\nUse this checklist before charging: the free challenge loop must create visible consistency, the paid offer must add measurable accountability or structure, and the user should feel the app saves more effort than it asks for.\n\nThis is a value-readiness brief only. Do not charge users, unlock paid access, promise outcomes, imply medical results, run discounts, write entitlements, or promote paid features as live until store products, support operations, receipt validation, and release QA are complete.`,
    customerValueReviewDecisionReplyCopy: `Rise With The Tribe Customer Value Review Decision Reply Kit:\n\nOpen customer value reviews: ${customerValueReviewQueue.length}\nApproved customer value reviews: ${approvedCustomerValueReviews.length}\nRecommended path: ${recommendedRevenuePath.label}\nFree-loop proof: ${daysActive} active days, ${referralJoins} referral joins, ${campaignPerformanceSummary.memberReach || 0} campaign member reach\nFirst-party monetization signals: ${monetizationSignalTotal}\n\nManual decision replies:\nAPPROVED FOR VALUE LEARNING: This customer value review is approved for manual planning. Use first-party free-loop proof to improve onboarding, challenge accountability, and support readiness before any paid launch step. Do not charge users, unlock paid access, create discounts, write entitlements, or promote paid features as live.\n\nWAITING ON VALUE PROOF: This value review needs clearer proof before it can guide launch decisions. Add first-party active days, challenge joins, progress logs, referral movement, support readiness, or entitlement QA notes before moving forward.\n\nNOT READY FOR PAID HANDOFF: This review is not ready for paid handoff. Keep members in the free challenge loop until the value proof, support readiness, store validation, and entitlement QA are stronger.\n\nDECLINED FOR VALUE HANDOFF: We are not using this review for paid-launch planning right now. The evidence does not yet prove the free loop is creating enough visible consistency, accountability value, community proof, or support readiness.\n\nThis is a manual Customer Value Review Decision Reply Kit only. Do not charge users, unlock paid access, create discounts, collect payment details, create purchases, write entitlements, process refunds, bypass marketplace policy, promote paid features as live, promise outcomes, imply medical results, add tracking pixels, scrape/store DMs, auto-message users, or pressure members.`,
  };
}
