export function buildStoreLifecycleCopy({
  renewalRecoveryItems,
  cancellationFeedbackItems,
  lapsedMemberWinbackItems,
  storeLaunchDryRunItems,
  storeTestPurchaseSessionPrepItems,
  storeEvidenceArchiveItems,
  storeEvidenceExportTemplateItems,
  storeDemoAccountItems,
  storeScreenshotQaItems,
  storeReviewPackItems,
  storeReviewEvidenceGapDecisionItems,
  storeReviewEvidenceGapTriageItems,
  storeReviewPolicyLinkQaItems,
  storeReviewRejectionRootCauseItems,
  storeReviewerReplyPacketItems,
  storeReviewMetadataDiffItems,
  storeReviewDataSafetyAlignmentItems,
  storeReviewPermissionCopyCheckItems,
  storeReviewDemoAccessQaItems,
  storeReviewResubmissionItems,
  storeCatalog,
  policyLinks,
  weeklyCampaignPrompt,
  currentStreak,
  referralJoins,
  monetizationSignalTotal,
  proTrialDemandTotal,
  recommendedRevenuePath,
  validationReadinessConfirmed,
  proActive,
  activeChallengePackCount,
  challengePackCount,
  entitlementRecoveryReviewCount,
  supportReviewCount,
  storeTestEvidenceSummary,
  paidLaunchDecisionStatus,
  paidLaunchReadyCount,
  paidLaunchDecisionItemCount,
}) {
  const minimumEvidence = storeTestEvidenceSummary.minimumEvidence || {
    missingRequiredCases: [],
    missingSafeDenialPlatforms: [],
    requiredCaseCount: 0,
    verifiedCaseCount: 0,
  };
  const storeTestEvidenceMatrixLines = [
    `- Minimum evidence matrix: ${minimumEvidence.verifiedCaseCount}/${minimumEvidence.requiredCaseCount} required proof items verified`,
    `- Missing required cases: ${minimumEvidence.missingRequiredCases.length ? minimumEvidence.missingRequiredCases.join(', ') : 'none'}`,
    `- Missing safe-denial platforms: ${minimumEvidence.missingSafeDenialPlatforms.length ? minimumEvidence.missingSafeDenialPlatforms.join(', ') : 'none'}`,
  ].join('\n');

  const renewalRecoveryCopy = `Rise With The Tribe Renewal Recovery Kit:\n\n${renewalRecoveryItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nRecovery summary:\n- Active Pro: ${proActive ? 'yes' : 'no'}\n- Active packs: ${activeChallengePackCount}/${challengePackCount}\n- Entitlement recovery queue: ${entitlementRecoveryReviewCount} open support case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.failed} failed)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n\nMember reply checklist:\n[ ] Confirm the store account that owns the original purchase\n[ ] Ask the member to check App Store or Google Play renewal/payment status\n[ ] Ask the member to restore/sync purchases in the app after marketplace renewal is fixed\n[ ] If access is still missing, open entitlement recovery and attach support notes before backend review\n[ ] Keep failed-renewal, grace-period, chargeback, refund, cancellation, and payment-method questions with marketplace support\n\nThis is a renewal recovery brief only. Do not retry charges in-app, collect payment details, cancel subscriptions, process refunds, create purchases, write entitlements, override marketplace renewal status, promise restored access, imply medical results, or mark paid access live until store products, receipt validation, restore QA, entitlement QA, and support operations are complete.`;

  const cancellationFeedbackCopy = `Rise With The Tribe Cancellation Feedback Kit:\n\n${cancellationFeedbackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nFeedback summary:\n- Recommended revenue path: ${recommendedRevenuePath.label}\n- First-party monetization signals: ${monetizationSignalTotal}\n- Pro trial interest: ${proTrialDemandTotal}\n- Pack products planned: ${challengePackCount}\n- Support readiness: ${validationReadinessConfirmed ? 'credential readiness acknowledged' : 'store validation still pending'}\n\nMember-safe prompts:\n[ ] What were you hoping Tribe Pro or challenge packs would help with?\n[ ] What felt missing, confusing, too expensive, or not worth renewing?\n[ ] Which free challenge/accountability feature should stay easiest to use?\n[ ] Would reports, private challenges, structured packs, creator challenges, or partner perks make the value clearer later?\n[ ] Remind the member that cancellation, refunds, renewal status, and billing changes happen in App Store or Google Play subscriptions.\n\nThis is a cancellation feedback brief only. Do not block cancellation, retry charges in-app, collect payment details, offer unconfigured discounts, process refunds, create purchases, write entitlements, override marketplace subscription state, promise future pricing, imply medical results, pressure the member to stay, or mark paid access live until store products, receipt validation, entitlement QA, support operations, and approved offer policy are complete.`;

  const lapsedMemberWinbackCopy = `Rise With The Tribe Lapsed Member Winback Kit:\n\n${lapsedMemberWinbackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nWinback summary:\n- Weekly campaign: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Comeback CTA: ${weeklyCampaignPrompt.cta}\n- Current streak: ${currentStreak} day${currentStreak === 1 ? '' : 's'}\n- Referral joins: ${referralJoins}\n- First-party monetization signals: ${monetizationSignalTotal}\n\nManual winback copy:\n[ ] Story angle: You can come back with one honest log. Join ${weeklyCampaignPrompt.name}, save the session, and use ${weeklyCampaignPrompt.hashtag} only if you choose to share it.\n[ ] DM/comment reply: No pressure to restart perfectly. Open Rise With The Tribe, log one small activity, and invite one accountability partner if that makes today easier.\n[ ] App-first next step: join the current challenge, log today, review streak rescue copy, then decide whether Pro, packs, creator challenges, or partner perks are actually useful.\n[ ] Review note: measure winback using first-party app logs, challenge joins, referrals, feature submissions, support notes, and saved interest only.\n\nThis is a manual lapsed-member winback brief only. Do not auto-message users, scrape DMs, store inbound replies, add tracking pixels, create attribution records, offer unconfigured discounts, retry charges, collect payment details, create purchases, write entitlements, imply paid access is live, promise outcomes, imply medical results, or pressure members to return.`;

  const storeLaunchDryRunCopy = `Rise With The Tribe Store Launch Dry-Run Kit:\n\n${storeLaunchDryRunItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDry-run summary:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Entitlement recovery queue: ${entitlementRecoveryReviewCount} open support case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n- Support requests open: ${supportReviewCount}\n- Policy links visible: ${policyLinks.length}\n- Recommended revenue path: ${recommendedRevenuePath.label}\n\nManual dry-run script:\n[ ] Sign in with a release test account and confirm onboarding, profile photo/avatar, goals, reminders, and support links render correctly.\n[ ] Join this week's campaign challenge, log one activity, confirm calendar history, badges, points, share cards, and Feature Me consent flow.\n[ ] Run restore/sync, entitlement recovery request, support request, and store-test evidence review paths without writing entitlements from the client.\n[ ] Confirm App Store / Play listing copy, reviewer notes, data safety notes, and refund/support handoff do not claim paid access is live early.\n[ ] Record dry-run gaps before any paid launch decision changes.\n\nThis is a manual Store Launch Dry-Run Kit only. Do not flip paid access live, write entitlements, create purchases, process payments, process refunds, bypass marketplace policy, collect payment details, submit store review, mark validation complete without credentials, claim sandbox/license-test purchases passed without evidence, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or announce launch readiness until the full release dry run passes.`;

  const storeTestPurchaseSessionPrepCopy = `Rise With The Tribe Store Test Purchase Session Prep Kit:\n\n${storeTestPurchaseSessionPrepItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nSession readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products under test: ${storeCatalog.map(product => product.id).join(', ')}\n\nManual test session checklist:\n[ ] Confirm App Store Connect, Play Console, and Firebase Functions credentials are configured outside source control.\n[ ] Run the exact product IDs in this build and record platform, product ID, test case, result, and short evidence note only after the real sandbox/license-test action happens.\n[ ] Export only platform, productId, testCase, result, evidenceNote, reviewNote, and reviewedAt fields into sanitized-store-evidence.json.\n[ ] Run node scripts/check-store-launch-readiness.js --evidence-log path/to/sanitized-store-evidence.json --json and archive the output with the internal release packet.\n[ ] Re-run restore/sync and entitlement recovery after purchase tests so support has a clean handoff path.\n[ ] Mark failed, wrong-account, duplicate-restore, and negative-validation results honestly; do not turn evidence into launch approval.\n\nThis is a manual Store Test Purchase Session Prep Kit only. Do not create fake purchase evidence, export order IDs, export transaction IDs, store raw purchase tokens, store tester emails, store tester passwords, store private keys, store service account JSON, write entitlements from the client, create purchases outside StoreKit or Play Billing, process refunds, bypass marketplace policy, mark validation complete without credentials, mark paid access live, submit store review, promise outcomes, imply medical results, auto-message users, scrape/store DMs, or pressure testers.`;

  const storeEvidenceArchiveCopy = `Rise With The Tribe Store Evidence Archive Kit:\n\n${storeEvidenceArchiveItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nArchive readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products archived: ${storeCatalog.map(product => product.id).join(', ')}\n\nArchive checklist:\n[ ] Confirm sanitized-store-evidence.json contains only platform, productId, testCase, result, evidenceNote, reviewNote, and reviewedAt fields.\n[ ] Confirm the --json audit output shows evidenceReady, verifiedCaseCount, missingRequiredCases, and missingSafeDenialPlatforms for this release candidate.\n[ ] Store the sanitized export, JSON audit output, build number, reviewer, and reviewedAt timestamp in the internal release packet.\n[ ] Copy only aggregate evidence status into reviewer notes; keep tokens, transaction IDs, tester emails, tester aliases, and private screenshots out of public submissions.\n[ ] Re-run the archive after any product, credential, entitlement, restore/sync, support handoff, or paid-launch decision change.\n\nThis is a manual Store Evidence Archive Kit only. Do not create fake evidence, export raw purchase tokens, export transaction IDs, export order IDs, store tester emails, store tester passwords, store private keys, store service account JSON, expose private screenshots, write entitlements from the client, create purchases outside StoreKit or Play Billing, process refunds, bypass marketplace policy, mark paid access live, submit store review, or treat archived evidence as final launch approval.`;

  const sanitizedEvidenceTemplate = storeCatalog.slice(0, 2).map((product, index) => `  {\n    "platform": "${index === 0 ? 'ios' : 'android'}",\n    "productId": "${product.id}",\n    "testCase": "${index === 0 ? 'sandbox_purchase' : 'restore_sync'}",\n    "result": "needs_review",\n    "evidenceNote": "Replace after real sandbox/license-test evidence is reviewed. Do not paste tokens, transaction IDs, order IDs, tester emails, or private screenshots.",\n    "reviewNote": "Reviewer initials and safe entitlement path check only.",\n    "reviewedAt": "YYYY-MM-DDTHH:mm:ssZ"\n  }`).join(',\n');
  const storeEvidenceExportTemplateCopy = `Rise With The Tribe Store Evidence Export Template Kit:\n\n${storeEvidenceExportTemplateItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nSanitized JSON template:\n[\n${sanitizedEvidenceTemplate}\n]\n\nTemplate checklist:\n[ ] Keep only platform, productId, testCase, result, evidenceNote, reviewNote, and reviewedAt fields.\n[ ] Keep result as needs_review until a human reviews real sandbox/license-test evidence.\n[ ] Use testCase values sandbox_purchase, restore_sync, negative_validation, or wrong_account only.\n[ ] Use result values verified, verified_safe_denial, needs_review, failed, or archived only.\n[ ] Run node scripts/check-store-launch-readiness.js --evidence-log path/to/sanitized-store-evidence.json --json before archive review.\n\nThis is a manual Store Evidence Export Template Kit only. Do not create fake evidence, export raw purchase tokens, export transaction IDs, export order IDs, store tester emails, store tester passwords, store private keys, store service account JSON, expose private screenshots, write entitlements from the client, create purchases outside StoreKit or Play Billing, process refunds, bypass marketplace policy, mark paid access live, submit store review, or treat a template record as verified evidence.`;

  const storeDemoAccountCopy = `Rise With The Tribe Store Demo Account Kit:\n\n${storeDemoAccountItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDemo account brief:\n- Decision gate: ${paidLaunchDecisionStatus}\n- Products in code: ${storeCatalog.length}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Weekly campaign to show: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android)\n- Support queue coverage: ${supportReviewCount} open support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer note checklist:\n[ ] Provide a dedicated demo account email through App Store Connect / Play Console review notes, not in public app copy.\n[ ] Seed only synthetic activity, challenge, profile, support, and Feature Me examples; do not expose real member data or private submissions.\n[ ] Explain that optional health sync imports user-authorized activity only and can be skipped by reviewers.\n[ ] Explain that media access is only for profile photos and optional Feature Me submissions with consent.\n[ ] Explain that paid products remain gated until real sandbox/license-test purchases, backend validation, restore, and entitlement QA pass.\n[ ] Include support, privacy, terms, and data deletion links for reviewer navigation.\n\nThis is a manual Store Demo Account Kit only. Do not create accounts from client code, store reviewer passwords in git, expose real user data, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, submit store review, claim paid access is live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or include private credentials in screenshots or public docs.`;

  const storeScreenshotQaCopy = `Rise With The Tribe Store Screenshot QA Kit:\n\n${storeScreenshotQaItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nScreenshot readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Weekly campaign to show: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n\nScreenshot QA checklist:\n[ ] Use synthetic demo account data only and remove personal emails, private submissions, support notes, transaction IDs, order IDs, raw purchase tokens, credentials, service account JSON, and reviewer passwords.\n[ ] Capture the free challenge loop first: onboarding, join challenge, tracker progress, activity log, badges, share card, Feature Me consent, support links, and account/data deletion resources.\n[ ] Show Pro, pack, restore, and entitlement messaging as pending/review mode until real sandbox/license-test evidence and backend validation are proven.\n[ ] Verify App Store and Play captions match current screens, policy links, optional HealthKit / Health Connect behavior, media upload consent, and marketplace billing boundaries.\n[ ] Record screenshot gaps before any store review submission or paid-access launch decision changes.\n\nThis is a manual Store Screenshot QA Kit only. Do not submit store review, expose personal user data, expose private submissions, include passwords or secret keys, include purchase tokens, store credentials, store service account JSON, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, claim paid access is live, claim sandbox/license-test evidence without proof, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  const storeReviewPackCopy = `Rise With The Tribe Store Review Pack:\n\n${storeReviewPackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nReview preparation brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Products in code: ${storeCatalog.length}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer submission checklist:\n[ ] Include demo account instructions through App Store Connect / Play Console review notes only.\n[ ] Explain optional HealthKit / Health Connect, media upload, notifications, purchase verification, restore/sync, support, privacy, terms, and data deletion behavior.\n[ ] Attach sandbox/license-test evidence status and entitlement QA gaps without claiming paid access is ready.\n[ ] Confirm data safety and permission language matches the current app build and public policies.\n[ ] Route refunds, cancellations, payment failures, and billing disputes to App Store or Google Play support.\n\nThis is a manual Store Review Pack only. Do not submit store review, store reviewer passwords in git, expose personal user data, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, claim paid access is live, mark review readiness without evidence, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or include private credentials in screenshots or public docs.`;

  const storeReviewResponseCopy = `Rise With The Tribe Store Review Response Kit:\n\nResponse context:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer follow-up checklist:\n[ ] Answer only the issue raised by App Review or Play review; keep the reply factual and tied to this build.\n[ ] If demo access is requested, provide the reviewed demo account through store-console reviewer notes only, never in public docs or screenshots.\n[ ] If permissions are questioned, explain optional health sync, media upload, notifications, and purchase verification using the current policy links.\n[ ] If purchase or restore behavior is questioned, cite sandbox/license-test evidence status, backend validation readiness, restore/sync flow, and entitlement QA without claiming paid access is live early.\n[ ] If privacy, support, or data deletion is questioned, point reviewers to hosted privacy, terms, support, and data deletion resources.\n[ ] If rejected, record the rejection reason, owner, policy area, evidence gap, and fix plan before resubmitting.\n\nSuggested response opening:\nThank you for the review. Rise With The Tribe is a fitness challenge and accountability app with free challenge, activity logging, streak, badge, sharing, support, and optional manually reviewed community-submission flows. Paid access remains store-backed and should only be promoted after products, receipt validation, restore/sync, entitlement QA, support links, and reviewer evidence are verified for this build.\n\nThis is a manual Store Review Response Kit only. Do not submit store review, bypass marketplace policy, expose private user data, include passwords or secret keys, unlock paid access, write entitlements, create purchases, process refunds, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  const storeReviewResubmissionCopy = `Rise With The Tribe Store Review Resubmission Readiness Kit:\n\n${storeReviewResubmissionItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nResubmission readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual resubmission checklist:\n[ ] Match each rejection or follow-up item to the fixed build, reviewer note, screenshot/caption, permission explanation, policy link, or evidence gap it references.\n[ ] Confirm demo account access is shared only through App Store Connect / Play Console review notes and contains no public password, real member data, private submissions, or credentials.\n[ ] Confirm purchase, restore, entitlement, refund, support, and data deletion language reflects the current build and does not claim paid access is live before evidence is reviewed.\n[ ] Record the resubmission owner, reviewer-note changes, policy area, evidence packet location, and remaining hold items before any console resubmission.\n\nThis is a manual Store Review Resubmission Readiness Kit only. Do not submit store review, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  const storeReviewEvidenceGapTriageCopy = `Rise With The Tribe Store Review Evidence Gap Triage Kit:\n\n${storeReviewEvidenceGapTriageItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nEvidence gap brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links visible: ${policyLinks.length}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual evidence-gap triage:\n[ ] Label every missing matrix case as credential/setup, product configuration, sandbox/license-test action, restore/sync, wrong-account safe denial, screenshot/caption, reviewer-note, policy-link, support/refund handoff, or entitlement QA.\n[ ] Assign an owner, next proof action, evidence note, and reviewedAt target for each missing case before updating reviewer notes or screenshots.\n[ ] Keep external reviewer notes factual: describe only reviewed evidence, current policy links, demo-account path, restore/sync status, and remaining paid-launch holds.\n[ ] Re-run the readiness script after evidence changes and keep paid access in review mode until the gate is reviewed.\n\nThis is a manual Store Review Evidence Gap Triage Kit only. Do not create fake evidence, submit store review, expose personal user data, expose private submissions, include passwords, include secret keys, include purchase tokens, export transaction IDs, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  const storeReviewEvidenceGapDecisionCopy = `Rise With The Tribe Store Review Evidence Gap Decision Reply Kit:\n\n${storeReviewEvidenceGapDecisionItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDecision context:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual evidence-gap decision replies:\nAPPROVED FOR GAP WORK: This evidence gap is approved for manual follow-up. Attach the owner, platform, product ID, missing case, proof path, support handoff, policy link, and reviewedAt target before changing reviewer notes.\n\nWAITING ON PROOF: This gap is waiting on real sandbox/license-test, restore/sync, screenshot, policy, support, or entitlement QA evidence. Keep review prep internal until the missing proof is reviewed.\n\nNOT READY FOR REVIEW NOTES: This gap is not ready for reviewer notes. Add product/platform context, evidence notes, safe-denial status, support/refund handoff, and paid-launch gate status before resubmission prep.\n\nDECLINED FOR RESUBMISSION: This gap should not move into resubmission because it relies on unreviewed proof, private data, credentials, purchase tokens, fake evidence, or pressure to move faster than the evidence allows.\n\nThis is a manual Store Review Evidence Gap Decision Reply Kit only. Do not create fake evidence, submit store review, expose personal user data, expose private submissions, include passwords, include secret keys, include purchase tokens, export transaction IDs, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewPolicyLinkQaCopy = `Rise With The Tribe Store Review Policy Link QA Kit:\n\n${storeReviewPolicyLinkQaItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nPolicy link QA brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual policy-link QA checklist:\n[ ] Open privacy, terms, support, and data-deletion URLs from the reviewer notes and confirm they load without authentication, private data, credentials, or draft-only links.\n[ ] Match App Store / Play data safety, optional HealthKit / Health Connect, media upload, notifications, purchase validation, restore/sync, support, refund, and account deletion wording to the current build.\n[ ] Remove any reviewer-note language that claims paid access is live, claims sandbox/license-test proof without evidence, promises refunds, promises outcomes, or bypasses marketplace support.\n[ ] Record policy-link QA owner, reviewedAt target, fixed build reference, evidence packet location, and remaining hold items before resubmission prep.\n\nThis is a manual Store Review Policy Link QA Kit only. Do not submit store review, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewRejectionRootCauseCopy = `Rise With The Tribe Store Review Rejection Root Cause Kit:\n\n${storeReviewRejectionRootCauseItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nRoot-cause brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual root-cause checklist:\n[ ] Quote the reviewer feedback internally, then classify it as demo access, permission wording, IAP/purchase evidence, restore/sync, metadata, screenshot/caption, privacy/data safety, support/refund, data deletion, or paid-access claim.\n[ ] Assign each root cause to a fixed build owner, reviewer-note owner, screenshot/metadata owner, evidence owner, policy-link owner, or support owner.\n[ ] Link each root cause to the required proof: fixed build reference, sanitized evidence packet, policy URL, screenshot, reviewer-note change, support handoff, or data-safety update.\n[ ] Keep paid access in review mode until every root cause has reviewed proof and the launch gate remains honest.\n\nThis is a manual Store Review Rejection Root Cause Kit only. Do not submit store review, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewerReplyPacketCopy = `Rise With The Tribe Store Reviewer Reply Packet Kit:\n\n${storeReviewerReplyPacketItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nReviewer reply packet brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual reviewer reply packet checklist:\n[ ] Confirm the reviewer issue, root cause, fixed build reference, reviewer-note owner, and exact reply text before any console action.\n[ ] Attach only reviewed proof references: sanitized evidence packet location, policy URLs, screenshot/caption owner, data-safety update, support handoff, and restore/sync status.\n[ ] Remove personal user data, private submissions, credentials, service account JSON, reviewer passwords, purchase tokens, order IDs, transaction IDs, and unreviewed screenshots from the packet.\n[ ] Keep paid access in review mode and keep the packet internal until the launch gate, evidence owner, policy-link owner, and support owner sign off.\n\nThis is a manual Store Reviewer Reply Packet Kit only. Do not submit store review, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, include order IDs, include transaction IDs, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewMetadataDiffCopy = `Rise With The Tribe Store Review Metadata Diff Kit:\n\n${storeReviewMetadataDiffItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nMetadata diff brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual metadata diff checklist:\n[ ] Compare App Store and Play title, subtitle, short description, full description, screenshot captions, reviewer notes, and data-safety text against the current build.\n[ ] Mark each mismatch as metadata, screenshot/caption, permission explanation, policy link, data safety, purchase/restore behavior, support/refund handoff, or paid-access claim.\n[ ] Assign the metadata owner, screenshot owner, policy-link owner, evidence owner, support owner, and reviewedAt target before reviewer replies or resubmission prep move forward.\n[ ] Keep the diff internal until listing copy, screenshots, captions, policy links, data safety, evidence packet, and support handoff all match the fixed build.\n\nThis is a manual Store Review Metadata Diff Kit only. Do not submit store review, publish unreviewed store metadata, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, include order IDs, include transaction IDs, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewDataSafetyAlignmentCopy = `Rise With The Tribe Store Review Data Safety Alignment Kit:\n\n${storeReviewDataSafetyAlignmentItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nData safety alignment brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual data safety alignment checklist:\n[ ] Compare App Privacy and Play Data Safety answers for auth, profile, activity logs, optional HealthKit / Health Connect sync, media uploads, notifications, purchase validation, support, and account/data deletion.\n[ ] Confirm privacy policy, terms, support, data deletion, reviewer notes, permission prompts, screenshots, and captions describe the same current-build data use.\n[ ] Mark every mismatch as privacy label, Play Data Safety, permission explanation, policy link, support/deletion, purchase validation, screenshot/caption, or reviewer-note follow-up.\n[ ] Keep the alignment packet internal until policy-link owner, data-safety owner, evidence owner, support owner, and fixed-build owner sign off.\n\nThis is a manual Store Review Data Safety Alignment Kit only. Do not submit store review, publish unreviewed privacy labels, publish unreviewed data safety answers, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, include order IDs, include transaction IDs, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewPermissionCopyCheckCopy = `Rise With The Tribe Store Review Permission Copy Check Kit:\n\n${storeReviewPermissionCopyCheckItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nPermission copy brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual permission copy checklist:\n[ ] Compare reviewer notes, permission prompts, screenshots, captions, privacy policy, terms, support, and data deletion language for optional HealthKit / Health Connect, media uploads, notifications, purchase validation, restore/sync, support, and account deletion.\n[ ] Mark every mismatch as health permission, media permission, notification permission, purchase validation, restore/sync, support/deletion, screenshot/caption, policy link, or reviewer-note follow-up.\n[ ] Remove copy that implies health sync is required, posts are automatic, media is public without consent, medical results are promised, paid access is live, or sandbox/license-test proof exists without evidence.\n[ ] Keep the check internal until permission-copy owner, data-safety owner, policy-link owner, screenshot owner, and reviewer-reply owner sign off.\n\nThis is a manual Store Review Permission Copy Check Kit only. Do not submit store review, publish unreviewed permission copy, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, include order IDs, include transaction IDs, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  const storeReviewDemoAccessQaCopy = `Rise With The Tribe Store Review Demo Access QA Kit:\n\n${storeReviewDemoAccessQaItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDemo access QA brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nManual demo access QA checklist:\n[ ] Confirm the reviewer demo account is shared only through App Store Connect or Play Console notes, not public docs, screenshots, git, analytics, or support-copy exports.\n[ ] Verify seeded demo data shows onboarding, profile appearance, joined campaign challenge, activity history, badges, share cards, support links, and Feature Me consent without real member data.\n[ ] Confirm optional HealthKit / Health Connect, media upload, notifications, support, privacy, terms, data deletion, restore/sync, and purchase validation notes match the current build.\n[ ] Keep paid surfaces in review mode until sandbox/license-test evidence, restore, validation, and entitlement QA are reviewed for this build.\n\nThis is a manual Store Review Demo Access QA Kit only. Do not submit store review, store reviewer passwords, expose personal user data, expose private submissions, include secret keys, include purchase tokens, include order IDs, include transaction IDs, publish private policy drafts, store credentials, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, process refunds, bypass StoreKit or Play Billing, claim sandbox/license-test proof without evidence, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, auto-message users, or pressure reviewers or members.`;

  return {
    renewalRecoveryCopy,
    cancellationFeedbackCopy,
    lapsedMemberWinbackCopy,
    storeLaunchDryRunCopy,
    storeTestPurchaseSessionPrepCopy,
    storeEvidenceArchiveCopy,
    storeEvidenceExportTemplateCopy,
    storeDemoAccountCopy,
    storeScreenshotQaCopy,
    storeReviewPackCopy,
    storeReviewResponseCopy,
    storeReviewEvidenceGapDecisionCopy,
    storeReviewEvidenceGapTriageCopy,
    storeReviewPolicyLinkQaCopy,
    storeReviewRejectionRootCauseCopy,
    storeReviewerReplyPacketCopy,
    storeReviewMetadataDiffCopy,
    storeReviewDataSafetyAlignmentCopy,
    storeReviewPermissionCopyCheckCopy,
    storeReviewDemoAccessQaCopy,
    storeReviewResubmissionCopy,
  };
}
