export function buildStoreLifecycleCopy({
  renewalRecoveryItems,
  cancellationFeedbackItems,
  lapsedMemberWinbackItems,
  storeLaunchDryRunItems,
  storeTestPurchaseSessionPrepItems,
  storeDemoAccountItems,
  storeScreenshotQaItems,
  storeReviewPackItems,
  storeCatalog,
  policyLinks,
  weeklyCampaignPrompt,
  currentStreak,
  referralJoins,
  monetizationSignalTotal,
  proTrialDemandTotal,
  recommendedRevenuePath,
  validationReadinessConfirmed,
  proActive,
  activeChallengePackCount,
  challengePackCount,
  entitlementRecoveryReviewCount,
  supportReviewCount,
  storeTestEvidenceSummary,
  paidLaunchDecisionStatus,
  paidLaunchReadyCount,
  paidLaunchDecisionItemCount,
}) {
  const renewalRecoveryCopy = `Rise With The Tribe Renewal Recovery Kit:\n\n${renewalRecoveryItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nRecovery summary:\n- Active Pro: ${proActive ? 'yes' : 'no'}\n- Active packs: ${activeChallengePackCount}/${challengePackCount}\n- Entitlement recovery queue: ${entitlementRecoveryReviewCount} open support case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.failed} failed)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n\nMember reply checklist:\n[ ] Confirm the store account that owns the original purchase\n[ ] Ask the member to check App Store or Google Play renewal/payment status\n[ ] Ask the member to restore/sync purchases in the app after marketplace renewal is fixed\n[ ] If access is still missing, open entitlement recovery and attach support notes before backend review\n[ ] Keep failed-renewal, grace-period, chargeback, refund, cancellation, and payment-method questions with marketplace support\n\nThis is a renewal recovery brief only. Do not retry charges in-app, collect payment details, cancel subscriptions, process refunds, create purchases, write entitlements, override marketplace renewal status, promise restored access, imply medical results, or mark paid access live until store products, receipt validation, restore QA, entitlement QA, and support operations are complete.`;

  const cancellationFeedbackCopy = `Rise With The Tribe Cancellation Feedback Kit:\n\n${cancellationFeedbackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nFeedback summary:\n- Recommended revenue path: ${recommendedRevenuePath.label}\n- First-party monetization signals: ${monetizationSignalTotal}\n- Pro trial interest: ${proTrialDemandTotal}\n- Pack products planned: ${challengePackCount}\n- Support readiness: ${validationReadinessConfirmed ? 'credential readiness acknowledged' : 'store validation still pending'}\n\nMember-safe prompts:\n[ ] What were you hoping Tribe Pro or challenge packs would help with?\n[ ] What felt missing, confusing, too expensive, or not worth renewing?\n[ ] Which free challenge/accountability feature should stay easiest to use?\n[ ] Would reports, private challenges, structured packs, creator challenges, or partner perks make the value clearer later?\n[ ] Remind the member that cancellation, refunds, renewal status, and billing changes happen in App Store or Google Play subscriptions.\n\nThis is a cancellation feedback brief only. Do not block cancellation, retry charges in-app, collect payment details, offer unconfigured discounts, process refunds, create purchases, write entitlements, override marketplace subscription state, promise future pricing, imply medical results, pressure the member to stay, or mark paid access live until store products, receipt validation, entitlement QA, support operations, and approved offer policy are complete.`;

  const lapsedMemberWinbackCopy = `Rise With The Tribe Lapsed Member Winback Kit:\n\n${lapsedMemberWinbackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nWinback summary:\n- Weekly campaign: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Comeback CTA: ${weeklyCampaignPrompt.cta}\n- Current streak: ${currentStreak} day${currentStreak === 1 ? '' : 's'}\n- Referral joins: ${referralJoins}\n- First-party monetization signals: ${monetizationSignalTotal}\n\nManual winback copy:\n[ ] Story angle: You can come back with one honest log. Join ${weeklyCampaignPrompt.name}, save the session, and use ${weeklyCampaignPrompt.hashtag} only if you choose to share it.\n[ ] DM/comment reply: No pressure to restart perfectly. Open Rise With The Tribe, log one small activity, and invite one accountability partner if that makes today easier.\n[ ] App-first next step: join the current challenge, log today, review streak rescue copy, then decide whether Pro, packs, creator challenges, or partner perks are actually useful.\n[ ] Review note: measure winback using first-party app logs, challenge joins, referrals, feature submissions, support notes, and saved interest only.\n\nThis is a manual lapsed-member winback brief only. Do not auto-message users, scrape DMs, store inbound replies, add tracking pixels, create attribution records, offer unconfigured discounts, retry charges, collect payment details, create purchases, write entitlements, imply paid access is live, promise outcomes, imply medical results, or pressure members to return.`;

  const storeLaunchDryRunCopy = `Rise With The Tribe Store Launch Dry-Run Kit:\n\n${storeLaunchDryRunItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDry-run summary:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n- Entitlement recovery queue: ${entitlementRecoveryReviewCount} open support case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n- Support requests open: ${supportReviewCount}\n- Policy links visible: ${policyLinks.length}\n- Recommended revenue path: ${recommendedRevenuePath.label}\n\nManual dry-run script:\n[ ] Sign in with a release test account and confirm onboarding, profile photo/avatar, goals, reminders, and support links render correctly.\n[ ] Join this week's campaign challenge, log one activity, confirm calendar history, badges, points, share cards, and Feature Me consent flow.\n[ ] Run restore/sync, entitlement recovery request, support request, and store-test evidence review paths without writing entitlements from the client.\n[ ] Confirm App Store / Play listing copy, reviewer notes, data safety notes, and refund/support handoff do not claim paid access is live early.\n[ ] Record dry-run gaps before any paid launch decision changes.\n\nThis is a manual Store Launch Dry-Run Kit only. Do not flip paid access live, write entitlements, create purchases, process payments, process refunds, bypass marketplace policy, collect payment details, submit store review, mark validation complete without credentials, claim sandbox/license-test purchases passed without evidence, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or announce launch readiness until the full release dry run passes.`;

  const storeTestPurchaseSessionPrepCopy = `Rise With The Tribe Store Test Purchase Session Prep Kit:\n\n${storeTestPurchaseSessionPrepItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nSession readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Validation readiness: ${validationReadinessConfirmed ? 'provider credentials detected' : 'credentials or sandbox/license-test proof still pending'}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n- Products under test: ${storeCatalog.map(product => product.id).join(', ')}\n\nManual test session checklist:\n[ ] Confirm App Store Connect, Play Console, and Firebase Functions credentials are configured outside source control.\n[ ] Run the exact product IDs in this build and record platform, product ID, test case, result, and short evidence note only after the real sandbox/license-test action happens.\n[ ] Re-run restore/sync and entitlement recovery after purchase tests so support has a clean handoff path.\n[ ] Mark failed, wrong-account, duplicate-restore, and negative-validation results honestly; do not turn evidence into launch approval.\n\nThis is a manual Store Test Purchase Session Prep Kit only. Do not create fake purchase evidence, store raw purchase tokens, store tester passwords, store private keys, store service account JSON, write entitlements from the client, create purchases outside StoreKit or Play Billing, process refunds, bypass marketplace policy, mark validation complete without credentials, mark paid access live, submit store review, promise outcomes, imply medical results, auto-message users, scrape/store DMs, or pressure testers.`;

  const storeDemoAccountCopy = `Rise With The Tribe Store Demo Account Kit:\n\n${storeDemoAccountItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nDemo account brief:\n- Decision gate: ${paidLaunchDecisionStatus}\n- Products in code: ${storeCatalog.length}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Weekly campaign to show: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android)\n- Support queue coverage: ${supportReviewCount} open support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer note checklist:\n[ ] Provide a dedicated demo account email through App Store Connect / Play Console review notes, not in public app copy.\n[ ] Seed only synthetic activity, challenge, profile, support, and Feature Me examples; do not expose real member data or private submissions.\n[ ] Explain that optional health sync imports user-authorized activity only and can be skipped by reviewers.\n[ ] Explain that media access is only for profile photos and optional Feature Me submissions with consent.\n[ ] Explain that paid products remain gated until real sandbox/license-test purchases, backend validation, restore, and entitlement QA pass.\n[ ] Include support, privacy, terms, and data deletion links for reviewer navigation.\n\nThis is a manual Store Demo Account Kit only. Do not create accounts from client code, store reviewer passwords in git, expose real user data, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, submit store review, claim paid access is live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or include private credentials in screenshots or public docs.`;

  const storeScreenshotQaCopy = `Rise With The Tribe Store Screenshot QA Kit:\n\n${storeScreenshotQaItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nScreenshot readiness brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Weekly campaign to show: ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.hashtag})\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n\nScreenshot QA checklist:\n[ ] Use synthetic demo account data only and remove personal emails, private submissions, support notes, transaction IDs, order IDs, raw purchase tokens, credentials, service account JSON, and reviewer passwords.\n[ ] Capture the free challenge loop first: onboarding, join challenge, tracker progress, activity log, badges, share card, Feature Me consent, support links, and account/data deletion resources.\n[ ] Show Pro, pack, restore, and entitlement messaging as pending/review mode until real sandbox/license-test evidence and backend validation are proven.\n[ ] Verify App Store and Play captions match current screens, policy links, optional HealthKit / Health Connect behavior, media upload consent, and marketplace billing boundaries.\n[ ] Record screenshot gaps before any store review submission or paid-access launch decision changes.\n\nThis is a manual Store Screenshot QA Kit only. Do not submit store review, expose personal user data, expose private submissions, include passwords or secret keys, include purchase tokens, store credentials, store service account JSON, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, claim paid access is live, claim sandbox/license-test evidence without proof, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  const storeReviewPackCopy = `Rise With The Tribe Store Review Pack:\n\n${storeReviewPackItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nReview preparation brief:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Products in code: ${storeCatalog.length}\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer submission checklist:\n[ ] Include demo account instructions through App Store Connect / Play Console review notes only.\n[ ] Explain optional HealthKit / Health Connect, media upload, notifications, purchase verification, restore/sync, support, privacy, terms, and data deletion behavior.\n[ ] Attach sandbox/license-test evidence status and entitlement QA gaps without claiming paid access is ready.\n[ ] Confirm data safety and permission language matches the current app build and public policies.\n[ ] Route refunds, cancellations, payment failures, and billing disputes to App Store or Google Play support.\n\nThis is a manual Store Review Pack only. Do not submit store review, store reviewer passwords in git, expose personal user data, unlock paid access, grant Pro, unlock packs, write entitlements, create purchases, bypass StoreKit or Play Billing, process refunds, collect payment details, claim paid access is live, mark review readiness without evidence, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or include private credentials in screenshots or public docs.`;

  const storeReviewResponseCopy = `Rise With The Tribe Store Review Response Kit:\n\nResponse context:\n- Decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\n- Store test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n- Policy links: ${policyLinks.map(link => link.label).join(', ')}\n- Products in code: ${storeCatalog.map(product => product.id).join(', ')}\n- Support coverage: ${supportReviewCount} support case${supportReviewCount === 1 ? '' : 's'} and ${entitlementRecoveryReviewCount} entitlement recovery case${entitlementRecoveryReviewCount === 1 ? '' : 's'}\n\nReviewer follow-up checklist:\n[ ] Answer only the issue raised by App Review or Play review; keep the reply factual and tied to this build.\n[ ] If demo access is requested, provide the reviewed demo account through store-console reviewer notes only, never in public docs or screenshots.\n[ ] If permissions are questioned, explain optional health sync, media upload, notifications, and purchase verification using the current policy links.\n[ ] If purchase or restore behavior is questioned, cite sandbox/license-test evidence status, backend validation readiness, restore/sync flow, and entitlement QA without claiming paid access is live early.\n[ ] If privacy, support, or data deletion is questioned, point reviewers to hosted privacy, terms, support, and data deletion resources.\n[ ] If rejected, record the rejection reason, owner, policy area, evidence gap, and fix plan before resubmitting.\n\nSuggested response opening:\nThank you for the review. Rise With The Tribe is a fitness challenge and accountability app with free challenge, activity logging, streak, badge, sharing, support, and optional manually reviewed community-submission flows. Paid access remains store-backed and should only be promoted after products, receipt validation, restore/sync, entitlement QA, support links, and reviewer evidence are verified for this build.\n\nThis is a manual Store Review Response Kit only. Do not submit store review, bypass marketplace policy, expose private user data, include passwords or secret keys, unlock paid access, write entitlements, create purchases, process refunds, claim review approval, mark paid access live, promise outcomes, imply medical results, add tracking pixels, scrape DMs, or pressure reviewers or members.`;

  return {
    renewalRecoveryCopy,
    cancellationFeedbackCopy,
    lapsedMemberWinbackCopy,
    storeLaunchDryRunCopy,
    storeTestPurchaseSessionPrepCopy,
    storeDemoAccountCopy,
    storeScreenshotQaCopy,
    storeReviewPackCopy,
    storeReviewResponseCopy,
  };
}
