export function buildStoreReviewPlanningCopy({
  sandboxPurchaseTestItems,
  storeCatalog,
  policyLinks,
  revenuePathways,
  recommendedRevenuePath,
  storeTestEvidenceSummary,
  validationReadinessConfirmed,
  paidLaunchDecisionStatus,
  paidLaunchReadyCount,
  paidLaunchDecisionItemCount,
}) {
  const minimumEvidence = storeTestEvidenceSummary.minimumEvidence || {
    missingRequiredCases: [],
    missingSafeDenialPlatforms: [],
    requiredCaseCount: 0,
    verifiedCaseCount: 0,
  };
  const storeTestEvidenceMatrixLines = [
    `Minimum evidence matrix: ${minimumEvidence.verifiedCaseCount}/${minimumEvidence.requiredCaseCount} required proof items verified`,
    `Missing required cases: ${minimumEvidence.missingRequiredCases.length ? minimumEvidence.missingRequiredCases.join(', ') : 'none'}`,
    `Missing safe-denial platforms: ${minimumEvidence.missingSafeDenialPlatforms.length ? minimumEvidence.missingSafeDenialPlatforms.join(', ') : 'none'}`,
  ].join('\n');

  const sandboxPurchaseTestPlanCopy = `Rise With The Tribe Sandbox Purchase Test Plan:\n\nProducts under test:\n${storeCatalog.map(product => `- ${product.id} (${product.kind})`).join('\n')}\n\nTest cases:\n${sandboxPurchaseTestItems.map((item, index) => `${index + 1}. ${item}`).join('\n')}\n\nBefore paid access is promoted: complete App Store sandbox purchases, Play license test purchases, restore flows, backend verifyPurchase validation, Firestore entitlement QA, and support escalation review.\n\nThis is a manual sandbox QA plan only. Do not run live charges, bypass marketplace policy, unlock entitlements from profile UI, write fake purchases, process refunds, promise outcomes, imply medical results, or claim paid access is live until real store test purchases validate end to end.`;

  const storeListingCopy = `Rise With The Tribe Store Listing Copy Kit:\n\nApp name: Rise With The Tribe\nSubtitle: Fitness challenges, streaks, and accountability\nShort description: Join weekly fitness challenges, log progress, build streaks, earn badges, and share wins with the tribe.\n\nValue points:\n- Track daily activity, points, streaks, and days active\n- Join weekly, seasonal, private, creator, and challenge-pack experiences\n- Share progress cards and challenge recaps with @risewiththetribe\n- Save first-party interest for future Tribe Pro, challenge packs, creator tools, and partner perks\n\nLaunch positioning: Lead with the free challenge loop, community accountability, progress proof, badges, calendar history, and social sharing. Mention Tribe Pro and challenge packs only as future or configured store-backed experiences until paid launch is approved.\n\nCurrent decision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\nRecommended revenue path: ${recommendedRevenuePath.label}\n\nThis is store-listing planning copy only. Do not claim paid access is live, advertise unconfigured prices, promise outcomes, imply medical results, mention refunds outside marketplace policy, unlock entitlements, or submit store copy that conflicts with App Store / Play policy until product setup, receipt validation, sandbox purchases, support readiness, and release QA are complete.`;

  const storeReviewSubmissionCopy = `Rise With The Tribe Store Review Submission Kit:\n\nReviewer notes draft:\nRise With The Tribe is a fitness challenge and accountability app. Users can create or join challenges, log activity, build streaks, earn badges, review calendar history, share progress, submit optional stories for manual community review, and save first-party interest in future Pro, challenge-pack, creator, and partner features.\n\nDemo account checklist:\n- Provide a test account with onboarding completed\n- Include at least one joined challenge, activity history, badges, and profile avatar/photo state\n- Keep paid access disabled unless App Store / Play products, receipt validation, sandbox purchases, restore flow, and entitlement QA are complete\n\nPermission explanations:\n- Photos/camera are used only when a user uploads a profile picture or optional feature-submission media\n- Notifications are used for reminders and challenge accountability prompts\n- HealthKit on iOS and Health Connect on Android are optional sync sources for workout/activity logging\n- In-app purchases are verified server-side before shared Firestore entitlements unlock Pro or challenge packs\n\nSupport and privacy notes: reviewers should be pointed to support, privacy policy, terms, and account/data deletion resources before submission.\n\nThis is store-review planning copy only. Do not submit inaccurate permission claims, provide personal user data in reviewer notes, bypass marketplace purchase review, claim medical or guaranteed fitness outcomes, unlock paid access from client code, or mark the app ready for review until store products, policies, support links, privacy/data deletion flows, and entitlement QA are verified.`;

  const storeReviewEvidencePackCopy = `Rise With The Tribe Store Review Evidence Pack:\n\nDecision gate: ${paidLaunchDecisionStatus} (${paidLaunchReadyCount}/${paidLaunchDecisionItemCount} checks ready)\nStore test evidence: ${storeTestEvidenceSummary.total} records (${storeTestEvidenceSummary.ios} iOS, ${storeTestEvidenceSummary.android} Android, ${storeTestEvidenceSummary.needs_review} needs review, ${storeTestEvidenceSummary.failed} failed)\n${storeTestEvidenceMatrixLines}\nRecommended revenue path: ${recommendedRevenuePath.label}\nValidation readiness: ${validationReadinessConfirmed ? 'Credential readiness acknowledged' : 'Credential readiness still pending'}\n\nProducts under review:\n${storeCatalog.map(product => `- ${product.id} (${product.kind})`).join('\n')}\n\nPolicy and support links:\n${policyLinks.map(link => `- ${link.label}: ${link.url}`).join('\n')}\n\nReviewer evidence notes: include demo account context, optional HealthKit / Health Connect explanations, media/photo permission explanations, notification purpose, restore flow status, sandbox/license-test evidence status, and support/privacy/data deletion links in the store submission notes.\n\nThis is a reviewer evidence pack only. Do not submit store review, expose personal user data, unlock paid access, write entitlements, create purchases, process refunds, bypass marketplace policy, mark paid access live, or claim review readiness until evidence, products, credentials, policies, support links, restore flow, and entitlement QA are verified.`;

  const dataSafetyDisclosureCopy = `Rise With The Tribe Data Safety Disclosure Kit:\n\nData categories used by the app:\n- Account identifiers: Firebase Authentication user id, email, and display name for sign-in and account support\n- Profile content: profile photo/avatar, Instagram handle, goals, creator profile, partner/pro interest, cosmetics, and share preferences\n- Fitness/activity data: user-entered activity logs, challenge progress, points, streaks, badges, and optional HealthKit / Health Connect imports after permission\n- User-generated content: optional feature-submission story and media, reviewed manually before any community highlight\n- Purchases: product ids, purchase verification payload metadata, server-side entitlement status, and audit-safe purchase records\n- Notifications: local reminder settings for accountability prompts\n\nDisclosure positioning: data is used for app functionality, account management, analytics derived from first-party app usage, optional health sync, purchase verification, support, and fraud/entitlement protection. The app does not sell personal data, does not use random ad tracking, does not provide medical diagnosis/treatment, and does not share feature submissions publicly without consent and manual review.\n\nStore links: Privacy Policy ${policyLinks[0].url}, Terms ${policyLinks[1].url}, Support ${policyLinks[2].url}, Data Deletion ${policyLinks[3].url}.\n\nThis is data-safety planning copy only. Do not submit store privacy labels that conflict with current permissions, hide optional health/media collection, imply medical or guaranteed fitness outcomes, claim third-party ad tracking exists, omit purchase verification data, or collect new data without updating privacy, data safety, feature parity docs, and release QA.`;

  const revenuePathwayPlannerCopy = `Rise With The Tribe Revenue Pathway Planner:\n\nRecommended path: ${recommendedRevenuePath.label}\nSignal: ${recommendedRevenuePath.signal}\nNext move: ${recommendedRevenuePath.action}\n\nPath signals:\n${revenuePathways.map(pathway => `- ${pathway.label}: ${pathway.signal}`).join('\n')}\n\nUse this as a manual planning brief from first-party app signals only. Do not add tracking pixels, paid-access claims, purchases, entitlements, partner links, or payout promises until store validation, partner terms, creator terms, and release QA are complete.`;

  return {
    sandboxPurchaseTestPlanCopy,
    storeListingCopy,
    storeReviewSubmissionCopy,
    storeReviewEvidencePackCopy,
    dataSafetyDisclosureCopy,
    revenuePathwayPlannerCopy,
  };
}
