export function buildStoreSupportCopyCards({
  subscriptionManagementGuidanceCopy,
  billingSupportEscalationCopy,
  renewalRecoveryCopy,
  cancellationFeedbackCopy,
  lapsedMemberWinbackCopy,
  storeLaunchDryRunCopy,
  storeDemoAccountCopy,
  storeReviewPackCopy,
}) {
  return [
    {
      title: 'SUBSCRIPTION MANAGEMENT GUIDANCE KIT',
      subtitle: 'App Store and Play cancellation/support boundaries',
      status: 'MARKETPLACE FIRST',
      accent: '#2DD4BF',
      body: 'Copy marketplace-first subscription guidance without cancelling subscriptions in-app, collecting payment details, or bypassing App Store or Play policy.',
      buttonLabel: 'COPY SUBSCRIPTION GUIDANCE',
      copyText: subscriptionManagementGuidanceCopy,
    },
    {
      title: 'BILLING SUPPORT ESCALATION KIT',
      subtitle: 'Wrong-account, renewal, charge, and entitlement triage',
      status: 'SUPPORT',
      accent: '#38BDF8',
      body: 'Copy billing escalation context without processing refunds, creating purchases, writing entitlements, or overriding marketplace decisions.',
      buttonLabel: 'COPY BILLING ESCALATION',
      copyText: billingSupportEscalationCopy,
    },
    {
      title: 'RENEWAL RECOVERY KIT',
      subtitle: 'Failed-renewal and lapsed-access support copy',
      status: 'RECOVERY',
      accent: '#A78BFA',
      body: 'Copy renewal recovery guidance without retrying charges in-app, collecting payment details, cancelling subscriptions, or promising restored access.',
      buttonLabel: 'COPY RENEWAL RECOVERY',
      copyText: renewalRecoveryCopy,
    },
    {
      title: 'CANCELLATION FEEDBACK KIT',
      subtitle: 'Marketplace-safe churn learning prompts',
      status: 'FEEDBACK',
      accent: '#FB7185',
      body: 'Copy cancellation feedback prompts without blocking cancellation, retrying charges, offering unconfigured discounts, or pressuring the member to stay.',
      buttonLabel: 'COPY CANCELLATION FEEDBACK',
      copyText: cancellationFeedbackCopy,
    },
    {
      title: 'LAPSED MEMBER WINBACK KIT',
      subtitle: 'Free comeback challenge and app-first return copy',
      status: 'FREE FIRST',
      accent: '#34D399',
      body: 'Copy a free-first comeback prompt for lapsed members without automated messaging, discounts, purchases, entitlements, or pressure.',
      buttonLabel: 'COPY LAPSED WINBACK',
      copyText: lapsedMemberWinbackCopy,
    },
    {
      title: 'STORE LAUNCH DRY-RUN KIT',
      subtitle: 'Manual release rehearsal before paid access',
      status: 'COPY ONLY',
      accent: '#0EA5E9',
      body: 'Copy a release dry-run script that rehearses auth, challenge, logging, sharing, support, restore, and store evidence paths without paid-live side effects.',
      buttonLabel: 'COPY STORE DRY RUN',
      copyText: storeLaunchDryRunCopy,
    },
    {
      title: 'STORE DEMO ACCOUNT KIT',
      subtitle: 'Reviewer-safe demo account notes',
      status: 'REVIEW NOTES',
      accent: '#818CF8',
      body: 'Copy reviewer notes for a synthetic demo account without creating accounts from client code, exposing real users, or unlocking paid access.',
      buttonLabel: 'COPY DEMO ACCOUNT KIT',
      copyText: storeDemoAccountCopy,
    },
    {
      title: 'STORE REVIEW PACK',
      subtitle: 'Reviewer notes and policy evidence',
      status: 'PREP ONLY',
      accent: '#14B8A6',
      body: 'Copy store review prep notes without submitting store review, storing credentials, exposing member data, or claiming paid access readiness.',
      buttonLabel: 'COPY STORE REVIEW PACK',
      copyText: storeReviewPackCopy,
    },
  ];
}
