export function buildStoreSupportCopyCards({
  subscriptionManagementGuidanceCopy,
  billingSupportEscalationCopy,
  renewalRecoveryCopy,
  cancellationFeedbackCopy,
  lapsedMemberWinbackCopy,
  storeLaunchDryRunCopy,
  storeTestPurchaseSessionPrepCopy,
  storeEvidenceArchiveCopy,
  storeEvidenceExportTemplateCopy,
  storeDemoAccountCopy,
  storeScreenshotQaCopy,
  storeReviewPackCopy,
  storeReviewResponseCopy,
  storeReviewEvidenceGapDecisionCopy,
  storeReviewEvidenceGapTriageCopy,
  storeReviewPolicyLinkQaCopy,
  storeReviewRejectionRootCauseCopy,
  storeReviewerReplyPacketCopy,
  storeReviewMetadataDiffCopy,
  storeReviewDataSafetyAlignmentCopy,
  storeReviewPermissionCopyCheckCopy,
  storeReviewDemoAccessQaCopy,
  storeReviewSupportHandoffQaCopy,
  storeReviewEvidencePacketIndexCopy,
  storeReviewFinalSignoffCopy,
  storeReviewConsoleDraftQaCopy,
  storeReviewSubmissionHoldReasonsCopy,
  storeReviewHoldReleaseDecisionCopy,
  storeReviewResubmissionCopy,
}) {
  return [
    {
      title: 'SUBSCRIPTION MANAGEMENT GUIDANCE KIT',
      subtitle: 'App Store and Play cancellation/support boundaries',
      status: 'MARKETPLACE FIRST',
      accent: '#2DD4BF',
      body: 'Copy marketplace-first subscription guidance without cancelling subscriptions in-app, collecting payment details, or bypassing App Store or Play policy.',
      buttonLabel: 'COPY SUBSCRIPTION GUIDANCE',
      copyText: subscriptionManagementGuidanceCopy,
    },
    {
      title: 'BILLING SUPPORT ESCALATION KIT',
      subtitle: 'Wrong-account, renewal, charge, and entitlement triage',
      status: 'SUPPORT',
      accent: '#38BDF8',
      body: 'Copy billing escalation context without processing refunds, creating purchases, writing entitlements, or overriding marketplace decisions.',
      buttonLabel: 'COPY BILLING ESCALATION',
      copyText: billingSupportEscalationCopy,
    },
    {
      title: 'RENEWAL RECOVERY KIT',
      subtitle: 'Failed-renewal and lapsed-access support copy',
      status: 'RECOVERY',
      accent: '#A78BFA',
      body: 'Copy renewal recovery guidance without retrying charges in-app, collecting payment details, cancelling subscriptions, or promising restored access.',
      buttonLabel: 'COPY RENEWAL RECOVERY',
      copyText: renewalRecoveryCopy,
    },
    {
      title: 'CANCELLATION FEEDBACK KIT',
      subtitle: 'Marketplace-safe churn learning prompts',
      status: 'FEEDBACK',
      accent: '#FB7185',
      body: 'Copy cancellation feedback prompts without blocking cancellation, retrying charges, offering unconfigured discounts, or pressuring the member to stay.',
      buttonLabel: 'COPY CANCELLATION FEEDBACK',
      copyText: cancellationFeedbackCopy,
    },
    {
      title: 'LAPSED MEMBER WINBACK KIT',
      subtitle: 'Free comeback challenge and app-first return copy',
      status: 'FREE FIRST',
      accent: '#34D399',
      body: 'Copy a free-first comeback prompt for lapsed members without automated messaging, discounts, purchases, entitlements, or pressure.',
      buttonLabel: 'COPY LAPSED WINBACK',
      copyText: lapsedMemberWinbackCopy,
    },
    {
      title: 'STORE LAUNCH DRY-RUN KIT',
      subtitle: 'Manual release rehearsal before paid access',
      status: 'COPY ONLY',
      accent: '#0EA5E9',
      body: 'Copy a release dry-run script that rehearses auth, challenge, logging, sharing, support, restore, and store evidence paths without paid-live side effects.',
      buttonLabel: 'COPY STORE DRY RUN',
      copyText: storeLaunchDryRunCopy,
    },
    {
      title: 'STORE TEST PURCHASE SESSION PREP KIT',
      subtitle: 'Sandbox and license-test evidence rehearsal',
      status: 'TEST PREP',
      accent: '#F59E0B',
      body: 'Copy the external store-test session checklist without creating fake evidence, storing credentials, or marking paid access live.',
      buttonLabel: 'COPY TEST SESSION PREP',
      copyText: storeTestPurchaseSessionPrepCopy,
    },
    {
      title: 'STORE EVIDENCE ARCHIVE KIT',
      subtitle: 'Sanitized audit packet and release evidence archive',
      status: 'ARCHIVE',
      accent: '#FBBF24',
      body: 'Copy the evidence archive checklist without exporting tokens, transaction IDs, tester emails, credentials, private screenshots, or treating archived evidence as launch approval.',
      buttonLabel: 'COPY EVIDENCE ARCHIVE',
      copyText: storeEvidenceArchiveCopy,
    },
    {
      title: 'STORE EVIDENCE EXPORT TEMPLATE KIT',
      subtitle: 'Sanitized JSON evidence template',
      status: 'TEMPLATE',
      accent: '#FDE68A',
      body: 'Copy the sanitized evidence JSON template without creating fake proof, exporting tokens, or treating template rows as verified evidence.',
      buttonLabel: 'COPY EVIDENCE TEMPLATE',
      copyText: storeEvidenceExportTemplateCopy,
    },
    {
      title: 'STORE DEMO ACCOUNT KIT',
      subtitle: 'Reviewer-safe demo account notes',
      status: 'REVIEW NOTES',
      accent: '#818CF8',
      body: 'Copy reviewer notes for a synthetic demo account without creating accounts from client code, exposing real users, or unlocking paid access.',
      buttonLabel: 'COPY DEMO ACCOUNT KIT',
      copyText: storeDemoAccountCopy,
    },
    {
      title: 'STORE SCREENSHOT QA KIT',
      subtitle: 'Reviewer-safe screenshots and captions',
      status: 'ASSET QA',
      accent: '#22C55E',
      body: 'Copy screenshot QA prompts that use synthetic demo data only and avoid private data, credentials, purchase tokens, paid-live claims, or store submission side effects.',
      buttonLabel: 'COPY SCREENSHOT QA',
      copyText: storeScreenshotQaCopy,
    },
    {
      title: 'STORE REVIEW PACK',
      subtitle: 'Reviewer notes and policy evidence',
      status: 'PREP ONLY',
      accent: '#14B8A6',
      body: 'Copy store review prep notes without submitting store review, storing credentials, exposing member data, or claiming paid access readiness.',
      buttonLabel: 'COPY STORE REVIEW PACK',
      copyText: storeReviewPackCopy,
    },
    {
      title: 'STORE REVIEW RESPONSE KIT',
      subtitle: 'Reviewer follow-up and rejection reply checklist',
      status: 'RESPONSE READY',
      accent: '#F97316',
      body: 'Copy reviewer follow-up replies without resubmitting, exposing private data, changing purchases, writing entitlements, or claiming paid access is live.',
      buttonLabel: 'COPY REVIEW RESPONSE',
      copyText: storeReviewResponseCopy,
    },
    {
      title: 'STORE REVIEW EVIDENCE GAP TRIAGE KIT',
      subtitle: 'Missing proof, policy, screenshot, and support handoff triage',
      status: 'GAP TRIAGE',
      accent: '#FACC15',
      body: 'Copy an evidence-gap triage checklist without creating fake proof, submitting review, exposing credentials, unlocking paid access, or claiming approval.',
      buttonLabel: 'COPY EVIDENCE GAP TRIAGE',
      copyText: storeReviewEvidenceGapTriageCopy,
    },
    {
      title: 'STORE REVIEW EVIDENCE GAP DECISION REPLY KIT',
      subtitle: 'Approved, waiting, not-ready, and declined evidence-gap replies',
      status: 'GAP REPLIES',
      accent: '#FDE047',
      body: 'Copy evidence-gap decision replies without creating fake proof, submitting review, exposing private data, unlocking paid access, or claiming approval.',
      buttonLabel: 'COPY GAP DECISION REPLIES',
      copyText: storeReviewEvidenceGapDecisionCopy,
    },
    {
      title: 'STORE REVIEW POLICY LINK QA KIT',
      subtitle: 'Privacy, terms, support, data deletion, and permission link checks',
      status: 'POLICY QA',
      accent: '#86EFAC',
      body: 'Copy policy-link QA checks without submitting review, exposing credentials, changing entitlements, or claiming paid access is live.',
      buttonLabel: 'COPY POLICY LINK QA',
      copyText: storeReviewPolicyLinkQaCopy,
    },
    {
      title: 'STORE REVIEW REJECTION ROOT CAUSE KIT',
      subtitle: 'Reviewer feedback, owner, evidence, and policy mapping',
      status: 'ROOT CAUSE',
      accent: '#67E8F9',
      body: 'Copy a rejection root-cause checklist without submitting review, exposing credentials, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY ROOT CAUSE KIT',
      copyText: storeReviewRejectionRootCauseCopy,
    },
    {
      title: 'STORE REVIEWER REPLY PACKET KIT',
      subtitle: 'Final reply, proof references, and owner sign-off',
      status: 'REPLY PACKET',
      accent: '#38BDF8',
      body: 'Copy a reviewer reply packet checklist without submitting review, exposing credentials, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY REPLY PACKET',
      copyText: storeReviewerReplyPacketCopy,
    },
    {
      title: 'STORE REVIEW METADATA DIFF KIT',
      subtitle: 'Listing copy, screenshot, policy, and data-safety diff',
      status: 'METADATA DIFF',
      accent: '#22D3EE',
      body: 'Copy a metadata diff checklist without publishing store copy, exposing credentials, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY METADATA DIFF',
      copyText: storeReviewMetadataDiffCopy,
    },
    {
      title: 'STORE REVIEW DATA SAFETY ALIGNMENT KIT',
      subtitle: 'Privacy labels, data safety, permissions, and policy match',
      status: 'DATA SAFETY',
      accent: '#2DD4BF',
      body: 'Copy a data-safety alignment checklist without publishing privacy labels, exposing credentials, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY DATA SAFETY',
      copyText: storeReviewDataSafetyAlignmentCopy,
    },
    {
      title: 'STORE REVIEW PERMISSION COPY CHECK KIT',
      subtitle: 'Health, media, notification, purchase, and deletion copy',
      status: 'PERMISSION COPY',
      accent: '#5EEAD4',
      body: 'Copy a permission-copy checklist without publishing reviewer notes, exposing credentials, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY PERMISSION COPY',
      copyText: storeReviewPermissionCopyCheckCopy,
    },
    {
      title: 'STORE REVIEW DEMO ACCESS QA KIT',
      subtitle: 'Reviewer demo account, seeded flows, and paid-mode checks',
      status: 'DEMO QA',
      accent: '#99F6E4',
      body: 'Copy a demo-access QA checklist without storing reviewer passwords, exposing member data, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY DEMO QA',
      copyText: storeReviewDemoAccessQaCopy,
    },
    {
      title: 'STORE REVIEW SUPPORT HANDOFF QA KIT',
      subtitle: 'Marketplace support, restore, deletion, and policy routing',
      status: 'SUPPORT QA',
      accent: '#CCFBF1',
      body: 'Copy a support-handoff QA checklist without promising refunds, writing entitlements, changing purchases, or claiming paid access readiness.',
      buttonLabel: 'COPY SUPPORT QA',
      copyText: storeReviewSupportHandoffQaCopy,
    },
    {
      title: 'STORE REVIEW EVIDENCE PACKET INDEX KIT',
      subtitle: 'Reviewed proof, owners, links, and fixed-build index',
      status: 'PACKET INDEX',
      accent: '#E0F2FE',
      body: 'Copy an evidence packet index without creating fake proof, exporting tokens, writing entitlements, or claiming paid access readiness.',
      buttonLabel: 'COPY PACKET INDEX',
      copyText: storeReviewEvidencePacketIndexCopy,
    },
    {
      title: 'STORE REVIEW FINAL SIGN-OFF KIT',
      subtitle: 'Human-reviewed build, evidence, policy, and reply gate',
      status: 'FINAL SIGN-OFF',
      accent: '#DBEAFE',
      body: 'Copy a final sign-off checklist without submitting review, exposing credentials, writing entitlements, or claiming approval.',
      buttonLabel: 'COPY FINAL SIGN-OFF',
      copyText: storeReviewFinalSignoffCopy,
    },
    {
      title: 'STORE REVIEW CONSOLE DRAFT QA KIT',
      subtitle: 'App Store Connect and Play Console draft field check',
      status: 'CONSOLE QA',
      accent: '#BFDBFE',
      body: 'Copy a console-draft QA checklist without submitting review, editing console fields, exposing credentials, or claiming approval.',
      buttonLabel: 'COPY CONSOLE QA',
      copyText: storeReviewConsoleDraftQaCopy,
    },
    {
      title: 'STORE REVIEW SUBMISSION HOLD REASONS KIT',
      subtitle: 'Internal hold reason, owner, proof, and unblock checks',
      status: 'HOLD REASONS',
      accent: '#C7D2FE',
      body: 'Copy a submission-hold checklist without editing console fields, removing holds without proof, writing entitlements, or claiming approval.',
      buttonLabel: 'COPY HOLD REASONS',
      copyText: storeReviewSubmissionHoldReasonsCopy,
    },
    {
      title: 'STORE REVIEW HOLD RELEASE DECISION KIT',
      subtitle: 'Approved, waiting, not-ready, and declined hold decisions',
      status: 'HOLD DECISION',
      accent: '#DDD6FE',
      body: 'Copy hold-release decision replies without removing holds without reviewed proof, editing console fields, writing entitlements, or claiming approval.',
      buttonLabel: 'COPY HOLD DECISIONS',
      copyText: storeReviewHoldReleaseDecisionCopy,
    },
    {
      title: 'STORE REVIEW RESUBMISSION READINESS KIT',
      subtitle: 'Policy fix, evidence, and reviewer-note checklist',
      status: 'RESUBMIT READY',
      accent: '#A3E635',
      body: 'Copy a resubmission readiness checklist without submitting review, exposing credentials, unlocking paid access, or claiming approval.',
      buttonLabel: 'COPY RESUBMISSION READINESS',
      copyText: storeReviewResubmissionCopy,
    },
  ];
}
