export function buildTribeProValueDemandProps(model) {
  const {
    communityHighlightRoundupItems,
    copyText,
    handleProTrialReasonToggle,
    isAdmin,
    isSavingProTrialInterest,
    monthlyRecap,
    proActive,
    proTrialDemandTotal,
    proTrialMessage,
    proTrialObjectionReplyCopy,
    proTrialPitchCopy,
    proTrialSummary,
    proValueNextAction,
    selectedProTrialReasonIds,
    storyPostingChecklistCopy,
    topProTrialReason,
    totalChallengePoints,
    valueProofStoryCopy,
    weeklyReport,
  } = model;

  return {
    communityHighlightRoundupItems,
    copyText,
    isAdmin,
    isSavingProTrialInterest,
    monthlyRecap,
    onProTrialReasonToggle: handleProTrialReasonToggle,
    proActive,
    proTrialDemandTotal,
    proTrialMessage,
    proTrialObjectionReplyCopy,
    proTrialPitchCopy,
    proTrialSummary,
    proValueNextAction,
    selectedProTrialReasonIds,
    storyPostingChecklistCopy,
    topProTrialReason,
    totalChallengePoints,
    valueProofStoryCopy,
    weeklyReport,
  };
}
