export function buildTribeProValueDemandProps(model) {
  const {
    communityHighlightRoundupItems,
    challengePackLaunchCopy,
    challengePackLaunchQaCopy,
    challengePackObjectionReplyCopy,
    challengePackSupportTriageCopy,
    challengePackStoreReadinessScriptCopy,
    copyText,
    approvedProTrialReviews,
    handleProTrialReasonToggle,
    handleProTrialReviewDecision,
    handleProTrialReviewSubmit,
    isAdmin,
    isSavingProTrialInterest,
    isSubmittingProTrialReview,
    monthlyRecap,
    proActive,
    proTrialDemandTotal,
    proTrialMessage,
    proTrialObjectionReplyCopy,
    proTrialPitchCopy,
    proTrialLaunchQaCopy,
    proTrialStoreReadinessScriptCopy,
    proTrialSupportEscalationCopy,
    proTrialReviewMessage,
    proTrialReviewNotes,
    proTrialReviewQueue,
    proTrialSummary,
    proValueNextAction,
    selectedProTrialReasonIds,
    setProTrialReviewNotes,
    storyPostingChecklistCopy,
    reviewingProTrialReviewId,
    topProTrialReason,
    totalChallengePoints,
    valueProofStoryCopy,
    weeklyReport,
  } = model;

  return {
    communityHighlightRoundupItems,
    challengePackLaunchCopy,
    challengePackLaunchQaCopy,
    challengePackObjectionReplyCopy,
    challengePackSupportTriageCopy,
    challengePackStoreReadinessScriptCopy,
    copyText,
    approvedProTrialReviews,
    isAdmin,
    isSavingProTrialInterest,
    isSubmittingProTrialReview,
    monthlyRecap,
    onProTrialReasonToggle: handleProTrialReasonToggle,
    proActive,
    proTrialDemandTotal,
    proTrialMessage,
    proTrialObjectionReplyCopy,
    proTrialPitchCopy,
    proTrialLaunchQaCopy,
    proTrialStoreReadinessScriptCopy,
    proTrialSupportEscalationCopy,
    proTrialReviewMessage,
    proTrialReviewNotes,
    proTrialReviewQueue,
    proTrialSummary,
    proValueNextAction,
    selectedProTrialReasonIds,
    setProTrialReviewNotes,
    storyPostingChecklistCopy,
    onProTrialReviewDecision: handleProTrialReviewDecision,
    onProTrialReviewSubmit: handleProTrialReviewSubmit,
    reviewingProTrialReviewId,
    topProTrialReason,
    totalChallengePoints,
    valueProofStoryCopy,
    weeklyReport,
  };
}
