export function buildTribeProCommerceActionProps(model) {
  const {
    challengePackTitle,
    checkoutProductId,
    entitlementRecoveryDecisionReplyCopy,
    entitlementRecoveryReviewNotes,
    entitlementRecoveryReviewQueue,
    handleCheckout,
    handleEntitlementRecoveryRequest,
    handleEntitlementRecoveryReview,
    handleRecordStoreTestEvidence,
    handleReviewStoreTestEvidence,
    handlePaidLaunchDecisionReviewDecision,
    handlePaidLaunchDecisionReviewSubmit,
    handleStoreReviewResponseReviewDecision,
    handleStoreReviewResponseReviewSubmit,
    handleSupportRefundReadinessReviewDecision,
    handleSupportRefundReadinessReviewSubmit,
    handleSyncPurchases,
    handleValidationReadinessCheck,
    isAdmin,
    isCheckingValidationReadiness,
    isPackUnlocked,
    isRequestingEntitlementRecovery,
    isSubmittingPaidLaunchDecisionReview,
    isSubmittingStoreReviewResponseReview,
    isSubmittingSupportRefundReadinessReview,
    paidLaunchDecisionReplyCopy,
    paidLaunchDecisionStatus,
    recordingStoreTestEvidenceId,
    reviewingPaidLaunchDecisionReviewId,
    reviewingEntitlementRecoveryRequestId,
    reviewingStoreReviewResponseReviewId,
    reviewingSupportRefundReadinessReviewId,
    reviewingStoreTestEvidenceId,
    approvedPaidLaunchDecisionReviews,
    approvedSupportRefundReadinessReviews,
    approvedStoreReviewResponseReviews,
    setEntitlementRecoveryReviewNotes,
    setPaidLaunchDecisionReviewNotes,
    setStoreReviewResponseReviewNotes,
    setSupportRefundReadinessReviewNotes,
    setStoreTestEvidenceReviewNotes,
    storeSupportCopyCards,
    storeTestEvidenceCases,
    storeTestEvidenceDecisionReplyCopy,
    storeTestEvidenceLog,
    storeTestEvidenceMessage,
    storeTestEvidenceReviewNotes,
    paidLaunchDecisionReviewMessage,
    paidLaunchDecisionReviewNotes,
    paidLaunchDecisionReviewQueue,
    storeReviewResponseReviewMessage,
    storeReviewResponseReviewNotes,
    storeReviewResponseReviewQueue,
    supportRefundReadinessReviewMessage,
    supportRefundReadinessReviewNotes,
    supportRefundReadinessReviewQueue,
    validationReadinessMessage,
  } = model;

  return {
    challengePackTitle,
    checkoutProductId,
    entitlementRecoveryDecisionReplyCopy,
    entitlementRecoveryReviewNotes,
    approvedPaidLaunchDecisionReviews,
    entitlementRecoveryReviewQueue,
    approvedSupportRefundReadinessReviews,
    approvedStoreReviewResponseReviews,
    isAdmin,
    isCheckingValidationReadiness,
    isPackUnlocked,
    isRequestingEntitlementRecovery,
    isSubmittingPaidLaunchDecisionReview,
    isSubmittingStoreReviewResponseReview,
    isSubmittingSupportRefundReadinessReview,
    onCheckout: handleCheckout,
    onEntitlementRecoveryRequest: handleEntitlementRecoveryRequest,
    onEntitlementRecoveryReview: handleEntitlementRecoveryReview,
    onRecordStoreTestEvidence: handleRecordStoreTestEvidence,
    onPaidLaunchDecisionReviewDecision: handlePaidLaunchDecisionReviewDecision,
    onPaidLaunchDecisionReviewSubmit: handlePaidLaunchDecisionReviewSubmit,
    onReviewStoreTestEvidence: handleReviewStoreTestEvidence,
    onStoreReviewResponseReviewDecision: handleStoreReviewResponseReviewDecision,
    onStoreReviewResponseReviewSubmit: handleStoreReviewResponseReviewSubmit,
    onSupportRefundReadinessReviewDecision: handleSupportRefundReadinessReviewDecision,
    onSupportRefundReadinessReviewSubmit: handleSupportRefundReadinessReviewSubmit,
    onSyncPurchases: handleSyncPurchases,
    onValidationReadinessCheck: handleValidationReadinessCheck,
    paidLaunchDecisionReplyCopy,
    paidLaunchDecisionStatus,
    recordingStoreTestEvidenceId,
    reviewingPaidLaunchDecisionReviewId,
    reviewingEntitlementRecoveryRequestId,
    reviewingStoreReviewResponseReviewId,
    reviewingSupportRefundReadinessReviewId,
    reviewingStoreTestEvidenceId,
    setEntitlementRecoveryReviewNotes,
    setPaidLaunchDecisionReviewNotes,
    setStoreReviewResponseReviewNotes,
    setSupportRefundReadinessReviewNotes,
    setStoreTestEvidenceReviewNotes,
    storeSupportCopyCards,
    storeTestEvidenceCases,
    storeTestEvidenceDecisionReplyCopy,
    storeTestEvidenceLog,
    storeTestEvidenceMessage,
    storeTestEvidenceReviewNotes,
    paidLaunchDecisionReviewMessage,
    paidLaunchDecisionReviewNotes,
    paidLaunchDecisionReviewQueue,
    storeReviewResponseReviewMessage,
    storeReviewResponseReviewNotes,
    storeReviewResponseReviewQueue,
    supportRefundReadinessReviewMessage,
    supportRefundReadinessReviewNotes,
    supportRefundReadinessReviewQueue,
    validationReadinessMessage,
  };
}
