import { buildCreatorHostingApplicationActionHandlers } from './creatorHostingApplicationActionHandlers';
import { buildCreatorBrandedPageActionHandlers } from './creatorBrandedPageActionHandlers';
import { buildCreatorChallengeTemplateDraftActionHandlers } from './creatorChallengeTemplateDraftActionHandlers';
import { buildCreatorLeaderboardSnapshotActionHandlers } from './creatorLeaderboardSnapshotActionHandlers';
import { buildCreatorPrivateInviteLaunchActionHandlers } from './creatorPrivateInviteLaunchActionHandlers';
import { buildCreatorProfileActionHandlers } from './creatorProfileActionHandlers';

export default function useCreatorRevenueActions({
  creatorAnalytics,
  creatorBio,
  creatorCtaUrl,
  creatorEnabled,
  creatorBrandedPageReviewNotes,
  creatorHostingApplicationReviewNotes,
  creatorLeaderboardSnapshotReviewNotes,
  creatorPrivateInviteLaunchReviewNotes,
  creatorLaunchChallenge,
  creatorRevenueShareInterest,
  creatorSpecialty,
  creatorTemplateDraftReviewNotes,
  isAdmin,
  isSubmittingCreatorBrandedPage,
  isSubmittingCreatorHostingApplication,
  isSubmittingCreatorLeaderboardSnapshot,
  isSubmittingCreatorPrivateInviteLaunch,
  isSubmittingCreatorTemplateDraft,
  proActive,
  profile,
  setPublishedCreatorBrandedPages,
  setPublishedCreatorChallengeTemplates,
  setPublishedCreatorLeaderboardSnapshots,
  setApprovedCreatorPrivateInviteLaunches,
  reviewingCreatorHostingApplicationId,
  reviewingCreatorBrandedPageId,
  reviewingCreatorLeaderboardSnapshotId,
  reviewingCreatorPrivateInviteLaunchId,
  reviewingCreatorTemplateDraftId,
  setCreatorLeaderboardSnapshotMessage,
  setCreatorLeaderboardSnapshotReviewQueue,
  setCreatorBrandedPageMessage,
  setCreatorBrandedPageReviewQueue,
  setCreatorPrivateInviteLaunchMessage,
  setCreatorPrivateInviteLaunchReviewQueue,
  setCreatorHostingApplicationMessage,
  setCreatorHostingApplicationReviewQueue,
  setCreatorMessage,
  setCreatorTemplateDraftMessage,
  setCreatorTemplateDraftReviewQueue,
  setIsSubmittingCreatorLeaderboardSnapshot,
  setIsSubmittingCreatorBrandedPage,
  setIsSubmittingCreatorPrivateInviteLaunch,
  setIsSavingCreator,
  setIsSubmittingCreatorHostingApplication,
  setIsSubmittingCreatorTemplateDraft,
  setProfile,
  setReviewingCreatorHostingApplicationId,
  setReviewingCreatorBrandedPageId,
  setReviewingCreatorLeaderboardSnapshotId,
  setReviewingCreatorPrivateInviteLaunchId,
  setReviewingCreatorTemplateDraftId,
  user,
  onProfileUpdated,
}) {
  const creatorProfileHandlers = buildCreatorProfileActionHandlers({
    creatorBio,
    creatorCtaUrl,
    creatorEnabled,
    creatorRevenueShareInterest,
    creatorSpecialty,
    proActive,
    profile,
    setCreatorMessage,
    setIsSavingCreator,
    setProfile,
    user,
    onProfileUpdated,
  });

  const creatorHostingApplicationHandlers = buildCreatorHostingApplicationActionHandlers({
    creatorAnalytics,
    creatorEnabled,
    creatorHostingApplicationReviewNotes,
    creatorRevenueShareInterest,
    isAdmin,
    isSubmittingCreatorHostingApplication,
    proActive,
    profile,
    reviewingCreatorHostingApplicationId,
    setCreatorHostingApplicationMessage,
    setCreatorHostingApplicationReviewQueue,
    setIsSubmittingCreatorHostingApplication,
    setReviewingCreatorHostingApplicationId,
    user,
  });
  const creatorTemplateDraftHandlers = buildCreatorChallengeTemplateDraftActionHandlers({
    creatorAnalytics,
    creatorEnabled,
    creatorLaunchChallenge,
    creatorTemplateDraftReviewNotes,
    isAdmin,
    isSubmittingCreatorTemplateDraft,
    proActive,
    profile,
    reviewingCreatorTemplateDraftId,
    setCreatorTemplateDraftMessage,
    setCreatorTemplateDraftReviewQueue,
    setPublishedCreatorChallengeTemplates,
    setIsSubmittingCreatorTemplateDraft,
    setReviewingCreatorTemplateDraftId,
    user,
  });
  const creatorLeaderboardSnapshotHandlers = buildCreatorLeaderboardSnapshotActionHandlers({
    creatorEnabled,
    creatorLeaderboardSnapshotReviewNotes,
    isAdmin,
    isSubmittingCreatorLeaderboardSnapshot,
    proActive,
    reviewingCreatorLeaderboardSnapshotId,
    setCreatorLeaderboardSnapshotMessage,
    setCreatorLeaderboardSnapshotReviewQueue,
    setIsSubmittingCreatorLeaderboardSnapshot,
    setPublishedCreatorLeaderboardSnapshots,
    setReviewingCreatorLeaderboardSnapshotId,
    user,
  });
  const creatorBrandedPageHandlers = buildCreatorBrandedPageActionHandlers({
    creatorBrandedPageReviewNotes,
    creatorEnabled,
    isAdmin,
    isSubmittingCreatorBrandedPage,
    proActive,
    reviewingCreatorBrandedPageId,
    setCreatorBrandedPageMessage,
    setCreatorBrandedPageReviewQueue,
    setIsSubmittingCreatorBrandedPage,
    setPublishedCreatorBrandedPages,
    setReviewingCreatorBrandedPageId,
    user,
  });
  const creatorPrivateInviteLaunchHandlers = buildCreatorPrivateInviteLaunchActionHandlers({
    creatorEnabled,
    creatorPrivateInviteLaunchReviewNotes,
    isAdmin,
    isSubmittingCreatorPrivateInviteLaunch,
    proActive,
    reviewingCreatorPrivateInviteLaunchId,
    setApprovedCreatorPrivateInviteLaunches,
    setCreatorPrivateInviteLaunchMessage,
    setCreatorPrivateInviteLaunchReviewQueue,
    setIsSubmittingCreatorPrivateInviteLaunch,
    setReviewingCreatorPrivateInviteLaunchId,
    user,
  });

  return {
    ...creatorBrandedPageHandlers,
    ...creatorHostingApplicationHandlers,
    ...creatorLeaderboardSnapshotHandlers,
    ...creatorPrivateInviteLaunchHandlers,
    ...creatorProfileHandlers,
    ...creatorTemplateDraftHandlers,
  };
}
