export function buildWeeklyCampaignMarketingProps(model) {
  const {
    campaignPerformanceSummary,
    dmKeywordCopy,
    featureReviewQueue,
    instagramContentCalendarCopy,
    isAdmin,
    recommendedLaunchExperiment,
    referralJoins,
    weeklyCampaignCaptionBankCopy,
    weeklyCampaignCollabCopyCards,
    weeklyCampaignCommentReplyCopy,
    weeklyCampaignCompletionRecapStoryCopy,
    weeklyCampaignCountdownStoryCopy,
    weeklyCampaignExperimentBriefCopy,
    weeklyCampaignFaqCarouselCopy,
    weeklyCampaignLaunchCardCopy,
    weeklyCampaignLiveQaCopy,
    weeklyCampaignLiveRecapCopy,
    weeklyCampaignMidweekCheckInStoryCopy,
    weeklyCampaignNextWeekTeaserStoryCopy,
    weeklyCampaignPartnerPerkTeaserStoryCopy,
    weeklyCampaignPollReviewCopy,
    weeklyCampaignPreflightCopy,
    weeklyCampaignPrompt,
    weeklyCampaignReviewCopy,
    weeklyCampaignStartDayStoryCopy,
    weeklyCampaignStoryboardCopy,
    weeklyCampaignStoryPollCopy,
    weeklyCampaignWeekendPushStoryCopy,
  } = model;

  return {
    campaignPerformanceSummary,
    creatorEnabled: model.creatorEnabled,
    dmKeywordCopy,
    featureReviewQueue,
    instagramContentCalendarCopy,
    isAdmin,
    recommendedLaunchExperiment,
    referralJoins,
    weeklyCampaignCaptionBankCopy,
    weeklyCampaignCollabCopyCards,
    weeklyCampaignCommentReplyCopy,
    weeklyCampaignCompletionRecapStoryCopy,
    weeklyCampaignCountdownStoryCopy,
    weeklyCampaignExperimentBriefCopy,
    weeklyCampaignFaqCarouselCopy,
    weeklyCampaignLaunchCardCopy,
    weeklyCampaignLiveQaCopy,
    weeklyCampaignLiveRecapCopy,
    weeklyCampaignMidweekCheckInStoryCopy,
    weeklyCampaignNextWeekTeaserStoryCopy,
    weeklyCampaignPartnerPerkTeaserStoryCopy,
    weeklyCampaignPollReviewCopy,
    weeklyCampaignPreflightCopy,
    weeklyCampaignPrompt,
    weeklyCampaignReviewCopy,
    weeklyCampaignStartDayStoryCopy,
    weeklyCampaignStoryboardCopy,
    weeklyCampaignStoryPollCopy,
    weeklyCampaignWeekendPushStoryCopy,
  };
}
