import { GOLD, DM_KEYWORD_PROMPTS } from './profileConstants';

export function buildWeeklyCampaignMetricKitSections({
  campaignPerformanceSummary,
  featureReviewQueue,
  recommendedLaunchExperiment,
  referralJoins,
  weeklyCampaignExperimentBriefCopy,
  weeklyCampaignPreflightCopy,
  weeklyCampaignPrompt,
  weeklyCampaignReviewCopy,
  weeklyCampaignStoryboardCopy,
}) {
  return [
    {
      title: 'Weekly Campaign Preflight Checklist',
      subtitle: 'Manual launch readiness before posting',
      status: 'CHECKLIST',
      accent: '#14B8A6',
      background: 'rgba(20,184,166,0.05)',
      border: '1px solid rgba(20,184,166,0.16)',
      metrics: [
        ['CARD', weeklyCampaignPrompt.hashtag],
        ['DM', DM_KEYWORD_PROMPTS.length],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Confirm card copy, manual DM replies, content calendar, referral copy, consent-reviewed UGC, and first-party review metrics before the weekly push.',
      buttonLabel: 'COPY CAMPAIGN PREFLIGHT',
      copyText: weeklyCampaignPreflightCopy,
    },
    {
      title: 'Weekly Campaign Review Kit',
      subtitle: 'First-party weekly campaign review',
      status: 'REVIEW',
      accent: GOLD,
      background: 'rgba(251,191,36,0.05)',
      border: '1px solid rgba(251,191,36,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['DM', DM_KEYWORD_PROMPTS.length],
      ],
      body: "Review challenge joins, referral movement, consent-cleared UGC, manual DM copy, and share-card usage before shaping next week's push.",
      buttonLabel: 'COPY CAMPAIGN REVIEW',
      copyText: weeklyCampaignReviewCopy,
    },
    {
      title: 'Weekly Campaign Storyboard Kit',
      subtitle: 'Reels, Stories, and carousel outline',
      status: 'STORYBOARD',
      accent: '#F472B6',
      background: 'rgba(244,114,182,0.05)',
      border: '1px solid rgba(244,114,182,0.16)',
      metrics: [
        ['REEL', '4 BEATS'],
        ['STORY', '4 FRAMES'],
        ['POST', '5 SLIDES'],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Copy a manual Reel hook, Story frame plan, carousel outline, hashtag, and consent-safe publishing guardrails for this week's campaign.",
      buttonLabel: 'COPY STORYBOARD KIT',
      copyText: weeklyCampaignStoryboardCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief Kit',
      subtitle: 'Manual experiment from weekly campaign signals',
      status: recommendedLaunchExperiment.label.toUpperCase(),
      accent: '#C084FC',
      background: 'rgba(192,132,252,0.05)',
      border: '1px solid rgba(192,132,252,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['SIGNAL', recommendedLaunchExperiment.signal],
        ['WEEK', weeklyCampaignPrompt.week],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Connect this week's campaign CTA to the recommended manual experiment and review only first-party app movement afterward.",
      buttonLabel: 'COPY EXPERIMENT BRIEF',
      copyText: weeklyCampaignExperimentBriefCopy,
    },
  ];
}
