import { buildSimpleWeeklyCampaignCopyCards } from './weeklyCampaignCardCopy';
import { buildWeeklyCampaignMetricKitSections } from './weeklyCampaignMetricKitSections';
import { buildWeeklyCampaignOperatingSummary } from './weeklyCampaignOperatingSummary';

export function buildWeeklyCampaignMarketingSectionData({
  campaignPerformanceSummary,
  dmKeywordCopy,
  featureReviewQueue,
  instagramContentCalendarCopy,
  launchRetrospectiveReadinessScriptCopy,
  recommendedLaunchExperiment,
  referralJoins,
  weeklyCampaignCaptionBankCopy,
  weeklyCampaignCollabCopyCards,
  weeklyCampaignCommentReplyCopy,
  weeklyCampaignCompletionRecapStoryCopy,
  weeklyCampaignCountdownStoryCopy,
  weeklyCampaignExperimentBriefCopy,
  weeklyCampaignFaqCarouselCopy,
  weeklyCampaignFirstDayMonitorCopy,
  weeklyCampaignLiveQaCopy,
  weeklyCampaignLiveRecapCopy,
  weeklyCampaignMidweekCheckInStoryCopy,
  weeklyCampaignNextWeekTeaserStoryCopy,
  weeklyCampaignPartnerPerkTeaserStoryCopy,
  weeklyCampaignPollReviewCopy,
  weeklyCampaignPreflightCopy,
  weeklyCampaignPrompt,
  weeklyCampaignLaunchCardCopy,
  weeklyCampaignLaunchCopyQaCopy,
  weeklyCampaignReviewCopy,
  weeklyCampaignStartDayStoryCopy,
  weeklyCampaignStoryboardCopy,
  weeklyCampaignStoryPollCopy,
  weeklyCampaignWeekendPushStoryCopy,
}) {
  return {
    dmKeywordSectionProps: {
      dmKeywordCopy,
    },
    instagramCalendarSectionProps: {
      instagramContentCalendarCopy,
    },
    launchCardSectionProps: {
      weeklyCampaignLaunchCardCopy,
      weeklyCampaignPrompt,
    },
    operatingSummaryProps: buildWeeklyCampaignOperatingSummary({
      campaignPerformanceSummary,
      featureReviewQueue,
      recommendedLaunchExperiment,
      referralJoins,
      weeklyCampaignPrompt,
    }),
    simpleWeeklyCampaignCopyCards: buildSimpleWeeklyCampaignCopyCards({
      weeklyCampaignPrompt,
      weeklyCampaignCommentReplyCopy,
      weeklyCampaignCountdownStoryCopy,
      weeklyCampaignStartDayStoryCopy,
      weeklyCampaignMidweekCheckInStoryCopy,
      weeklyCampaignWeekendPushStoryCopy,
      weeklyCampaignCompletionRecapStoryCopy,
      weeklyCampaignNextWeekTeaserStoryCopy,
      weeklyCampaignPartnerPerkTeaserStoryCopy,
      weeklyCampaignStoryPollCopy,
      weeklyCampaignPollReviewCopy,
      weeklyCampaignLiveQaCopy,
      weeklyCampaignLiveRecapCopy,
      weeklyCampaignFaqCarouselCopy,
      weeklyCampaignCaptionBankCopy,
    }),
    weeklyCampaignMetricKitSections: buildWeeklyCampaignMetricKitSections({
      campaignPerformanceSummary,
      featureReviewQueue,
      recommendedLaunchExperiment,
      referralJoins,
      launchRetrospectiveReadinessScriptCopy,
      weeklyCampaignExperimentBriefCopy,
      weeklyCampaignFirstDayMonitorCopy,
      weeklyCampaignLaunchCopyQaCopy,
      weeklyCampaignPreflightCopy,
      weeklyCampaignPrompt,
      weeklyCampaignReviewCopy,
      weeklyCampaignStoryboardCopy,
    }),
    weeklyCampaignCollabCopyCards,
  };
}
