import { buildWeeklyCampaignCollabCopyCards } from './weeklyCampaignCollabCopyCards';

export function buildWeeklyCampaignEngagementCopy({
  weeklyCampaignPrompt,
  recommendedLaunchExperiment,
  campaignPerformanceSummary,
  referralJoins,
  featureReviewQueue,
  supportReviewQueue = [],
}) {
  const weeklyCampaignCommentReplyCopy = `Rise With The Tribe Weekly Campaign Comment Reply Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual public replies:\nQ: How do I join?\nA: Pick this week's Rise With The Tribe challenge in the app, log your first honest session, and use ${weeklyCampaignPrompt.hashtag} when you share your start.\n\nQ: I missed a day. Should I restart?\nA: Come back today. The goal is return speed, not perfect weeks. Log one session, rebuild the streak, and tag @risewiththetribe when you are back in motion.\n\nQ: Is Pro or a paid pack live?\nA: Not yet. We are validating value through the free challenge loop, Pro Trial Interest, and first-party campaign signals before paid access is promoted.\n\nQ: Can I be featured?\nA: Yes. Submit your win through Feature Me in the app with consent, a clear story, and an optional Instagram handle so it can be reviewed manually.\n\nThis is a manual public comment reply kit only. Do not auto-reply, scrape comments, scrape DMs, store inbound comments, store inbound DMs, add tracking pixels, create attribution records, export per-user activity, share user content without consent, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignCountdownStoryCopy = `Rise With The Tribe Weekly Campaign Countdown Story Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: Countdown sticker - ${weeklyCampaignPrompt.name} starts soon.\nFrame 2: Why it matters - One honest session can restart momentum.\nFrame 3: Join CTA - Open Rise With The Tribe and join this week's challenge before the first log.\nFrame 4: Accountability prompt - Tag one person who should start with you.\nFrame 5: Start-day reminder - Log your first session in the app and use ${weeklyCampaignPrompt.hashtag} if you share.\n\nSticker text:\nCountdown: ${weeklyCampaignPrompt.name}\nQuestion: What would make you show up on day one?\nPoll: Starting with us? / Need a nudge\n\nReview note:\nUse visible Story engagement as directional content feedback only. Confirm launch momentum with first-party app joins, logs, referrals, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual countdown Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story interactions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignStartDayStoryCopy = `Rise With The Tribe Weekly Campaign Start-Day Story Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: It starts today - ${weeklyCampaignPrompt.name} is open inside Rise With The Tribe.\nFrame 2: First action - Pick one honest session and log it before the day ends.\nFrame 3: Accountability - Invite one person or tag @risewiththetribe if you share your start.\nFrame 4: Proof - Your streak, points, badges, referrals, and challenge progress move only when the app log is saved.\nFrame 5: Close - Join, log, and use ${weeklyCampaignPrompt.hashtag} when your first session is done.\n\nSticker text:\nPoll: Logged yet? / Starting soon\nQuestion: What are you logging first today?\nCTA sticker: Open Rise With The Tribe\n\nReview note:\nUse Story reactions as directional content feedback only. Confirm start-day momentum with first-party challenge joins, saved activity logs, referrals, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual start-day Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignMidweekCheckInStoryCopy = `Rise With The Tribe Weekly Campaign Midweek Check-In Story Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: Midweek check-in - Are you still in ${weeklyCampaignPrompt.name}?\nFrame 2: Comeback lane - If you missed a day, log one honest session today.\nFrame 3: Momentum lane - If you are on track, invite one accountability partner before the weekend.\nFrame 4: App-first proof - Streaks, badges, referrals, and challenge progress move when the app log is saved.\nFrame 5: CTA - Open Rise With The Tribe, log today, and use ${weeklyCampaignPrompt.hashtag} if you share the comeback.\n\nSticker text:\nPoll: Still in? / Coming back today\nQuestion: What would make the next log easier?\nCTA sticker: Log today's session\n\nReview note:\nUse visible midweek reactions as directional content feedback only. Confirm re-engagement with first-party saved activity logs, challenge progress, referral joins, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual midweek check-in Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignWeekendPushStoryCopy = `Rise With The Tribe Weekly Campaign Weekend Push Story Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: Weekend push - ${weeklyCampaignPrompt.name} is still open.\nFrame 2: Finish-line action - Log one session before the weekend gets away from you.\nFrame 3: Accountability - Invite one person who needs a reset before Monday.\nFrame 4: Community proof - Submit Feature Me only if you want your win reviewed with consent.\nFrame 5: CTA - Open Rise With The Tribe, save the log, and use ${weeklyCampaignPrompt.hashtag} if you share the finish.\n\nSticker text:\nPoll: Weekend log done? / Doing it today\nQuestion: What is your finish-line session?\nCTA sticker: Save the weekend log\n\nReview note:\nUse visible weekend reactions as directional content feedback only. Confirm finish-line momentum with first-party saved activity logs, challenge completion progress, referral joins, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual weekend push Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignCompletionRecapStoryCopy = `Rise With The Tribe Weekly Campaign Completion Recap Story Kit:\n\nCampaign reviewed: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: Weekly recap - ${weeklyCampaignPrompt.name} helped the tribe choose one honest session at a time.\nFrame 2: Celebrate effort - Show aggregate wins only: logs saved, comeback stories submitted, referrals joined, or challenge progress improved.\nFrame 3: Feature Me CTA - Got a win? Submit Feature Me inside the app so consent and context are reviewed first.\nFrame 4: Next step - Invite one accountability partner into the next weekly challenge.\nFrame 5: Close - Open Rise With The Tribe, review your history, and use ${weeklyCampaignPrompt.hashtag} only if you choose to share.\n\nSticker text:\nPoll: Finished strong? / Coming back next week\nQuestion: What should next week's challenge help with?\nCTA sticker: Submit Feature Me in the app\n\nReview note:\nUse completion reactions as directional content feedback only. Confirm weekly recap lessons with first-party saved activity logs, challenge completions, referral joins, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual completion recap Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, share user wins without Feature Me consent, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignNextWeekTeaserStoryCopy = `Rise With The Tribe Weekly Campaign Next-Week Teaser Story Kit:\n\nCampaign closing: ${weeklyCampaignPrompt.name}\nCurrent week: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual Story sequence:\nFrame 1: Next week is coming - The next Rise With The Tribe challenge is being shaped now.\nFrame 2: Choose the lane - Ask the audience which consistency obstacle should become the next prompt.\nFrame 3: App-first CTA - Open Rise With The Tribe and join the current challenge or invite one accountability partner before the next one drops.\nFrame 4: Signal check - Use app joins, logs, referrals, Feature Me submissions, and saved interest to choose the next launch angle.\nFrame 5: Close - Watch for the next weekly challenge, and use ${weeklyCampaignPrompt.hashtag} only if you choose to share your current progress.\n\nSticker text:\nPoll: Next challenge? Comeback / Discipline\nQuestion: What should next week's challenge help you solve?\nCTA sticker: Join inside the app\n\nReview note:\nUse teaser reactions as directional content feedback only. Confirm next-week direction with first-party saved activity logs, challenge joins, referral joins, Feature Me submissions, saved Pro interest, saved creator interest, or saved partner interest.\n\nThis is a manual next-week teaser Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignPartnerPerkTeaserStoryCopy = `Rise With The Tribe Weekly Campaign Partner Perk Teaser Story Kit:\n\nCampaign context: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: Partner Perk Poll\n\nManual Story sequence:\nFrame 1: Partner perk check - What kind of aligned reward would help the tribe stay consistent?\nFrame 2: Perk lanes - Recovery, apparel, gym/studio, meal prep, wearable, or accountability support.\nFrame 3: App-first CTA - Save partner interest inside Rise With The Tribe so demand is reviewed first-party.\nFrame 4: Review boundary - Use only aggregate saved interest and app movement before contacting any partner.\nFrame 5: Close - Keep logging ${weeklyCampaignPrompt.name}; perks should support consistency, not distract from the challenge.\n\nSticker text:\nPoll: Partner perk? Recovery / Gear\nQuestion: What perk would genuinely help consistency?\nCTA sticker: Save partner interest in the app\n\nReview note:\nUse visible perk reactions as directional content feedback only. Confirm partner direction with first-party saved partner interest, saved activity logs, challenge joins, referrals, Feature Me submissions, saved Pro interest, or saved creator interest.\n\nThis is a manual partner perk teaser Story kit only. Do not auto-post, schedule Stories, scrape Story responses, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, create affiliate links, create partner payouts, contact partners as if demand is validated, add tracking pixels, export per-user activity, treat Story reactions as app consent, share private responses, imply paid access or perks are live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignStoryPollCopy = `Rise With The Tribe Weekly Campaign Story Poll Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\nCTA: ${weeklyCampaignPrompt.cta}\n\nStory sticker prompts:\nPoll 1: Are you joining this week's challenge?\nOptions: I'm in / Need a comeback\n\nPoll 2: What would help you show up today?\nOptions: Accountability / Clear plan\n\nQuiz: What should we build next for the tribe?\nOptions: Pro reports / Challenge packs / Creator challenges / Partner perks\n\nQuestion sticker: What is one thing making consistency hard this week?\n\nFollow-up CTA:\nVote on the Story, then join the challenge inside Rise With The Tribe so your progress, referrals, badges, and feature submissions are tracked first-party in the app.\n\nThis is a manual Story poll kit only. Do not auto-post, scrape Story responses, scrape comments, scrape DMs, store inbound replies, add tracking pixels, create attribution records, export per-user activity, treat Instagram votes as app consent, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignPollReviewCopy = `Rise With The Tribe Weekly Campaign Poll Review Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\nFirst-party follow-up CTA: ${weeklyCampaignPrompt.cta}\n\nManual review prompts:\n[ ] What Story option got the strongest visible response?\n[ ] Did voters ask for accountability, a clearer plan, Pro reports, challenge packs, creator challenges, or partner perks?\n[ ] Which response should become the next Reel hook, carousel topic, or app challenge CTA?\n[ ] Which first-party app signal should confirm the reaction: challenge joins, referral joins, feature submissions, saved Pro interest, saved partner interest, or share-card usage?\n[ ] What should be posted next without exposing individual voters?\n\nDecision note:\nUse Instagram poll reactions as directional creator feedback only. Confirm product and monetization decisions with first-party app movement before changing paid copy, entitlements, products, partner offers, or roadmap priority.\n\nThis is a manual poll review kit only. Do not scrape Story responses, store Instagram voter identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Instagram votes as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignLiveQaCopy = `Rise With The Tribe Weekly Campaign Live Q&A Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nLive setup:\n[ ] Open with one honest lesson from this week's challenge.\n[ ] Invite viewers to join the app challenge, log one session, and use ${weeklyCampaignPrompt.hashtag} if they share.\n[ ] Answer questions with app-first actions: join a challenge, log progress, invite one partner, submit Feature Me with consent, or save Pro/creator/partner interest.\n[ ] Turn repeated questions into the next Reel hook, carousel, Caption Bank angle, or Comment Reply Kit update.\n\nQuestion lanes:\nQ: How do I start?\nA: Pick this week's challenge in Rise With The Tribe and log one honest session today.\n\nQ: What if I missed days?\nA: Come back with the next log. The app rewards return speed, streak rebuilds, and visible consistency.\n\nQ: Are paid packs, Pro, or creator hosting live?\nA: Not yet. We are validating value through first-party app signals before paid access, creator hosting, or partner campaigns are promoted.\n\nClose:\nDrop your next session in the app, tag @risewiththetribe if you share it, and bring one accountability partner into ${weeklyCampaignPrompt.name}.\n\nThis is a manual Live Q&A kit only. Do not auto-host, record private replies, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Live questions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignLiveRecapCopy = `Rise With The Tribe Weekly Campaign Live Recap Kit:\n\nCampaign reviewed: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\n\nManual recap prompts:\n[ ] What question came up more than once?\n[ ] Which app-first action answered it best: join a challenge, log one session, invite a partner, submit Feature Me with consent, save Pro interest, save creator interest, or save partner interest?\n[ ] Which first-party signal should confirm momentum after the Live: challenge joins, referral joins, feature submissions, saved interest, or share-card usage?\n[ ] What should become the next Reel hook, carousel slide, Story poll, Caption Bank angle, or Comment Reply Kit update?\n[ ] What should not be repeated because it implied paid access, medical outcomes, pressure, or private-user detail?\n\nPublic recap copy:\nTonight's Live came back to one simple idea: consistency gets easier when the next action is visible. Join ${weeklyCampaignPrompt.name}, log one honest session in Rise With The Tribe, and use ${weeklyCampaignPrompt.hashtag} if you share your start.\n\nDecision note:\nUse the Live as directional content feedback only. Confirm product, creator, partner, and paid-feature decisions with first-party app movement before changing roadmap priority or launch copy.\n\nThis is a manual Live recap kit only. Do not auto-post, record private replies, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Live questions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignFaqCarouselCopy = `Rise With The Tribe Weekly Campaign FAQ Carousel Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCTA: ${weeklyCampaignPrompt.cta}\n\nCarousel outline:\nSlide 1: ${weeklyCampaignPrompt.name} - the simple way to start\nSlide 2: Q: How do I join? A: Open Rise With The Tribe, pick this week's challenge, and log one honest session.\nSlide 3: Q: What if I missed days? A: Come back with today's log. Return speed matters more than a perfect streak.\nSlide 4: Q: Can I bring someone? A: Yes. Invite one accountability partner and make the start visible together.\nSlide 5: Q: Can I be featured? A: Submit Feature Me in the app with consent and a clear story.\nSlide 6: Q: Are Pro, paid packs, or creator hosting live? A: Not yet. Save interest in the app while paid features stay behind validation.\nSlide 7: CTA: Join ${weeklyCampaignPrompt.name}, log your first session, and use ${weeklyCampaignPrompt.hashtag} if you share.\n\nCaption:\nThe same questions keep coming up, so here is the simple start. Swipe, pick one action, and put your first log into Rise With The Tribe today.\n\nReview note:\nUse repeated questions as directional content input only. Confirm roadmap, paid-feature, creator, and partner decisions with first-party app movement before changing launch copy.\n\nThis is a manual FAQ carousel kit only. Do not auto-post, schedule posts, scrape comments, scrape DMs, store Instagram identities, store inbound replies, create attribution records, add tracking pixels, export per-user activity, treat Instagram questions as app consent, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignCaptionBankCopy = `Rise With The Tribe Weekly Campaign Caption Bank Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nRecommended experiment: ${recommendedLaunchExperiment.label}\nCTA: ${weeklyCampaignPrompt.cta}\n\nReel caption:\nYour next reset does not need a perfect week. It needs one honest log today. Join ${weeklyCampaignPrompt.name} inside Rise With The Tribe, tag @risewiththetribe, and use ${weeklyCampaignPrompt.hashtag} when you start.\n\nCarousel caption:\nConsistency gets easier when the next action is visible. Swipe through the prompt, pick today's session, and log it in the app so your streak, points, referrals, and badges move with you.\n\nStory caption:\nVote, then move. Join this week's challenge in the app and bring one accountability partner with you.\n\nPinned comment:\nJoining? Open Rise With The Tribe, start ${weeklyCampaignPrompt.name}, log your first session, and use ${weeklyCampaignPrompt.hashtag} so we can cheer you on.\n\nCreator note:\nUse the Story Poll Kit and Poll Review Kit to choose the angle, then confirm momentum through first-party app movement before repeating the caption.\n\nThis is a manual caption bank only. Do not auto-post, schedule posts, scrape comments, scrape DMs, store inbound replies, create attribution records, add tracking pixels, export per-user activity, share private responses, imply paid access is live, promise outcomes, imply medical results, or pressure users.`;
  const weeklyCampaignCollabCopyCards = buildWeeklyCampaignCollabCopyCards({
    campaignPerformanceSummary,
    featureReviewQueue,
    recommendedLaunchExperiment,
    referralJoins,
    supportReviewQueue,
    weeklyCampaignPrompt,
  });


  return {
    weeklyCampaignCommentReplyCopy,
    weeklyCampaignCountdownStoryCopy,
    weeklyCampaignStartDayStoryCopy,
    weeklyCampaignMidweekCheckInStoryCopy,
    weeklyCampaignWeekendPushStoryCopy,
    weeklyCampaignCompletionRecapStoryCopy,
    weeklyCampaignNextWeekTeaserStoryCopy,
    weeklyCampaignPartnerPerkTeaserStoryCopy,
    weeklyCampaignStoryPollCopy,
    weeklyCampaignPollReviewCopy,
    weeklyCampaignLiveQaCopy,
    weeklyCampaignLiveRecapCopy,
    weeklyCampaignFaqCarouselCopy,
    weeklyCampaignCaptionBankCopy,
    weeklyCampaignCollabCopyCards,
  };
}
