export const WEEKLY_CAMPAIGN_STORY_LIFECYCLE_COPY_CARD_DEFINITIONS = [
  {
    title: 'Weekly Campaign Comment Reply Kit',
    subtitle: 'Manual public replies for weekly campaign comments',
    statusKey: 'hashtag',
    accent: '#818CF8',
    body: 'Copy public comment replies for joining, comeback, paid-access, and Feature Me questions without automation or comment scraping.',
    buttonLabel: 'COPY COMMENT REPLIES',
    copyKey: 'weeklyCampaignCommentReplyCopy',
  },
  {
    title: 'Weekly Campaign Countdown Story Kit',
    subtitle: 'Manual Story countdown sequence before launch',
    status: 'COUNTDOWN',
    accent: '#FB923C',
    body: 'Copy countdown frames, sticker text, and app-first launch reminders without scheduling Stories, scraping responses, or treating Story interactions as app consent.',
    buttonLabel: 'COPY COUNTDOWN STORIES',
    copyKey: 'weeklyCampaignCountdownStoryCopy',
  },
  {
    title: 'Weekly Campaign Start-Day Story Kit',
    subtitle: 'Manual launch-day Stories for first logs',
    status: 'START DAY',
    accent: '#22C55E',
    body: 'Copy launch-day Story frames and stickers that push followers to join and save the first app log without scraping reactions or creating attribution.',
    buttonLabel: 'COPY START-DAY STORIES',
    copyKey: 'weeklyCampaignStartDayStoryCopy',
  },
  {
    title: 'Weekly Campaign Midweek Check-In Story Kit',
    subtitle: 'Manual midweek Stories for comeback logs',
    status: 'MIDWEEK',
    accent: '#10B981',
    body: "Copy midweek Story frames and stickers that route people back to today's app log without scraping reactions or creating attribution.",
    buttonLabel: 'COPY MIDWEEK CHECK-IN',
    copyKey: 'weeklyCampaignMidweekCheckInStoryCopy',
  },
  {
    title: 'Weekly Campaign Weekend Push Story Kit',
    subtitle: 'Manual weekend Stories for finish-line logs',
    status: 'WEEKEND',
    accent: '#F59E0B',
    body: 'Copy weekend Story frames and stickers that push saved logs, referrals, and consent-based Feature Me submissions without scraping reactions.',
    buttonLabel: 'COPY WEEKEND PUSH',
    copyKey: 'weeklyCampaignWeekendPushStoryCopy',
  },
  {
    title: 'Weekly Campaign Completion Recap Story Kit',
    subtitle: 'Manual recap Stories for consent-safe weekly wins',
    status: 'RECAP',
    accent: '#60A5FA',
    body: 'Copy weekly recap Story frames and stickers that celebrate aggregate progress, route wins through Feature Me, and point people to the next challenge.',
    buttonLabel: 'COPY COMPLETION RECAP',
    copyKey: 'weeklyCampaignCompletionRecapStoryCopy',
  },
  {
    title: 'Weekly Campaign Next-Week Teaser Story Kit',
    subtitle: 'Manual teaser Stories for the next challenge',
    status: 'NEXT',
    accent: '#A855F7',
    body: "Copy teaser Story frames and stickers that turn this week's closeout into a next-challenge invite using first-party app movement.",
    buttonLabel: 'COPY NEXT-WEEK TEASER',
    copyKey: 'weeklyCampaignNextWeekTeaserStoryCopy',
  },
  {
    title: 'Weekly Campaign Partner Perk Teaser Story Kit',
    subtitle: 'Manual perk-interest Stories before partner outreach',
    status: 'PERK',
    accent: '#22D3EE',
    body: 'Copy partner-perk teaser frames and stickers that route interest back into the app before any partner link, payout, or outreach exists.',
    buttonLabel: 'COPY PARTNER PERK TEASER',
    copyKey: 'weeklyCampaignPartnerPerkTeaserStoryCopy',
  },
];
