export function buildWeeklyCampaignCoreCopy({
  weeklyCampaignPrompt,
  campaignPerformanceSummary,
  referralJoins,
  featureReviewQueue,
  dmKeywordPrompts,
}) {
  const campaignPerformanceCopy = (campaignPerformanceSummary.total || 0)
    ? `Rise With The Tribe campaign board: ${campaignPerformanceSummary.total || 0} campaign-backed challenges are live in the system with ${campaignPerformanceSummary.memberReach || 0} total member joins. ${campaignPerformanceSummary.active || 0} are active, ${campaignPerformanceSummary.public || 0} are public, ${campaignPerformanceSummary.premium || 0} are premium, and ${campaignPerformanceSummary.seasonal || 0} are seasonal drops. Use this to decide the next weekly Instagram push and creator challenge prompt.`
    : 'Rise With The Tribe campaign board: campaign-backed challenges will appear here once weekly, seasonal, or creator campaigns are created.';
  const dmKeywordReplies = {
    TRIBE: `DM keyword TRIBE reply:\nYou are in. This week's Rise With The Tribe prompt is ${weeklyCampaignPrompt.name}. ${weeklyCampaignPrompt.cta}\nStart in the app, tag @risewiththetribe, and use ${weeklyCampaignPrompt.hashtag}.`,
    COMEBACK: `DM keyword COMEBACK reply:\nNo shame, just the next log. Open Rise With The Tribe, pick one small session today, and rebuild from a visible win. Tag @risewiththetribe when you are back in motion.`,
    PRO: `DM keyword PRO reply:\nTribe Pro is being shaped around deeper reports, private challenges, premium packs, and creator tools. Save your Pro Trial Interest in the app so we know what to launch first.`,
    FEATURE: `DM keyword FEATURE reply:\nWant to be featured by @risewiththetribe? Submit your streak win, comeback, transformation, or challenge completion inside the app with consent and a clear story.`,
  };

  return {
    campaignPerformanceCopy,
    campaignSchedulerCopy: `Rise With The Tribe weekly campaign scheduler: Week ${weeklyCampaignPrompt.week} is ${weeklyCampaignPrompt.name} (${weeklyCampaignPrompt.label}). ${weeklyCampaignPrompt.cta}\n\nUse ${weeklyCampaignPrompt.hashtag}, tag @risewiththetribe, and invite one accountability partner to join the ${weeklyCampaignPrompt.duration}-day challenge.`,
    weeklyCampaignLaunchCardCopy: `Rise With The Tribe Weekly Campaign Launch Card Kit:\n\nCard headline: ${weeklyCampaignPrompt.name}\nCard label: Week ${weeklyCampaignPrompt.week} - ${weeklyCampaignPrompt.label}\nCard CTA: ${weeklyCampaignPrompt.cta}\nHashtag: ${weeklyCampaignPrompt.hashtag}\nDuration: ${weeklyCampaignPrompt.duration} days\n\nDesign notes: use a clear challenge-title lockup, one progress-forward CTA, @risewiththetribe, and the weekly hashtag. Keep the card readable on Instagram Stories and Reels covers.\n\nCaption draft:\nThis week's Rise With The Tribe prompt is ${weeklyCampaignPrompt.name}. ${weeklyCampaignPrompt.cta}\n\nUse ${weeklyCampaignPrompt.hashtag}, tag @risewiththetribe, and invite one accountability partner to join the ${weeklyCampaignPrompt.duration}-day challenge.\n\nThis is a manual campaign launch card brief only. Do not auto-post to Instagram, scrape DMs, add tracking pixels, imply paid access is live, promise outcomes, imply medical results, or share user activity without consent.`,
    weeklyCampaignLaunchCopyQaCopy: `Rise With The Tribe Weekly Campaign Launch Copy QA Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nDuration: ${weeklyCampaignPrompt.duration} days\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nPending feature submissions: ${featureReviewQueue.length}\n\nManual launch copy QA checklist:\n[ ] Compare the launch-card headline, caption draft, Story/Reel hook, pinned comment, DM keyword replies, and referral CTA against this week's campaign prompt before posting.\n[ ] Confirm every CTA routes followers back into the app challenge loop: join the challenge, log one honest session, invite one accountability partner, or submit Feature Me with consent.\n[ ] Remove claims about paid access, Pro, packs, creator payouts, partner perks, discounts, refunds, guaranteed outcomes, medical results, or unreviewed member stories before the copy is used.\n[ ] Record copy owner, reviewedAt timestamp, approved caption, approved hashtag, support-risk note, and remaining edits before any human publishes or sends the message.\n\nThis is a manual Weekly Campaign Launch Copy QA Kit only. Do not auto-post to Instagram, schedule posts from the app, scrape comments, scrape DMs, store inbound replies, store Instagram identities, create attribution records, count link opens, add tracking pixels, export per-user activity, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    weeklyCampaignFirstDayMonitorCopy: `Rise With The Tribe Weekly Campaign First 24h Monitor Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nActive campaign challenges: ${campaignPerformanceSummary.active || 0}\nReferral joins: ${referralJoins}\nPending feature submissions: ${featureReviewQueue.length}\n\nManual first 24h monitor checklist:\n[ ] Confirm the human-posted launch card, caption, Story/Reel hook, pinned comment, and DM keyword replies match the approved launch copy QA record.\n[ ] Review only first-party app movement: challenge joins, referral joins, activity logs, share-card usage, Feature Me submissions, saved interest, and support notes.\n[ ] Route support-risk replies to support triage before retention, re-invite, Pro, pack, creator, partner, or referral copy is used.\n[ ] Record monitor owner, reviewedAt timestamp, first-party signal summary, support-risk note, repeat/hold recommendation, and next app CTA for the campaign review.\n\nThis is a manual Weekly Campaign First 24h Monitor Kit only. Do not auto-post to Instagram, schedule posts from the app, scrape posts, scrape comments, scrape DMs, store inbound replies, store Instagram identities, create attribution records, count link opens, add tracking pixels, export per-user activity, share private responses, share user content without consent, share unreviewed submissions, write referral state, grant rewards, create purchases, write entitlements, unlock paid access, imply paid access is live, promise outcomes, imply medical results, offer discounts, promise refunds, auto-message users, or pressure members.`,
    weeklyCampaignPreflightCopy: `Rise With The Tribe Weekly Campaign Preflight Checklist:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nPending feature submissions: ${featureReviewQueue.length}\n\nPreflight checks:\n[ ] Launch card headline, caption draft, hashtag, and design notes are ready\n[ ] DM keyword replies for TRIBE, COMEBACK, PRO, and FEATURE are ready for manual use\n[ ] Seven-day content calendar is aligned to the weekly campaign prompt\n[ ] Invite/referral copy points members back into the app challenge loop\n[ ] Feature submissions and user activity are shared only with consent and manual review\n[ ] Post-launch review will use first-party challenge joins, referral movement, feature submissions, and share-card usage only\n\nThis is a manual weekly campaign preflight checklist only. Do not schedule posts, auto-post to Instagram, scrape DMs, store inbound DMs, add tracking pixels, export per-user activity, share user content without consent, imply paid access is live, promise outcomes, or imply medical results.`,
    weeklyCampaignReviewCopy: `Rise With The Tribe Weekly Campaign Review Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nHashtag: ${weeklyCampaignPrompt.hashtag}\nCampaign member reach: ${campaignPerformanceSummary.memberReach || 0}\nReferral joins: ${referralJoins}\nPending feature submissions: ${featureReviewQueue.length}\nShare-card usage: review in native share/activity surfaces only when first-party logs exist\n\nReview notes:\n[ ] Which post, story, or challenge invite drove the clearest app challenge joins?\n[ ] Which DM keyword reply needs clearer manual copy next week?\n[ ] Which feature submissions are consent-cleared for Instagram review?\n[ ] Which referral prompt should be repeated or retired?\n[ ] What should change in next week's launch card, content calendar, and challenge CTA?\n\nThis is a manual weekly campaign review brief only. Do not create attribution records, add tracking pixels, scrape or store Instagram DMs, export per-user activity, share user content without consent, imply paid access is live, promise outcomes, or imply medical results.`,
    weeklyCampaignStoryboardCopy: `Rise With The Tribe Weekly Campaign Storyboard Kit:\n\nCampaign: ${weeklyCampaignPrompt.name}\nWeek: ${weeklyCampaignPrompt.week} (${weeklyCampaignPrompt.label})\nCTA: ${weeklyCampaignPrompt.cta}\nHashtag: ${weeklyCampaignPrompt.hashtag}\nDuration: ${weeklyCampaignPrompt.duration} days\n\nReel storyboard:\n1. Hook: \"Your next ${weeklyCampaignPrompt.duration}-day reset starts with one logged session.\"\n2. Proof beat: show app streak, points, challenge card, or consent-cleared member win.\n3. Action beat: ask followers to join the weekly challenge in the app and tag @risewiththetribe.\n4. CTA: use ${weeklyCampaignPrompt.hashtag} and invite one accountability partner.\n\nStory frames:\n[ ] Frame 1: campaign name and today's simple action\n[ ] Frame 2: poll or question sticker about showing up today\n[ ] Frame 3: app challenge invite and hashtag\n[ ] Frame 4: repost consent-cleared UGC or a founder accountability note\n\nCarousel outline:\nSlide 1: ${weeklyCampaignPrompt.name}\nSlide 2: why this challenge matters this week\nSlide 3: how to log the first session\nSlide 4: how to invite one accountability partner\nSlide 5: weekly hashtag and app CTA\n\nThis is a manual content storyboard only. Do not auto-post to Instagram, schedule posts from the app, scrape DMs, store inbound DMs, add tracking pixels, export per-user activity, share user content without consent, imply paid access is live, promise outcomes, or imply medical results.`,
    dmKeywordCopy: dmKeywordPrompts.map(prompt => dmKeywordReplies[prompt.keyword]).join('\n\n'),
  };
}
