import { buildSimpleWeeklyCampaignCopyCards } from './weeklyCampaignCardCopy';
import { buildWeeklyCampaignMetricKitSections } from './weeklyCampaignMetricKitSections';
import { buildWeeklyCampaignOperatingSummary } from './weeklyCampaignOperatingSummary';

export function buildWeeklyCampaignMarketingSectionData({
  campaignPerformanceSummary,
  dmKeywordCopy,
  featureReviewQueue,
  instagramContentCalendarCopy,
  launchRetrospectiveReadinessScriptCopy,
  recommendedLaunchExperiment,
  referralJoins,
  weeklyCampaignCaptionBankCopy,
  weeklyCampaignCollabCopyCards,
  weeklyCampaignCommentReplyCopy,
  weeklyCampaignCompletionRecapStoryCopy,
  weeklyCampaignCountdownStoryCopy,
  weeklyCampaignExperimentBriefHandoffCopy,
  weeklyCampaignExperimentBriefCopy,
  weeklyCampaignExperimentBriefQaCopy,
  weeklyCampaignFaqCarouselCopy,
  weeklyCampaignFinalPostingPrepQaCopy,
  weeklyCampaignFirstDayMonitorCopy,
  weeklyCampaignLiveQaCopy,
  weeklyCampaignLiveRecapCopy,
  weeklyCampaignManualPostingOperatorBriefCopy,
  weeklyCampaignMidweekCheckInStoryCopy,
  weeklyCampaignMidweekAdjustmentCopy,
  weeklyCampaignNextWeekLaunchAngleCopy,
  weeklyCampaignNextWeekTeaserStoryCopy,
  weeklyCampaignPartnerPerkTeaserStoryCopy,
  weeklyCampaignPollReviewCopy,
  weeklyCampaignPostCompleteCallbackQaCopy,
  weeklyCampaignReviewHandoffCopy,
  weeklyCampaignPreflightAssetReadinessCopy,
  weeklyCampaignPreflightChecklistHandoffCopy,
  weeklyCampaignPreflightCopy,
  weeklyCampaignPreflightChecklistQaCopy,
  weeklyCampaignLaunchReadinessHandoffCopy,
  weeklyCampaignPreflightCopyFreezeCopy,
  weeklyCampaignPreflightGoNoGoCopy,
  weeklyCampaignPreflightLaunchPacketQaCopy,
  weeklyCampaignPreflightOwnerHandoffCopy,
  weeklyCampaignPreflightReadinessDecisionCopy,
  weeklyCampaignPrompt,
  weeklyCampaignLaunchCardCopy,
  weeklyCampaignLaunchCopyQaCopy,
  weeklyCampaignReviewCopy,
  weeklyCampaignReviewDecisionCopy,
  weeklyCampaignStartDayStoryCopy,
  weeklyCampaignStoryboardHandoffCopy,
  weeklyCampaignStoryboardCopy,
  weeklyCampaignStoryboardQaCopy,
  weeklyCampaignStoryPollCopy,
  weeklyCampaignWeekendPushDecisionCopy,
  weeklyCampaignWeekendPushStoryCopy,
  weeklyCampaignSundayRecapQaCopy,
}) {
  return {
    dmKeywordSectionProps: {
      dmKeywordCopy,
    },
    instagramCalendarSectionProps: {
      instagramContentCalendarCopy,
    },
    launchCardSectionProps: {
      weeklyCampaignLaunchCardCopy,
      weeklyCampaignPrompt,
    },
    operatingSummaryProps: buildWeeklyCampaignOperatingSummary({
      campaignPerformanceSummary,
      featureReviewQueue,
      recommendedLaunchExperiment,
      referralJoins,
      weeklyCampaignPrompt,
    }),
    simpleWeeklyCampaignCopyCards: buildSimpleWeeklyCampaignCopyCards({
      weeklyCampaignPrompt,
      weeklyCampaignCommentReplyCopy,
      weeklyCampaignCountdownStoryCopy,
      weeklyCampaignStartDayStoryCopy,
      weeklyCampaignMidweekCheckInStoryCopy,
      weeklyCampaignWeekendPushStoryCopy,
      weeklyCampaignCompletionRecapStoryCopy,
      weeklyCampaignNextWeekTeaserStoryCopy,
      weeklyCampaignPartnerPerkTeaserStoryCopy,
      weeklyCampaignStoryPollCopy,
      weeklyCampaignPollReviewCopy,
      weeklyCampaignLiveQaCopy,
      weeklyCampaignLiveRecapCopy,
      weeklyCampaignFaqCarouselCopy,
      weeklyCampaignCaptionBankCopy,
    }),
    weeklyCampaignMetricKitSections: buildWeeklyCampaignMetricKitSections({
      campaignPerformanceSummary,
      featureReviewQueue,
      recommendedLaunchExperiment,
      referralJoins,
      launchRetrospectiveReadinessScriptCopy,
      weeklyCampaignExperimentBriefCopy,
      weeklyCampaignExperimentBriefQaCopy,
      weeklyCampaignFirstDayMonitorCopy,
      weeklyCampaignMidweekAdjustmentCopy,
      weeklyCampaignWeekendPushDecisionCopy,
      weeklyCampaignSundayRecapQaCopy,
      weeklyCampaignNextWeekLaunchAngleCopy,
      weeklyCampaignPreflightOwnerHandoffCopy,
      weeklyCampaignPreflightReadinessDecisionCopy,
      weeklyCampaignPreflightCopyFreezeCopy,
      weeklyCampaignPreflightAssetReadinessCopy,
      weeklyCampaignPreflightChecklistHandoffCopy,
      weeklyCampaignPreflightLaunchPacketQaCopy,
      weeklyCampaignPreflightGoNoGoCopy,
      weeklyCampaignPreflightChecklistQaCopy,
      weeklyCampaignLaunchReadinessHandoffCopy,
      weeklyCampaignFinalPostingPrepQaCopy,
      weeklyCampaignManualPostingOperatorBriefCopy,
      weeklyCampaignPostCompleteCallbackQaCopy,
      weeklyCampaignReviewHandoffCopy,
      weeklyCampaignLaunchCopyQaCopy,
      weeklyCampaignPreflightCopy,
      weeklyCampaignPrompt,
      weeklyCampaignReviewCopy,
      weeklyCampaignReviewDecisionCopy,
      weeklyCampaignStoryboardHandoffCopy,
      weeklyCampaignStoryboardCopy,
      weeklyCampaignStoryboardQaCopy,
      weeklyCampaignExperimentBriefHandoffCopy,
    }),
    weeklyCampaignCollabCopyCards,
  };
}
