import { WEEKLY_CAMPAIGN_STORY_FEEDBACK_COPY_CARD_DEFINITIONS } from './weeklyCampaignStoryFeedbackCopyCardDefinitions';
import { WEEKLY_CAMPAIGN_STORY_LIFECYCLE_COPY_CARD_DEFINITIONS } from './weeklyCampaignStoryLifecycleCopyCardDefinitions';

export const WEEKLY_CAMPAIGN_STORY_COPY_CARD_DEFINITIONS = [
  ...WEEKLY_CAMPAIGN_STORY_LIFECYCLE_COPY_CARD_DEFINITIONS,
  ...WEEKLY_CAMPAIGN_STORY_FEEDBACK_COPY_CARD_DEFINITIONS,
];
