import { GOLD, DM_KEYWORD_PROMPTS } from './profileConstants';

export function buildWeeklyCampaignMetricKitSections({
  campaignPerformanceSummary,
  featureReviewQueue,
  launchRetrospectiveDecisionCopy,
  launchRetrospectiveDecisionReplyCopy,
  launchRetrospectiveNextCampaignFinalPostingPrepHandoffCopy,
  launchRetrospectiveNextCampaignFinalPostingPrepQaBridgeCopy,
  launchRetrospectiveNextCampaignManualPostingOperatorBriefQaBridgeCopy,
  launchRetrospectiveNextCampaignManualPostingOperatorHandoffCopy,
  launchRetrospectiveNextCampaignPostCompleteCallbackHandoffCopy,
  launchRetrospectiveNextCampaignPostCompleteCallbackQaBridgeCopy,
  launchRetrospectiveNextCampaignBriefCopy,
  launchRetrospectiveNextCampaignBriefQaCopy,
  launchRetrospectiveNextCampaignLaunchCopyApprovalCopy,
  launchRetrospectiveNextCampaignLaunchCopyHandoffCopy,
  launchRetrospectiveNextCampaignLaunchCopyQaBridgeCopy,
  launchRetrospectiveNextCampaignPreflightBridgeCopy,
  launchRetrospectiveNextCampaignHandoffCopy,
  launchRetrospectiveNextCampaignQaCopy,
  launchRetrospectiveReadinessHandoffCopy,
  launchRetrospectiveReadinessQaCopy,
  launchRetrospectiveReadinessScriptCopy,
  recommendedLaunchExperiment,
  referralJoins,
  weeklyCampaignFirstDayMonitorCopy,
  weeklyCampaignExperimentBriefApprovalCopy,
  weeklyCampaignExperimentBriefCopy,
  weeklyCampaignExperimentBriefHandoffCopy,
  weeklyCampaignExperimentBriefQaCopy,
  weeklyCampaignFinalPostingPrepQaCopy,
  weeklyCampaignLaunchCopyQaCopy,
  weeklyCampaignManualPostingOperatorBriefCopy,
  weeklyCampaignMidweekAdjustmentCopy,
  weeklyCampaignPostCompleteCallbackQaCopy,
  weeklyCampaignReviewHandoffCopy,
  weeklyCampaignPreflightCopy,
  weeklyCampaignPrompt,
  weeklyCampaignReviewCopy,
  weeklyCampaignReviewDecisionCopy,
  weeklyCampaignStoryboardHandoffCopy,
  weeklyCampaignStoryboardCopy,
  weeklyCampaignStoryboardQaCopy,
  weeklyCampaignWeekendPushDecisionCopy,
  weeklyCampaignSundayRecapQaCopy,
  weeklyCampaignNextWeekLaunchAngleCopy,
  weeklyCampaignPreflightAssetReadinessCopy,
  weeklyCampaignPreflightChecklistHandoffCopy,
  weeklyCampaignPreflightChecklistQaCopy,
  weeklyCampaignLaunchReadinessHandoffCopy,
  weeklyCampaignPreflightCopyFreezeCopy,
  weeklyCampaignPreflightGoNoGoCopy,
  weeklyCampaignPreflightLaunchPacketQaCopy,
  weeklyCampaignPreflightOwnerHandoffCopy,
  weeklyCampaignPreflightReadinessDecisionCopy,
}) {
  return [
    {
      title: 'Weekly Campaign Launch Copy QA Kit',
      subtitle: 'Manual copy check before posting',
      status: 'COPY QA',
      accent: '#38BDF8',
      background: 'rgba(56,189,248,0.05)',
      border: '1px solid rgba(56,189,248,0.16)',
      metrics: [
        ['CARD', weeklyCampaignPrompt.hashtag],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check launch-card, caption, Story/Reel hook, pinned comment, DM keyword, and referral copy before any manual weekly campaign post.',
      buttonLabel: 'COPY LAUNCH COPY QA',
      copyText: weeklyCampaignLaunchCopyQaCopy,
    },
    {
      title: 'Weekly Campaign First 24h Monitor Kit',
      subtitle: 'First-party signal readback after launch',
      status: '24H MONITOR',
      accent: '#60A5FA',
      background: 'rgba(96,165,250,0.05)',
      border: '1px solid rgba(96,165,250,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Review first-party app movement and support risk during the first 24 hours after a human weekly campaign launch.',
      buttonLabel: 'COPY 24H MONITOR',
      copyText: weeklyCampaignFirstDayMonitorCopy,
    },
    {
      title: 'Weekly Campaign Midweek Adjustment Kit',
      subtitle: 'Manual CTA decision from first-party signals',
      status: 'MIDWEEK',
      accent: '#818CF8',
      background: 'rgba(129,140,248,0.05)',
      border: '1px solid rgba(129,140,248,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Decide whether to repeat, clarify, support-route, comeback-invite, ask for consent, or hold follow-up copy midweek.',
      buttonLabel: 'COPY MIDWEEK ADJUSTMENT',
      copyText: weeklyCampaignMidweekAdjustmentCopy,
    },
    {
      title: 'Weekly Campaign Weekend Push Decision Kit',
      subtitle: 'Manual final-push decision from app signals',
      status: 'WEEKEND',
      accent: '#A78BFA',
      background: 'rgba(167,139,250,0.05)',
      border: '1px solid rgba(167,139,250,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Decide whether to approve, repeat, comeback-invite, feature proof, support-route, or hold weekend follow-up copy.',
      buttonLabel: 'COPY WEEKEND DECISION',
      copyText: weeklyCampaignWeekendPushDecisionCopy,
    },
    {
      title: 'Weekly Campaign Sunday Recap QA Kit',
      subtitle: 'Manual recap and next-week handoff check',
      status: 'RECAP QA',
      accent: '#C4B5FD',
      background: 'rgba(196,181,253,0.05)',
      border: '1px solid rgba(196,181,253,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check aggregate recap copy, consent-cleared proof, support-risk notes, and next-week handoff before any Sunday recap post.',
      buttonLabel: 'COPY SUNDAY RECAP QA',
      copyText: weeklyCampaignSundayRecapQaCopy,
    },
    {
      title: 'Weekly Campaign Next-Week Launch Angle Kit',
      subtitle: 'Manual next campaign angle decision',
      status: 'NEXT ANGLE',
      accent: '#FDBA74',
      background: 'rgba(253,186,116,0.05)',
      border: '1px solid rgba(253,186,116,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Choose the next-week launch angle from recap QA, campaign movement, consent-safe proof, and support-risk notes before preflight.',
      buttonLabel: 'COPY NEXT-WEEK ANGLE',
      copyText: weeklyCampaignNextWeekLaunchAngleCopy,
    },
    {
      title: 'Weekly Campaign Preflight Owner Handoff Kit',
      subtitle: 'Manual owner assignment before preflight',
      status: 'HANDOFF',
      accent: '#F59E0B',
      background: 'rgba(245,158,11,0.05)',
      border: '1px solid rgba(245,158,11,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Assign preflight owners for launch copy, manual replies, consent review, and support-risk routing before the next campaign preflight starts.',
      buttonLabel: 'COPY PREFLIGHT HANDOFF',
      copyText: weeklyCampaignPreflightOwnerHandoffCopy,
    },
    {
      title: 'Weekly Campaign Preflight Readiness Decision Kit',
      subtitle: 'Manual approve or hold decision before preflight',
      status: 'READY?',
      accent: '#22C55E',
      background: 'rgba(34,197,94,0.05)',
      border: '1px solid rgba(34,197,94,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Approve, clarify, support-route, wait for consent proof, repeat free-loop CTA, or hold paid-feature language before preflight.',
      buttonLabel: 'COPY PREFLIGHT DECISION',
      copyText: weeklyCampaignPreflightReadinessDecisionCopy,
    },
    {
      title: 'Weekly Campaign Preflight Copy Freeze Kit',
      subtitle: 'Manual freeze before preflight edits',
      status: 'FREEZE',
      accent: '#2DD4BF',
      background: 'rgba(45,212,191,0.05)',
      border: '1px solid rgba(45,212,191,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Freeze the launch-card headline, app-first CTA, manual replies, consent proof, and support-risk routing note before preflight edits.',
      buttonLabel: 'COPY PREFLIGHT FREEZE',
      copyText: weeklyCampaignPreflightCopyFreezeCopy,
    },
    {
      title: 'Weekly Campaign Preflight Asset Readiness Kit',
      subtitle: 'Manual launch asset prep check',
      status: 'ASSETS',
      accent: '#0EA5E9',
      background: 'rgba(14,165,233,0.05)',
      border: '1px solid rgba(14,165,233,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Confirm launch-card headline, caption input, Story/Reel hook, consent-safe proof, and support routing before final assets.',
      buttonLabel: 'COPY PREFLIGHT ASSETS',
      copyText: weeklyCampaignPreflightAssetReadinessCopy,
    },
    {
      title: 'Weekly Campaign Preflight Launch Packet QA Kit',
      subtitle: 'Manual final packet check before preflight',
      status: 'PACKET QA',
      accent: '#38BDF8',
      background: 'rgba(56,189,248,0.05)',
      border: '1px solid rgba(56,189,248,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check the launch-card headline, caption input, Story/Reel hook, CTA, consent proof, support note, and owner as one packet.',
      buttonLabel: 'COPY PACKET QA',
      copyText: weeklyCampaignPreflightLaunchPacketQaCopy,
    },
    {
      title: 'Weekly Campaign Preflight Go/No-Go Kit',
      subtitle: 'Manual final decision before preflight',
      status: 'GO/NO-GO',
      accent: '#22D3EE',
      background: 'rgba(34,211,238,0.05)',
      border: '1px solid rgba(34,211,238,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Choose go to preflight or hold for copy, assets, consent, support, free-loop, or paid-language blockers.',
      buttonLabel: 'COPY GO/NO-GO',
      copyText: weeklyCampaignPreflightGoNoGoCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist Handoff Kit',
      subtitle: 'Manual checklist owner handoff',
      status: 'HANDOFF',
      accent: '#67E8F9',
      background: 'rgba(103,232,249,0.05)',
      border: '1px solid rgba(103,232,249,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off the approved lane, packet reference, blockers, consent proof, support route, and checklist owner before preflight work starts.',
      buttonLabel: 'COPY CHECKLIST HANDOFF',
      copyText: weeklyCampaignPreflightChecklistHandoffCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist',
      subtitle: 'Manual launch readiness before posting',
      status: 'CHECKLIST',
      accent: '#14B8A6',
      background: 'rgba(20,184,166,0.05)',
      border: '1px solid rgba(20,184,166,0.16)',
      metrics: [
        ['CARD', weeklyCampaignPrompt.hashtag],
        ['DM', DM_KEYWORD_PROMPTS.length],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Confirm card copy, manual DM replies, content calendar, referral copy, consent-reviewed UGC, and first-party review metrics before the weekly push.',
      buttonLabel: 'COPY CAMPAIGN PREFLIGHT',
      copyText: weeklyCampaignPreflightCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist QA Kit',
      subtitle: 'Manual completed-checklist review',
      status: 'CHECK QA',
      accent: '#5EEAD4',
      background: 'rgba(94,234,212,0.05)',
      border: '1px solid rgba(94,234,212,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Review the completed checklist, handoff, blockers, consent proof, support route, and launch readiness handoff before copy is treated as ready.',
      buttonLabel: 'COPY CHECKLIST QA',
      copyText: weeklyCampaignPreflightChecklistQaCopy,
    },
    {
      title: 'Weekly Campaign Launch Readiness Handoff Kit',
      subtitle: 'Manual ready-for-launch owner handoff',
      status: 'READY HANDOFF',
      accent: '#99F6E4',
      background: 'rgba(153,246,228,0.05)',
      border: '1px solid rgba(153,246,228,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off the approved checklist, launch copy, reply owner, consent proof, support route, blockers, and launch operator before final posting copy.',
      buttonLabel: 'COPY READY HANDOFF',
      copyText: weeklyCampaignLaunchReadinessHandoffCopy,
    },
    {
      title: 'Weekly Campaign Final Posting Prep QA Kit',
      subtitle: 'Manual final posting packet check',
      status: 'POST QA',
      accent: '#A7F3D0',
      background: 'rgba(167,243,208,0.05)',
      border: '1px solid rgba(167,243,208,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check the final caption, launch card, Story/Reel hook, CTA, reply boundary, consent proof, support route, and launch operator.',
      buttonLabel: 'COPY POSTING QA',
      copyText: weeklyCampaignFinalPostingPrepQaCopy,
    },
    {
      title: 'Weekly Campaign Manual Posting Operator Brief Kit',
      subtitle: 'Manual launch operator instructions',
      status: 'OPERATOR',
      accent: '#BBF7D0',
      background: 'rgba(187,247,208,0.05)',
      border: '1px solid rgba(187,247,208,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Give the human posting operator the approved caption, launch card, Story/Reel hook, CTA, reply owner, consent proof, and support route.',
      buttonLabel: 'COPY OPERATOR BRIEF',
      copyText: weeklyCampaignManualPostingOperatorBriefCopy,
    },
    {
      title: 'Weekly Campaign Post-Complete Callback QA Kit',
      subtitle: 'Manual post-complete callback check',
      status: 'CALLBACK QA',
      accent: '#86EFAC',
      background: 'rgba(134,239,172,0.05)',
      border: '1px solid rgba(134,239,172,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Record only manual post-complete status, posting operator, approved packet reference, support note, and first-party monitoring owner.',
      buttonLabel: 'COPY CALLBACK QA',
      copyText: weeklyCampaignPostCompleteCallbackQaCopy,
    },
    {
      title: 'Weekly Campaign Review Handoff Kit',
      subtitle: 'Manual post-launch review handoff',
      status: 'REVIEW HANDOFF',
      accent: '#4ADE80',
      background: 'rgba(74,222,128,0.05)',
      border: '1px solid rgba(74,222,128,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off callback evidence, first-party signal summary, support route, consent queue, and review owner before the campaign review brief is written.',
      buttonLabel: 'COPY REVIEW HANDOFF',
      copyText: weeklyCampaignReviewHandoffCopy,
    },
    {
      title: 'Weekly Campaign Review Kit',
      subtitle: 'First-party weekly campaign review',
      status: 'REVIEW',
      accent: GOLD,
      background: 'rgba(251,191,36,0.05)',
      border: '1px solid rgba(251,191,36,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['DM', DM_KEYWORD_PROMPTS.length],
      ],
      body: "Review challenge joins, referral movement, consent-cleared UGC, manual DM copy, and share-card usage before shaping next week's push.",
      buttonLabel: 'COPY CAMPAIGN REVIEW',
      copyText: weeklyCampaignReviewCopy,
    },
    {
      title: 'Weekly Campaign Review Decision Kit',
      subtitle: 'Manual post-review next action',
      status: 'REVIEW DECISION',
      accent: '#FACC15',
      background: 'rgba(250,204,21,0.05)',
      border: '1px solid rgba(250,204,21,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['DM', DM_KEYWORD_PROMPTS.length],
      ],
      body: 'Choose one manual next action from the review brief before storyboard, referral follow-up, support routing, or retrospective readiness starts.',
      buttonLabel: 'COPY REVIEW DECISION',
      copyText: weeklyCampaignReviewDecisionCopy,
    },
    {
      title: 'Weekly Campaign Storyboard Handoff Kit',
      subtitle: 'Manual content owner handoff',
      status: 'STORYBOARD HANDOFF',
      accent: '#FBBF24',
      background: 'rgba(251,191,36,0.05)',
      border: '1px solid rgba(251,191,36,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: 'Hand off the review decision, app-first CTA, consent proof source, support route, and storyboard owner before content copy is written.',
      buttonLabel: 'COPY STORYBOARD HANDOFF',
      copyText: weeklyCampaignStoryboardHandoffCopy,
    },
    {
      title: 'Weekly Campaign Storyboard Kit',
      subtitle: 'Reels, Stories, and carousel outline',
      status: 'STORYBOARD',
      accent: '#F472B6',
      background: 'rgba(244,114,182,0.05)',
      border: '1px solid rgba(244,114,182,0.16)',
      metrics: [
        ['REEL', '4 BEATS'],
        ['STORY', '4 FRAMES'],
        ['POST', '5 SLIDES'],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Copy a manual Reel hook, Story frame plan, carousel outline, hashtag, and consent-safe publishing guardrails for this week's campaign.",
      buttonLabel: 'COPY STORYBOARD KIT',
      copyText: weeklyCampaignStoryboardCopy,
    },
    {
      title: 'Weekly Campaign Storyboard QA Kit',
      subtitle: 'Manual content safety QA',
      status: 'STORYBOARD QA',
      accent: '#FB7185',
      background: 'rgba(251,113,133,0.05)',
      border: '1px solid rgba(251,113,133,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: 'Check Reel, Story, and carousel copy for consent-safe proof, app-first CTA, support routing, and no paid/live/reward claims.',
      buttonLabel: 'COPY STORYBOARD QA',
      copyText: weeklyCampaignStoryboardQaCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief Handoff Kit',
      subtitle: 'Manual experiment owner handoff',
      status: 'EXPERIMENT HANDOFF',
      accent: '#FDA4AF',
      background: 'rgba(253,164,175,0.05)',
      border: '1px solid rgba(253,164,175,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off approved storyboard evidence, first-party signal summary, support route, paid-language hold, and experiment brief owner before experiment copy is written.',
      buttonLabel: 'COPY EXPERIMENT HANDOFF',
      copyText: weeklyCampaignExperimentBriefHandoffCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief QA Kit',
      subtitle: 'Manual experiment brief QA',
      status: 'EXPERIMENT QA',
      accent: '#F9A8D4',
      background: 'rgba(249,168,212,0.05)',
      border: '1px solid rgba(249,168,212,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check approved storyboard evidence, first-party signal summary, support route, paid-language hold, and no experiment writes before experiment copy is used.',
      buttonLabel: 'COPY EXPERIMENT QA',
      copyText: weeklyCampaignExperimentBriefQaCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief Kit',
      subtitle: 'Manual experiment from weekly campaign signals',
      status: recommendedLaunchExperiment.label.toUpperCase(),
      accent: '#C084FC',
      background: 'rgba(192,132,252,0.05)',
      border: '1px solid rgba(192,132,252,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['SIGNAL', recommendedLaunchExperiment.signal],
        ['WEEK', weeklyCampaignPrompt.week],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Connect this week's campaign CTA to the recommended manual experiment and review only first-party app movement afterward.",
      buttonLabel: 'COPY EXPERIMENT BRIEF',
      copyText: weeklyCampaignExperimentBriefCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief Approval Kit',
      subtitle: 'Manual experiment lane approval',
      status: 'EXPERIMENT APPROVAL',
      accent: '#E879F9',
      background: 'rgba(232,121,249,0.05)',
      border: '1px solid rgba(232,121,249,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['SIGNAL', recommendedLaunchExperiment.signal],
        ['REF', referralJoins],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Approve, hold, or route the manual experiment lane after the brief is QA-reviewed and before retrospective readback begins.',
      buttonLabel: 'COPY EXPERIMENT APPROVAL',
      copyText: weeklyCampaignExperimentBriefApprovalCopy,
    },
    {
      title: 'Launch Retrospective Readiness Handoff Kit',
      subtitle: 'Manual retrospective owner handoff',
      status: 'RETRO HANDOFF',
      accent: '#F0ABFC',
      background: 'rgba(240,171,252,0.05)',
      border: '1px solid rgba(240,171,252,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Hand off approved experiment evidence, first-party signal summary, support route, consent queue, and paid-language hold before retrospective readback begins.',
      buttonLabel: 'COPY RETRO HANDOFF',
      copyText: launchRetrospectiveReadinessHandoffCopy,
    },
    {
      title: 'Launch Retrospective Readiness QA Kit',
      subtitle: 'Manual retrospective readiness QA',
      status: 'RETRO QA',
      accent: '#F9A8D4',
      background: 'rgba(249,168,212,0.05)',
      border: '1px solid rgba(249,168,212,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the approved handoff, first-party readback script, support route, consent queue, and no tracking or paid-live claims before retrospective decisions.',
      buttonLabel: 'COPY RETRO QA',
      copyText: launchRetrospectiveReadinessQaCopy,
    },
    {
      title: 'Launch Retrospective Readiness Script Kit',
      subtitle: 'Manual first-party campaign readback before repeat decisions',
      status: 'RETRO',
      accent: '#F5D0FE',
      background: 'rgba(245,208,254,0.05)',
      border: '1px solid rgba(245,208,254,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Copy a first-party retrospective readiness script before repeating, pausing, or escalating a launch experiment.',
      buttonLabel: 'COPY RETRO READINESS SCRIPT',
      copyText: launchRetrospectiveReadinessScriptCopy,
    },
    {
      title: 'Launch Retrospective Decision Kit',
      subtitle: 'Manual repeat, pause, or route decision',
      status: 'RETRO DECISION',
      accent: '#FBCFE8',
      background: 'rgba(251,207,232,0.05)',
      border: '1px solid rgba(251,207,232,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Choose repeat, pause, support review, store QA, prompt refresh, free-loop, or paid-language hold after retrospective readback.',
      buttonLabel: 'COPY RETRO DECISION',
      copyText: launchRetrospectiveDecisionCopy,
    },
    {
      title: 'Launch Retrospective Decision Reply Kit',
      subtitle: 'Manual approved, pause, support, store QA, or prompt reply',
      status: 'RETRO REPLY',
      accent: '#F9A8D4',
      background: 'rgba(249,168,212,0.05)',
      border: '1px solid rgba(249,168,212,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Copy safe retrospective decision replies for repeat, pause, support review, store QA, prompt refresh, free-loop, or paid-language hold outcomes.',
      buttonLabel: 'COPY RETRO REPLY',
      copyText: launchRetrospectiveDecisionReplyCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Handoff Kit',
      subtitle: 'Manual handoff into the next campaign preflight',
      status: 'NEXT HANDOFF',
      accent: '#F0ABFC',
      background: 'rgba(240,171,252,0.05)',
      border: '1px solid rgba(240,171,252,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Carry the final retrospective decision into the next campaign owner, preflight owner, support route, consent queue, and paid-language hold.',
      buttonLabel: 'COPY NEXT HANDOFF',
      copyText: launchRetrospectiveNextCampaignHandoffCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign QA Kit',
      subtitle: 'Manual QA before the next preflight starts',
      status: 'NEXT QA',
      accent: '#E879F9',
      background: 'rgba(232,121,249,0.05)',
      border: '1px solid rgba(232,121,249,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the next campaign handoff, decision reply, support route, consent queue, entitlement QA status, and no-paid-live note before preflight starts.',
      buttonLabel: 'COPY NEXT QA',
      copyText: launchRetrospectiveNextCampaignQaCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Brief Kit',
      subtitle: 'Manual brief before new launch copy is written',
      status: 'NEXT BRIEF',
      accent: '#D946EF',
      background: 'rgba(217,70,239,0.05)',
      border: '1px solid rgba(217,70,239,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Turn the approved next campaign QA note into an app-first campaign angle, free challenge CTA, support route, consent lane, and preflight owner.',
      buttonLabel: 'COPY NEXT BRIEF',
      copyText: launchRetrospectiveNextCampaignBriefCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Brief QA Kit',
      subtitle: 'Manual QA before new launch copy starts',
      status: 'BRIEF QA',
      accent: '#C026D3',
      background: 'rgba(192,38,211,0.05)',
      border: '1px solid rgba(192,38,211,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the next campaign brief for app-first angle, free challenge CTA, support-safe route, consent-safe proof lane, paid-language hold, and preflight owner.',
      buttonLabel: 'COPY BRIEF QA',
      copyText: launchRetrospectiveNextCampaignBriefQaCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Preflight Bridge Kit',
      subtitle: 'Manual bridge into preflight owner handoff',
      status: 'PREFLIGHT BRIDGE',
      accent: '#A21CAF',
      background: 'rgba(162,28,175,0.05)',
      border: '1px solid rgba(162,28,175,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Bridge approved brief QA into the preflight owner, launch-copy QA owner, asset owner, support route, consent queue, and paid-language hold before launch copy begins.',
      buttonLabel: 'COPY PREFLIGHT BRIDGE',
      copyText: launchRetrospectiveNextCampaignPreflightBridgeCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Launch Copy Handoff Kit',
      subtitle: 'Manual handoff into launch-copy QA',
      status: 'LAUNCH COPY HANDOFF',
      accent: '#86198F',
      background: 'rgba(134,25,143,0.05)',
      border: '1px solid rgba(134,25,143,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Package the approved preflight bridge into a launch-copy writer, launch-copy QA owner, launch-card headline, caption direction, Story/Reel hook, pinned-comment CTA, DM route, support route, consent queue, and paid-language hold.',
      buttonLabel: 'COPY LAUNCH COPY HANDOFF',
      copyText: launchRetrospectiveNextCampaignLaunchCopyHandoffCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Launch Copy QA Bridge Kit',
      subtitle: 'Manual QA bridge before launch-copy approval',
      status: 'LAUNCH COPY QA',
      accent: '#701A75',
      background: 'rgba(112,26,117,0.05)',
      border: '1px solid rgba(112,26,117,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the launch-copy handoff packet, approved preflight bridge, launch-card headline, caption direction, Story/Reel hook, pinned-comment CTA, DM route, support route, consent queue, and paid-language hold before launch copy is approved.',
      buttonLabel: 'COPY LAUNCH COPY QA BRIDGE',
      copyText: launchRetrospectiveNextCampaignLaunchCopyQaBridgeCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Launch Copy Approval Kit',
      subtitle: 'Manual launch-copy approval decision',
      status: 'COPY APPROVAL',
      accent: '#581C87',
      background: 'rgba(88,28,135,0.05)',
      border: '1px solid rgba(88,28,135,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Approve, hold, route support, request consent review, open store QA, keep free-loop CTA, or hold paid-language copy after the launch-copy QA bridge and before final posting prep.',
      buttonLabel: 'COPY LAUNCH COPY APPROVAL',
      copyText: launchRetrospectiveNextCampaignLaunchCopyApprovalCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Final Posting Prep Handoff Kit',
      subtitle: 'Manual handoff into final posting prep QA',
      status: 'POSTING PREP',
      accent: '#4C1D95',
      background: 'rgba(76,29,149,0.05)',
      border: '1px solid rgba(76,29,149,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Hand off approved launch copy into the manual posting prep owner, final QA owner, support route, consent queue, paid-language hold, and no-paid-live note before final posting prep QA starts.',
      buttonLabel: 'COPY POSTING PREP HANDOFF',
      copyText: launchRetrospectiveNextCampaignFinalPostingPrepHandoffCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Final Posting Prep QA Bridge Kit',
      subtitle: 'Manual QA before posting operator brief',
      status: 'POSTING PREP QA',
      accent: '#4338CA',
      background: 'rgba(67,56,202,0.05)',
      border: '1px solid rgba(67,56,202,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the approved final posting prep handoff, launch copy, support route, consent queue, paid-language hold, no-paid-live note, and operator brief owner before manual posting operator prep starts.',
      buttonLabel: 'COPY POSTING PREP QA BRIDGE',
      copyText: launchRetrospectiveNextCampaignFinalPostingPrepQaBridgeCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Manual Posting Operator Handoff Kit',
      subtitle: 'Manual handoff into operator brief',
      status: 'OPERATOR HANDOFF',
      accent: '#312E81',
      background: 'rgba(49,46,129,0.05)',
      border: '1px solid rgba(49,46,129,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Hand off the approved final posting prep QA bridge, caption source, launch-card source, reply owner, consent proof, support route, and callback owner before any human posting operator receives instructions.',
      buttonLabel: 'COPY OPERATOR HANDOFF',
      copyText: launchRetrospectiveNextCampaignManualPostingOperatorHandoffCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Manual Posting Operator Brief QA Bridge Kit',
      subtitle: 'Manual QA before callback prep',
      status: 'OPERATOR QA',
      accent: '#1E1B4B',
      background: 'rgba(30,27,75,0.05)',
      border: '1px solid rgba(30,27,75,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check the manual posting operator handoff, caption source, launch-card source, reply owner, consent proof, support route, and callback owner before post-complete callback prep starts.',
      buttonLabel: 'COPY OPERATOR QA BRIDGE',
      copyText: launchRetrospectiveNextCampaignManualPostingOperatorBriefQaBridgeCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Post-Complete Callback Handoff Kit',
      subtitle: 'Manual handoff into callback QA',
      status: 'CALLBACK HANDOFF',
      accent: '#14532D',
      background: 'rgba(20,83,45,0.05)',
      border: '1px solid rgba(20,83,45,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Hand off the approved operator brief QA bridge, post-complete callback owner, first-party monitor owner, support route, consent queue, and review handoff owner before callback QA starts.',
      buttonLabel: 'COPY CALLBACK HANDOFF',
      copyText: launchRetrospectiveNextCampaignPostCompleteCallbackHandoffCopy,
    },
    {
      title: 'Launch Retrospective Next Campaign Post-Complete Callback QA Bridge Kit',
      subtitle: 'Manual QA before review handoff',
      status: 'CALLBACK QA',
      accent: '#166534',
      background: 'rgba(22,101,52,0.05)',
      border: '1px solid rgba(22,101,52,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Check callback handoff evidence, manual post-complete status, approved packet reference, support note, consent note, first-party monitor owner, and review handoff owner before review handoff starts.',
      buttonLabel: 'COPY CALLBACK QA BRIDGE',
      copyText: launchRetrospectiveNextCampaignPostCompleteCallbackQaBridgeCopy,
    },
  ];
}
