import { GOLD, DM_KEYWORD_PROMPTS } from './profileConstants';

export function buildWeeklyCampaignMetricKitSections({
  campaignPerformanceSummary,
  featureReviewQueue,
  launchRetrospectiveReadinessScriptCopy,
  recommendedLaunchExperiment,
  referralJoins,
  weeklyCampaignFirstDayMonitorCopy,
  weeklyCampaignExperimentBriefCopy,
  weeklyCampaignFinalPostingPrepQaCopy,
  weeklyCampaignLaunchCopyQaCopy,
  weeklyCampaignManualPostingOperatorBriefCopy,
  weeklyCampaignMidweekAdjustmentCopy,
  weeklyCampaignPreflightCopy,
  weeklyCampaignPrompt,
  weeklyCampaignReviewCopy,
  weeklyCampaignStoryboardCopy,
  weeklyCampaignWeekendPushDecisionCopy,
  weeklyCampaignSundayRecapQaCopy,
  weeklyCampaignNextWeekLaunchAngleCopy,
  weeklyCampaignPreflightAssetReadinessCopy,
  weeklyCampaignPreflightChecklistHandoffCopy,
  weeklyCampaignPreflightChecklistQaCopy,
  weeklyCampaignLaunchReadinessHandoffCopy,
  weeklyCampaignPreflightCopyFreezeCopy,
  weeklyCampaignPreflightGoNoGoCopy,
  weeklyCampaignPreflightLaunchPacketQaCopy,
  weeklyCampaignPreflightOwnerHandoffCopy,
  weeklyCampaignPreflightReadinessDecisionCopy,
}) {
  return [
    {
      title: 'Weekly Campaign Launch Copy QA Kit',
      subtitle: 'Manual copy check before posting',
      status: 'COPY QA',
      accent: '#38BDF8',
      background: 'rgba(56,189,248,0.05)',
      border: '1px solid rgba(56,189,248,0.16)',
      metrics: [
        ['CARD', weeklyCampaignPrompt.hashtag],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check launch-card, caption, Story/Reel hook, pinned comment, DM keyword, and referral copy before any manual weekly campaign post.',
      buttonLabel: 'COPY LAUNCH COPY QA',
      copyText: weeklyCampaignLaunchCopyQaCopy,
    },
    {
      title: 'Weekly Campaign First 24h Monitor Kit',
      subtitle: 'First-party signal readback after launch',
      status: '24H MONITOR',
      accent: '#60A5FA',
      background: 'rgba(96,165,250,0.05)',
      border: '1px solid rgba(96,165,250,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Review first-party app movement and support risk during the first 24 hours after a human weekly campaign launch.',
      buttonLabel: 'COPY 24H MONITOR',
      copyText: weeklyCampaignFirstDayMonitorCopy,
    },
    {
      title: 'Weekly Campaign Midweek Adjustment Kit',
      subtitle: 'Manual CTA decision from first-party signals',
      status: 'MIDWEEK',
      accent: '#818CF8',
      background: 'rgba(129,140,248,0.05)',
      border: '1px solid rgba(129,140,248,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Decide whether to repeat, clarify, support-route, comeback-invite, ask for consent, or hold follow-up copy midweek.',
      buttonLabel: 'COPY MIDWEEK ADJUSTMENT',
      copyText: weeklyCampaignMidweekAdjustmentCopy,
    },
    {
      title: 'Weekly Campaign Weekend Push Decision Kit',
      subtitle: 'Manual final-push decision from app signals',
      status: 'WEEKEND',
      accent: '#A78BFA',
      background: 'rgba(167,139,250,0.05)',
      border: '1px solid rgba(167,139,250,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Decide whether to approve, repeat, comeback-invite, feature proof, support-route, or hold weekend follow-up copy.',
      buttonLabel: 'COPY WEEKEND DECISION',
      copyText: weeklyCampaignWeekendPushDecisionCopy,
    },
    {
      title: 'Weekly Campaign Sunday Recap QA Kit',
      subtitle: 'Manual recap and next-week handoff check',
      status: 'RECAP QA',
      accent: '#C4B5FD',
      background: 'rgba(196,181,253,0.05)',
      border: '1px solid rgba(196,181,253,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check aggregate recap copy, consent-cleared proof, support-risk notes, and next-week handoff before any Sunday recap post.',
      buttonLabel: 'COPY SUNDAY RECAP QA',
      copyText: weeklyCampaignSundayRecapQaCopy,
    },
    {
      title: 'Weekly Campaign Next-Week Launch Angle Kit',
      subtitle: 'Manual next campaign angle decision',
      status: 'NEXT ANGLE',
      accent: '#FDBA74',
      background: 'rgba(253,186,116,0.05)',
      border: '1px solid rgba(253,186,116,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Choose the next-week launch angle from recap QA, campaign movement, consent-safe proof, and support-risk notes before preflight.',
      buttonLabel: 'COPY NEXT-WEEK ANGLE',
      copyText: weeklyCampaignNextWeekLaunchAngleCopy,
    },
    {
      title: 'Weekly Campaign Preflight Owner Handoff Kit',
      subtitle: 'Manual owner assignment before preflight',
      status: 'HANDOFF',
      accent: '#F59E0B',
      background: 'rgba(245,158,11,0.05)',
      border: '1px solid rgba(245,158,11,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Assign preflight owners for launch copy, manual replies, consent review, and support-risk routing before the next campaign preflight starts.',
      buttonLabel: 'COPY PREFLIGHT HANDOFF',
      copyText: weeklyCampaignPreflightOwnerHandoffCopy,
    },
    {
      title: 'Weekly Campaign Preflight Readiness Decision Kit',
      subtitle: 'Manual approve or hold decision before preflight',
      status: 'READY?',
      accent: '#22C55E',
      background: 'rgba(34,197,94,0.05)',
      border: '1px solid rgba(34,197,94,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Approve, clarify, support-route, wait for consent proof, repeat free-loop CTA, or hold paid-feature language before preflight.',
      buttonLabel: 'COPY PREFLIGHT DECISION',
      copyText: weeklyCampaignPreflightReadinessDecisionCopy,
    },
    {
      title: 'Weekly Campaign Preflight Copy Freeze Kit',
      subtitle: 'Manual freeze before preflight edits',
      status: 'FREEZE',
      accent: '#2DD4BF',
      background: 'rgba(45,212,191,0.05)',
      border: '1px solid rgba(45,212,191,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Freeze the launch-card headline, app-first CTA, manual replies, consent proof, and support-risk routing note before preflight edits.',
      buttonLabel: 'COPY PREFLIGHT FREEZE',
      copyText: weeklyCampaignPreflightCopyFreezeCopy,
    },
    {
      title: 'Weekly Campaign Preflight Asset Readiness Kit',
      subtitle: 'Manual launch asset prep check',
      status: 'ASSETS',
      accent: '#0EA5E9',
      background: 'rgba(14,165,233,0.05)',
      border: '1px solid rgba(14,165,233,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Confirm launch-card headline, caption input, Story/Reel hook, consent-safe proof, and support routing before final assets.',
      buttonLabel: 'COPY PREFLIGHT ASSETS',
      copyText: weeklyCampaignPreflightAssetReadinessCopy,
    },
    {
      title: 'Weekly Campaign Preflight Launch Packet QA Kit',
      subtitle: 'Manual final packet check before preflight',
      status: 'PACKET QA',
      accent: '#38BDF8',
      background: 'rgba(56,189,248,0.05)',
      border: '1px solid rgba(56,189,248,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check the launch-card headline, caption input, Story/Reel hook, CTA, consent proof, support note, and owner as one packet.',
      buttonLabel: 'COPY PACKET QA',
      copyText: weeklyCampaignPreflightLaunchPacketQaCopy,
    },
    {
      title: 'Weekly Campaign Preflight Go/No-Go Kit',
      subtitle: 'Manual final decision before preflight',
      status: 'GO/NO-GO',
      accent: '#22D3EE',
      background: 'rgba(34,211,238,0.05)',
      border: '1px solid rgba(34,211,238,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Choose go to preflight or hold for copy, assets, consent, support, free-loop, or paid-language blockers.',
      buttonLabel: 'COPY GO/NO-GO',
      copyText: weeklyCampaignPreflightGoNoGoCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist Handoff Kit',
      subtitle: 'Manual checklist owner handoff',
      status: 'HANDOFF',
      accent: '#67E8F9',
      background: 'rgba(103,232,249,0.05)',
      border: '1px solid rgba(103,232,249,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off the approved lane, packet reference, blockers, consent proof, support route, and checklist owner before preflight work starts.',
      buttonLabel: 'COPY CHECKLIST HANDOFF',
      copyText: weeklyCampaignPreflightChecklistHandoffCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist',
      subtitle: 'Manual launch readiness before posting',
      status: 'CHECKLIST',
      accent: '#14B8A6',
      background: 'rgba(20,184,166,0.05)',
      border: '1px solid rgba(20,184,166,0.16)',
      metrics: [
        ['CARD', weeklyCampaignPrompt.hashtag],
        ['DM', DM_KEYWORD_PROMPTS.length],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Confirm card copy, manual DM replies, content calendar, referral copy, consent-reviewed UGC, and first-party review metrics before the weekly push.',
      buttonLabel: 'COPY CAMPAIGN PREFLIGHT',
      copyText: weeklyCampaignPreflightCopy,
    },
    {
      title: 'Weekly Campaign Preflight Checklist QA Kit',
      subtitle: 'Manual completed-checklist review',
      status: 'CHECK QA',
      accent: '#5EEAD4',
      background: 'rgba(94,234,212,0.05)',
      border: '1px solid rgba(94,234,212,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Review the completed checklist, handoff, blockers, consent proof, support route, and launch readiness handoff before copy is treated as ready.',
      buttonLabel: 'COPY CHECKLIST QA',
      copyText: weeklyCampaignPreflightChecklistQaCopy,
    },
    {
      title: 'Weekly Campaign Launch Readiness Handoff Kit',
      subtitle: 'Manual ready-for-launch owner handoff',
      status: 'READY HANDOFF',
      accent: '#99F6E4',
      background: 'rgba(153,246,228,0.05)',
      border: '1px solid rgba(153,246,228,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Hand off the approved checklist, launch copy, reply owner, consent proof, support route, blockers, and launch operator before final posting copy.',
      buttonLabel: 'COPY READY HANDOFF',
      copyText: weeklyCampaignLaunchReadinessHandoffCopy,
    },
    {
      title: 'Weekly Campaign Final Posting Prep QA Kit',
      subtitle: 'Manual final posting packet check',
      status: 'POST QA',
      accent: '#A7F3D0',
      background: 'rgba(167,243,208,0.05)',
      border: '1px solid rgba(167,243,208,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Check the final caption, launch card, Story/Reel hook, CTA, reply boundary, consent proof, support route, and launch operator.',
      buttonLabel: 'COPY POSTING QA',
      copyText: weeklyCampaignFinalPostingPrepQaCopy,
    },
    {
      title: 'Weekly Campaign Manual Posting Operator Brief Kit',
      subtitle: 'Manual launch operator instructions',
      status: 'OPERATOR',
      accent: '#BBF7D0',
      background: 'rgba(187,247,208,0.05)',
      border: '1px solid rgba(187,247,208,0.16)',
      metrics: [
        ['ACTIVE', campaignPerformanceSummary.active || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
      ],
      body: 'Give the human posting operator the approved caption, launch card, Story/Reel hook, CTA, reply owner, consent proof, and support route.',
      buttonLabel: 'COPY OPERATOR BRIEF',
      copyText: weeklyCampaignManualPostingOperatorBriefCopy,
    },
    {
      title: 'Weekly Campaign Review Kit',
      subtitle: 'First-party weekly campaign review',
      status: 'REVIEW',
      accent: GOLD,
      background: 'rgba(251,191,36,0.05)',
      border: '1px solid rgba(251,191,36,0.16)',
      metrics: [
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
        ['DM', DM_KEYWORD_PROMPTS.length],
      ],
      body: "Review challenge joins, referral movement, consent-cleared UGC, manual DM copy, and share-card usage before shaping next week's push.",
      buttonLabel: 'COPY CAMPAIGN REVIEW',
      copyText: weeklyCampaignReviewCopy,
    },
    {
      title: 'Weekly Campaign Storyboard Kit',
      subtitle: 'Reels, Stories, and carousel outline',
      status: 'STORYBOARD',
      accent: '#F472B6',
      background: 'rgba(244,114,182,0.05)',
      border: '1px solid rgba(244,114,182,0.16)',
      metrics: [
        ['REEL', '4 BEATS'],
        ['STORY', '4 FRAMES'],
        ['POST', '5 SLIDES'],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Copy a manual Reel hook, Story frame plan, carousel outline, hashtag, and consent-safe publishing guardrails for this week's campaign.",
      buttonLabel: 'COPY STORYBOARD KIT',
      copyText: weeklyCampaignStoryboardCopy,
    },
    {
      title: 'Weekly Campaign Experiment Brief Kit',
      subtitle: 'Manual experiment from weekly campaign signals',
      status: recommendedLaunchExperiment.label.toUpperCase(),
      accent: '#C084FC',
      background: 'rgba(192,132,252,0.05)',
      border: '1px solid rgba(192,132,252,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['SIGNAL', recommendedLaunchExperiment.signal],
        ['WEEK', weeklyCampaignPrompt.week],
        ['TAG', weeklyCampaignPrompt.hashtag],
      ],
      body: "Connect this week's campaign CTA to the recommended manual experiment and review only first-party app movement afterward.",
      buttonLabel: 'COPY EXPERIMENT BRIEF',
      copyText: weeklyCampaignExperimentBriefCopy,
    },
    {
      title: 'Launch Retrospective Readiness Script Kit',
      subtitle: 'Manual first-party campaign readback before repeat decisions',
      status: 'RETRO',
      accent: '#F5D0FE',
      background: 'rgba(245,208,254,0.05)',
      border: '1px solid rgba(245,208,254,0.16)',
      metrics: [
        ['TEST', recommendedLaunchExperiment.label],
        ['REACH', campaignPerformanceSummary.memberReach || 0],
        ['REF', referralJoins],
        ['UGC', featureReviewQueue.length],
      ],
      body: 'Copy a first-party retrospective readiness script before repeating, pausing, or escalating a launch experiment.',
      buttonLabel: 'COPY RETRO READINESS SCRIPT',
      copyText: launchRetrospectiveReadinessScriptCopy,
    },
  ];
}
