import { WEEKLY_CAMPAIGN_LIVE_COPY_CARD_DEFINITIONS } from './weeklyCampaignLiveCopyCardDefinitions';
import { WEEKLY_CAMPAIGN_STORY_COPY_CARD_DEFINITIONS } from './weeklyCampaignStoryCopyCardDefinitions';

export const SIMPLE_WEEKLY_CAMPAIGN_COPY_CARD_DEFINITIONS = [
  ...WEEKLY_CAMPAIGN_STORY_COPY_CARD_DEFINITIONS,
  ...WEEKLY_CAMPAIGN_LIVE_COPY_CARD_DEFINITIONS,
];
