export const BADGE_CATEGORIES = [
  { id: "all",       label: "All",        icon: "✨" },
  { id: "streak",    label: "Streak",     icon: "🔥" },
  { id: "points",    label: "Milestones", icon: "⭐" },
  { id: "activity",  label: "Activity",   icon: "💪" },
  { id: "challenge", label: "Challenges", icon: "🎯" },
  { id: "special",   label: "Special",    icon: "👑" },
];

export const BADGES = [
  { id: "first_log",  cat: "streak",    icon: "🌱", label: "First Step",        desc: "Log your very first activity",                color: "#34D399", xp: 10  },
  { id: "streak3",    cat: "streak",    icon: "🔥", label: "On Fire",            desc: "3-day activity streak",                       color: "#FF6B35", xp: 25  },
  { id: "streak7",    cat: "streak",    icon: "⚡", label: "Week Warrior",       desc: "7-day activity streak",                       color: "#FFD700", xp: 50  },
  { id: "streak14",   cat: "streak",    icon: "💎", label: "Two Weeks Strong",   desc: "14-day activity streak",                      color: "#38BDF8", xp: 100 },
  { id: "streak30",   cat: "streak",    icon: "🏆", label: "Month Legend",       desc: "30-day activity streak",                      color: "#F59E0B", xp: 250 },
  { id: "streak75",   cat: "streak",    icon: "👑", label: "75 Hard Spirit",     desc: "75-day activity streak — the ultimate test",  color: "#C084FC", xp: 750 },
  { id: "pts50",      cat: "points",    icon: "🌟", label: "Getting Started",    desc: "Earn 50 total points",                        color: "#34D399", xp: 10  },
  { id: "pts100",     cat: "points",    icon: "💯", label: "Century Club",       desc: "Earn 100 total points",                       color: "#C084FC", xp: 20  },
  { id: "pts500",     cat: "points",    icon: "🚀", label: "Rising Star",        desc: "Earn 500 total points",                       color: "#F59E0B", xp: 75  },
  { id: "pts1000",    cat: "points",    icon: "💫", label: "Elite",              desc: "Earn 1,000 total points",                     color: "#FFD700", xp: 150 },
  { id: "pts5000",    cat: "points",    icon: "☄️", label: "Tribe Legend",      desc: "Earn 5,000 total points",                     color: "#FF6B35", xp: 500 },
  { id: "days10",     cat: "points",    icon: "📅", label: "Ten Club",           desc: "Be active on 10 different days",              color: "#34D399", xp: 30  },
  { id: "days30",     cat: "points",    icon: "🗓️", label: "Thirty Strong",     desc: "Be active on 30 different days",              color: "#60A5FA", xp: 100 },
  { id: "run_50km",   cat: "activity",  icon: "🏃", label: "Road Runner",        desc: "Run 50km total",                              color: "#34D399", xp: 75  },
  { id: "yoga_10",    cat: "activity",  icon: "🧘", label: "Zen Tribe",          desc: "10 yoga sessions",                            color: "#A78BFA", xp: 50  },
  { id: "gym_15",     cat: "activity",  icon: "💪", label: "Iron Tribe",         desc: "Hit the gym 15 times",                        color: "#F59E0B", xp: 75  },
  { id: "cycle_100",  cat: "activity",  icon: "🚴", label: "Cyclone",            desc: "Cycle 100km total",                           color: "#60A5FA", xp: 100 },
  { id: "swim_10",    cat: "activity",  icon: "🏊", label: "Deep Diver",         desc: "10 swim sessions",                            color: "#38BDF8", xp: 60  },
  { id: "walk_50",    cat: "activity",  icon: "🚶", label: "Wanderer",           desc: "Walk 50km total",                             color: "#4ADE80", xp: 40  },
  { id: "allround",   cat: "activity",  icon: "🌈", label: "All-Rounder",        desc: "Log 3 different activity types",              color: "#C084FC", xp: 40  },
  { id: "variety",    cat: "activity",  icon: "🎪", label: "Variety Pack",       desc: "Try all 6 activity types",                    color: "#F59E0B", xp: 100 },
  { id: "first_join", cat: "challenge", icon: "🤝", label: "Tribe Member",       desc: "Join your first challenge",                   color: "#60A5FA", xp: 30  },
  { id: "creator",    cat: "challenge", icon: "🎯", label: "Challenge Creator",  desc: "Create your first challenge",                 color: "#FF6B35", xp: 50  },
  { id: "squad",      cat: "challenge", icon: "👥", label: "Squad Goals",        desc: "Join 3 different challenges",                 color: "#A78BFA", xp: 75  },
  { id: "connector",  cat: "challenge", icon: "📣", label: "Connector",          desc: "Bring 1 friend into a challenge",             color: "#34D399", xp: 50  },
  { id: "tribe_builder", cat: "challenge", icon: "🤝", label: "Tribe Builder",   desc: "Bring 5 friends into challenges",             color: "#FF6B35", xp: 150 },
  { id: "community_captain", cat: "challenge", icon: "🌟", label: "Community Captain", desc: "Bring 10 friends into challenges",      color: "#FFD700", xp: 300 },
  { id: "finisher",   cat: "challenge", icon: "✅", label: "Finisher",           desc: "Complete a full challenge",                   color: "#34D399", xp: 200 },
  { id: "champion",   cat: "challenge", icon: "🥇", label: "Champion",           desc: "Finish #1 on a challenge leaderboard",        color: "#FFD700", xp: 300 },
  { id: "og_tribe",   cat: "special",   icon: "🌅", label: "OG Tribe",           desc: "Founding tribe member — you were here first", color: "#FF6B35", xp: 100 },
  { id: "comeback",   cat: "special",   icon: "🦾", label: "Comeback King",      desc: "Log after a 3+ day gap — never quit",         color: "#F59E0B", xp: 50  },
  { id: "weekend_w",  cat: "special",   icon: "🎉", label: "Weekend Warrior",    desc: "Log on both Saturday and Sunday",             color: "#C084FC", xp: 40  },
  { id: "no_excuses", cat: "special",   icon: "🧱", label: "No Excuses",         desc: "Log 5 sessions in a single week",             color: "#38BDF8", xp: 60  },
  { id: "pro_weekly_report", cat: "special", icon: "📈", label: "Pro Weekly Report", desc: "Tribe Pro: hit 5 active logs in a week",   color: "#A78BFA", xp: 120 },
  { id: "pro_streak_saver",  cat: "special", icon: "🛡️", label: "Streak Saver",      desc: "Tribe Pro: use a streak recovery credit",  color: "#34D399", xp: 90  },
  { id: "pro_finisher",      cat: "special", icon: "🏁", label: "Pro Finisher",       desc: "Tribe Pro: complete a full challenge",     color: "#FFD700", xp: 180 },
];

export const TRIBE_RANKS = [
  { label: "Rookie",    min: 0,    icon: "🌱", color: "#34D399" },
  { label: "Warrior",   min: 100,  icon: "⚔️",  color: "#60A5FA" },
  { label: "Elite",     min: 300,  icon: "🚀", color: "#F59E0B" },
  { label: "Legend",    min: 700,  icon: "💫", color: "#FFD700" },
  { label: "Tribe God", min: 1500, icon: "👑", color: "#C084FC" },
];
