export const CORE_CAMPAIGN_CHALLENGE_TEMPLATES = [
  {
    id: 'weekly_reset',
    name: '7-Day Tribe Reset',
    emoji: '🚀',
    color: '#F97316',
    duration: 7,
    tagline: 'A campaign-ready week of movement, hydration, and accountability',
    difficulty: 'Beginner-friendly',
    campaignId: 'weekly-reset',
    campaignLabel: 'Weekly Campaign',
    campaignHashtag: '#RiseWithTheTribe',
    campaignCta: 'Tag @risewiththetribe with your Day 1 proof and invite one friend.',
    sponsorName: 'Tribe Partner Preview',
    sponsorLabel: 'Member Perk',
    sponsorPerk: 'Future partner rewards can attach to challenge campaigns without changing the core habit loop.',
    sponsorUrl: '',
    rules: [
      'Move for at least 20 minutes every day',
      'Drink 2 litres of water daily',
      'Log your activity in the app before bed',
      'Share one progress update and tag @risewiththetribe',
      'Invite one accountability partner before Day 3',
    ],
    tasks: [
      { id: 'move', label: '20+ minutes of movement', emoji: '🏃' },
      { id: 'water', label: '2 L of water', emoji: '💧' },
      { id: 'log', label: 'Logged activity in app', emoji: '📱' },
      { id: 'share', label: 'Shared or encouraged the tribe', emoji: '📣' },
    ],
    disclaimer: 'This challenge is designed for general accountability and is not medical advice. Adjust movement and hydration targets to your needs and consult a healthcare professional when appropriate.',
  },
  {
    id: 'comeback_week',
    name: 'Comeback Week',
    emoji: '⚡',
    color: '#34D399',
    duration: 7,
    tagline: 'Restart your streak without overthinking it',
    difficulty: 'Easy',
    campaignId: 'comeback-week',
    campaignLabel: 'Instagram Challenge',
    campaignHashtag: '#TribeComeback',
    campaignCta: 'Post your comeback win and tag @risewiththetribe to be featured.',
    rules: [
      'Complete one low-friction activity every day',
      'Keep the promise small enough that you cannot dodge it',
      'Log activity in the app daily',
      'Share your comeback moment once during the week',
    ],
    tasks: [
      { id: 'activity', label: 'Completed any activity', emoji: '✅' },
      { id: 'logged', label: 'Logged in the app', emoji: '📱' },
      { id: 'reflection', label: 'Noted one win', emoji: '📝' },
    ],
    disclaimer: 'This challenge is intended to rebuild consistency. Choose activity intensity that matches your current fitness level.',
  },
  {
    id: '30tribe',
    name: '30-Day Tribe',
    emoji: '⚡',
    color: '#34D399',
    duration: 30,
    tagline: 'A month of movement with your people',
    difficulty: 'Beginner-friendly',
    campaignId: '30-day-tribe',
    campaignLabel: 'Core Campaign',
    campaignHashtag: '#30DayTribe',
    campaignCta: 'Share your Day 1 and tag @risewiththetribe so the tribe can cheer you on.',
    rules: [
      'Complete at least one workout per day',
      'Log every activity in the app',
      'Any activity counts — run, walk, yoga, gym, swim, cycle',
      'Encourage at least one tribe member per week',
    ],
    tasks: [
      { id: 'workout', label: 'Completed a workout', emoji: '🏃' },
      { id: 'logged',  label: 'Logged activity in app', emoji: '📱' },
    ],
    disclaimer: 'This challenge is designed for all fitness levels. Rest days are at your own discretion — listen to your body. Rise With The Tribe is not a medical provider. Consult a healthcare professional before starting a new exercise programme.',
  },
];
