export const CORE_LONG_FORM_CHALLENGE_TEMPLATES = [
  {
    id: '75hard',
    name: '75 Hard',
    emoji: '🔥',
    color: '#FF6B35',
    duration: 75,
    tagline: 'The original mental toughness programme',
    difficulty: 'Extreme',
    rules: [
      'Two 45-minute workouts per day — one MUST be outdoors, regardless of weather',
      'Follow a structured diet with zero alcohol and zero cheat meals for all 75 days',
      'Drink 1 gallon (3.8 L) of water every day',
      'Read 10 pages of a non-fiction or self-development book (audiobooks do NOT count)',
      'Take a daily progress photo',
      'Miss ANY single task on ANY day → restart from Day 1, no exceptions',
    ],
    tasks: [
      { id: 'workout1', label: 'Workout 1 — 45 min', emoji: '💪' },
      { id: 'workout2', label: 'Outdoor workout — 45 min', emoji: '🌤' },
      { id: 'diet',     label: 'Followed diet, no alcohol', emoji: '🥗' },
      { id: 'water',    label: '1 gallon of water drunk', emoji: '💧' },
      { id: 'reading',  label: '10 pages read', emoji: '📚' },
      { id: 'photo',    label: 'Progress photo taken', emoji: '📸' },
    ],
    disclaimer: '75 Hard was created by Andy Frisella. It is intentionally extreme and is a mental toughness programme — NOT a fitness programme. The "restart from Day 1" rule is non-negotiable by design. Consult a physician before beginning. Rise With The Tribe is not affiliated with Andy Frisella or the official 75 Hard programme and makes no medical claims.',
  },
  {
    id: '75soft',
    name: '75 Soft',
    emoji: '🌊',
    color: '#60A5FA',
    duration: 75,
    tagline: 'Build lasting habits — no burnout, no restart',
    difficulty: 'Moderate',
    rules: [
      'One 45-minute workout per day (indoors or outdoors)',
      'Be mindful of food choices 90% of the time — one social meal per week allowed',
      'Drink 3 litres of water every day',
      'Read or listen to 10 minutes of personal development daily',
      'Meditate for at least 5 minutes daily',
      'No perfection required — missing a day does not reset your streak',
    ],
    tasks: [
      { id: 'workout',   label: 'Workout — 45 min', emoji: '💪' },
      { id: 'water',     label: '3 L of water drunk', emoji: '💧' },
      { id: 'diet',      label: 'Ate mindfully today', emoji: '🥗' },
      { id: 'reading',   label: '10 min personal development', emoji: '📚' },
      { id: 'meditate',  label: '5 min meditation', emoji: '🧘' },
    ],
    disclaimer: '75 Soft is a community-adapted programme inspired by 75 Hard. It is not an official programme and is not affiliated with Andy Frisella. Always consult a healthcare provider before starting any new fitness or nutrition regimen. Rise With The Tribe is not a medical provider and makes no health claims.',
  },
];
