export const ONBOARDING_QUESTIONS = [
  {
    id: 'goal',
    emoji: '🎯',
    question: "What's your main goal?",
    subtitle: 'This shapes your whole challenge experience',
    multi: false,
    cols: 2,
    options: [
      { id: 'lose_weight',    emoji: '🔥', label: 'Lose Weight' },
      { id: 'build_muscle',   emoji: '💪', label: 'Build Muscle' },
      { id: 'endurance',      emoji: '🏃', label: 'Improve Endurance' },
      { id: 'stress',         emoji: '🧘', label: 'Reduce Stress' },
      { id: 'energy',         emoji: '⚡', label: 'Boost Energy' },
    ],
  },
  {
    id: 'level',
    emoji: '📊',
    question: 'Current fitness level?',
    subtitle: "Be honest — we'll tailor the challenge to you",
    multi: false,
    cols: 2,
    options: [
      { id: 'beginner',  emoji: '🌱', label: 'Just Starting',    desc: '0–1 workouts / week' },
      { id: 'moderate',  emoji: '🚶', label: 'Somewhat Active',  desc: '2–3 workouts / week' },
      { id: 'fit',       emoji: '🏃', label: 'Pretty Fit',       desc: '4–5 workouts / week' },
      { id: 'athlete',   emoji: '🦅', label: 'Very Athletic',    desc: '6+ workouts / week' },
    ],
  },
  {
    id: 'activities',
    emoji: '🏋️',
    question: 'Activities you love?',
    subtitle: 'Pick everything that gets you moving',
    multi: true,
    cols: 3,
    options: [
      { id: 'run',   emoji: '🏃', label: 'Run' },
      { id: 'yoga',  emoji: '🧘', label: 'Yoga' },
      { id: 'gym',   emoji: '💪', label: 'Gym' },
      { id: 'cycle', emoji: '🚴', label: 'Cycle' },
      { id: 'swim',  emoji: '🏊', label: 'Swim' },
      { id: 'walk',  emoji: '🚶', label: 'Walk' },
    ],
  },
  {
    id: 'frequency',
    emoji: '📅',
    question: 'How often will you train?',
    subtitle: 'Consistency beats intensity every time',
    multi: false,
    cols: 2,
    options: [
      { id: '2_3',      emoji: '🌿', label: '2–3× a week' },
      { id: '4_5',      emoji: '💪', label: '4–5× a week' },
      { id: 'daily',    emoji: '🔥', label: 'Every day' },
      { id: 'flexible', emoji: '🎯', label: 'Flexible' },
    ],
  },
  {
    id: 'time',
    emoji: '⏰',
    question: 'Best time to train?',
    subtitle: "We'll cheer you on at the right moment",
    multi: false,
    cols: 2,
    options: [
      { id: 'early',     emoji: '🌅', label: 'Early Bird',  desc: 'Before 7 am' },
      { id: 'morning',   emoji: '☀️',  label: 'Morning',    desc: '7 am – 12 pm' },
      { id: 'afternoon', emoji: '🌤',  label: 'Afternoon',  desc: '12 pm – 5 pm' },
      { id: 'evening',   emoji: '🌙', label: 'Evening',     desc: 'After 5 pm' },
    ],
  },
  {
    id: 'motivation',
    emoji: '🚀',
    question: 'What drives you most?',
    subtitle: 'Your tribe wants to know',
    multi: false,
    cols: 2,
    options: [
      { id: 'compete',   emoji: '🏆', label: 'Beating others' },
      { id: 'progress',  emoji: '📈', label: 'My own progress' },
      { id: 'community', emoji: '👥', label: 'The community' },
      { id: 'records',   emoji: '⚡', label: 'Personal records' },
    ],
  },
];

export {
  ONBOARDING_ACTIVITY_LABELS,
  ONBOARDING_FREQUENCY_LABELS,
  ONBOARDING_GOAL_LABELS,
  ONBOARDING_LEVEL_LABELS,
} from './onboardingLabels';
