export const ONBOARDING_QUESTIONS = [
  {
    id: 'privacy',
    icon: '🔒',
    question: 'You control what TribeLog can use',
    subtitle: 'Choose whether you want TribeLog to prepare health sync. We only ask for Apple Health or Health Connect permission after you choose a sync path.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'sync_data', label: 'Sync my workout data', desc: 'Prepare Apple Health or Health Connect so workouts and steps can import when you approve permission.' },
      { id: 'manual_first', label: 'Manual logging for now', desc: 'Start without health permissions and connect a data source later from Profile.' },
    ],
  },
  {
    id: 'level',
    icon: '📊',
    question: 'Where are you in your fitness journey?',
    subtitle: 'TribeLog works whether you are just restarting or already training hard.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'beginner', label: 'Beginner', desc: 'I am new to fitness or getting back into it.' },
      { id: 'moderate', label: 'Intermediate', desc: 'I can do easy to moderate activities.' },
      { id: 'fit', label: 'Advanced', desc: 'I like to push myself with harder sessions.' },
      { id: 'athlete', label: 'Very active', desc: 'Training is already part of my routine.' },
    ],
  },
  {
    id: 'goal',
    icon: '🎯',
    question: 'What do you want TribeLog to help with first?',
    subtitle: 'Pick the outcome that matters most right now. You can change it later.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'consistency', label: 'Build an exercise habit', desc: 'Use streaks and challenges to keep showing up.' },
      { id: 'strength', label: 'Get stronger', desc: 'Log gym work and watch your effort compound.' },
      { id: 'endurance', label: 'Improve endurance', desc: 'Track runs, walks, rides, swims, and steps.' },
      { id: 'wellbeing', label: 'Feel healthier', desc: 'Use movement as a simple daily reset.' },
    ],
  },
  {
    id: 'activities',
    icon: '🏋️',
    question: 'What types of activities do you like to do?',
    subtitle: 'Choose as many as apply. These become your quick logging shortcuts.',
    multi: true,
    layout: 'grid',
    cols: 2,
    options: [
      { id: 'run',   emoji: '🏃', label: 'Run' },
      { id: 'walk',  emoji: '🚶', label: 'Walk' },
      { id: 'steps', emoji: '👟', label: 'Steps' },
      { id: 'gym',   emoji: '💪', label: 'Gym' },
      { id: 'yoga',  emoji: '🧘', label: 'Yoga' },
      { id: 'cycle', emoji: '🚴', label: 'Cycle' },
      { id: 'swim',  emoji: '🏊', label: 'Swim' },
      { id: 'other', emoji: '⚡', label: 'Other' },
    ],
  },
  {
    id: 'frequency',
    icon: '📅',
    question: 'How often do you want to show up?',
    subtitle: 'A realistic rhythm makes the first challenge feel achievable.',
    multi: false,
    layout: 'list',
    options: [
      { id: '2_3', label: '2-3 times a week', desc: 'A steady start without pressure.' },
      { id: '4_5', label: '4-5 times a week', desc: 'A strong weekly rhythm.' },
      { id: 'daily', label: 'Every day', desc: 'I want the streak to pull me forward.' },
      { id: 'flexible', label: 'Flexible', desc: 'I will log when life allows.' },
    ],
  },
  {
    id: 'motivation',
    icon: '🔥',
    question: 'What kind of motivation works best for you?',
    subtitle: 'This helps TribeLog make the home screen feel more useful.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'progress', label: 'Seeing my progress', desc: 'Charts, streaks, and personal bests.' },
      { id: 'community', label: 'Moving with others', desc: 'Tribe activity, challenges, and leaderboards.' },
      { id: 'accountability', label: 'Being reminded', desc: 'Helpful nudges when I forget to log.' },
      { id: 'competition', label: 'Friendly competition', desc: 'A little leaderboard energy.' },
    ],
  },
  {
    id: 'dataSource',
    icon: '⌚',
    question: 'Which device or data source should TribeLog prepare for?',
    subtitle: 'Choose the path that best matches how you track. You can connect more sources later.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'manual', label: 'No wearable yet', desc: 'Start with manual logs and challenge check-ins.' },
      { id: 'apple_watch', label: 'Apple Watch', desc: 'Import workouts and steps through Apple Health on iOS.' },
      { id: 'health_connect', label: 'Android watch / Health Connect', desc: 'Import workouts and steps through Health Connect on Android.' },
      { id: 'garmin', label: 'Garmin', desc: 'Use Apple Health or Health Connect as the bridge when available.' },
      { id: 'oura', label: 'Oura', desc: 'Use sleep/recovery context later without blocking challenge logging.' },
      { id: 'other_health', label: 'Other via health app', desc: 'Any source that writes supported workouts or steps.' },
    ],
  },
  {
    id: 'healthSync',
    icon: '💚',
    question: 'How much health sync do you want at the start?',
    subtitle: 'TribeLog keeps this lightweight: activity sync supports accountability, not medical advice.',
    multi: false,
    layout: 'list',
    options: [
      { id: 'workouts_steps', label: 'Sync workouts and steps', desc: 'Best for Apple Watch, Garmin, Oura, and Android watches when data is available.' },
      { id: 'advanced_later', label: 'Show advanced sync later', desc: 'Sleep, heart, HRV, and recovery-style data can wait until those features are real.' },
      { id: 'manual_first', label: 'Manual logging first', desc: 'Skip health permissions and start with the first challenge.' },
    ],
  },
];

export {
  ONBOARDING_ACTIVITY_LABELS,
  ONBOARDING_DATA_SOURCE_LABELS,
  ONBOARDING_FREQUENCY_LABELS,
  ONBOARDING_GOAL_LABELS,
  ONBOARDING_HEALTH_SYNC_LABELS,
  ONBOARDING_LEVEL_LABELS,
  ONBOARDING_MOTIVATION_LABELS,
  ONBOARDING_PRIVACY_LABELS,
} from './onboardingLabels';
