export const PREMIUM_CHALLENGE_TEMPLATES = [
  {
    id: 'premium_21_reset',
    name: '21-Day Reset Pack',
    emoji: '💎',
    color: '#A78BFA',
    duration: 21,
    tagline: 'A structured premium reset with movement, recovery, and accountability',
    difficulty: 'Structured',
    isPremium: true,
    packId: '21_day_reset',
    packLabel: 'Premium Pack',
    rules: [
      'Complete one intentional movement session each day',
      'Hit your hydration target and log it',
      'Complete one recovery or mindset task daily',
      'Share a weekly proof update with the tribe',
      'Invite one accountability partner before Day 5',
    ],
    tasks: [
      { id: 'movement', label: 'Intentional movement completed', emoji: '🏃' },
      { id: 'hydration', label: 'Hydration target hit', emoji: '💧' },
      { id: 'recovery', label: 'Recovery or mindset task', emoji: '🧘' },
      { id: 'proof', label: 'Progress proof logged', emoji: '📸' },
    ],
    dailyPrompts: [
      'What is the smallest win you can protect today?',
      'Send one accountability check-in before the day gets busy.',
      'Choose recovery with the same discipline as training.',
    ],
    disclaimer: 'This premium challenge pack is for accountability and habit formation. It is not medical advice. Adjust intensity to your needs and consult a healthcare professional when appropriate.',
  },
  {
    id: 'premium_beginner_consistency',
    name: 'Beginner Consistency Plan',
    emoji: '🌱',
    color: '#34D399',
    duration: 14,
    tagline: 'A gentle premium starter plan for movement, recovery, and confidence',
    difficulty: 'Beginner',
    isPremium: true,
    packId: 'beginner_consistency',
    packLabel: 'Beginner Pack',
    rules: [
      'Complete one approachable movement session each day',
      'Log how the session felt, not just the result',
      'Take one planned recovery or mobility step',
      'Share one weekly proof update only if it helps accountability',
    ],
    tasks: [
      { id: 'movement', label: 'Beginner movement completed', emoji: '🌱' },
      { id: 'checkin', label: 'Confidence check-in logged', emoji: '📝' },
      { id: 'recovery', label: 'Recovery or mobility step', emoji: '🧘' },
    ],
    dailyPrompts: [
      'Make the session easy enough to repeat tomorrow.',
      'Write one sentence about what helped you start.',
      'Choose consistency over intensity today.',
    ],
    disclaimer: 'This premium challenge pack is for accountability and habit formation. It is not medical advice. Adjust intensity to your needs and consult a healthcare professional when appropriate.',
  },
  {
    id: 'premium_30_discipline',
    name: '30-Day Discipline Challenge',
    emoji: '🎯',
    color: '#F97316',
    duration: 30,
    tagline: 'A focused premium plan for consistent training, recovery, and proof',
    difficulty: 'Intermediate',
    isPremium: true,
    packId: 'discipline_30',
    packLabel: 'Discipline Pack',
    rules: [
      'Complete one planned training or movement session each day',
      'Log one discipline proof note before the day ends',
      'Protect one recovery habit so consistency stays sustainable',
      'Share a weekly progress proof with the tribe',
      'Review the next week plan every seventh day',
    ],
    tasks: [
      { id: 'training', label: 'Planned session completed', emoji: '🎯' },
      { id: 'proof', label: 'Discipline proof logged', emoji: '📝' },
      { id: 'recovery', label: 'Recovery habit protected', emoji: '🧘' },
      { id: 'review', label: 'Weekly plan reviewed', emoji: '📌' },
    ],
    dailyPrompts: [
      'What is the one promise you will keep today?',
      'Log the proof before motivation gets a vote.',
      'Make tomorrow easier by choosing recovery today.',
    ],
    disclaimer: 'This premium challenge pack is for accountability and habit formation. It is not medical advice. Adjust intensity to your needs and consult a healthcare professional when appropriate.',
  },
];
