export const SEASONAL_CHALLENGE_TEMPLATES = [
  {
    id: 'seasonal_summer_shred',
    name: '28-Day Summer Shred',
    emoji: '☀️',
    color: '#F59E0B',
    duration: 28,
    tagline: 'A premium seasonal push for training, nutrition consistency, and visible proof',
    difficulty: 'Intermediate',
    campaignId: 'summer-shred',
    campaignLabel: 'Seasonal Drop',
    campaignHashtag: '#TribeSummerShred',
    campaignCta: 'Share your weekly check-in and tag @risewiththetribe for the seasonal leaderboard.',
    isPremium: true,
    packId: 'summer_shred',
    packLabel: 'Seasonal Pack',
    rules: [
      'Complete one focused training session each day',
      'Log protein or balanced meal consistency',
      'Complete one recovery habit daily',
      'Share a weekly progress check-in',
      'Invite one accountability partner before Day 7',
    ],
    tasks: [
      { id: 'training', label: 'Focused training completed', emoji: '💪' },
      { id: 'nutrition', label: 'Nutrition target hit', emoji: '🥗' },
      { id: 'recovery', label: 'Recovery habit completed', emoji: '🧘' },
      { id: 'proof', label: 'Progress proof logged', emoji: '📸' },
    ],
    dailyPrompts: [
      'Post one honest progress proof, not a perfect one.',
      'Win the next meal, then win the next session.',
      'Check in with your accountability partner before you log off.',
    ],
    disclaimer: 'This seasonal challenge is for accountability and general fitness habit formation. It is not medical or nutrition advice. Adjust targets to your needs and consult a qualified professional when appropriate.',
  },
  {
    id: 'seasonal_winter_base',
    name: '14-Day Winter Base',
    emoji: '❄️',
    color: '#38BDF8',
    duration: 14,
    tagline: 'Build a steady base when motivation is low',
    difficulty: 'Beginner-friendly',
    campaignId: 'winter-base',
    campaignLabel: 'Seasonal Campaign',
    campaignHashtag: '#TribeWinterBase',
    campaignCta: 'Post your daily base-building win and tag @risewiththetribe.',
    rules: [
      'Move for at least 20 minutes daily',
      'Log one simple recovery action',
      'Complete one hydration check-in',
      'Encourage one tribe member during the challenge',
    ],
    tasks: [
      { id: 'move', label: '20+ minutes of movement', emoji: '🏃' },
      { id: 'recovery', label: 'Recovery action completed', emoji: '🧘' },
      { id: 'hydration', label: 'Hydration check-in', emoji: '💧' },
      { id: 'support', label: 'Encouraged the tribe', emoji: '📣' },
    ],
    disclaimer: 'This challenge is designed for general accountability. Choose activity intensity that matches your current fitness level.',
  },
];
